Repository mapbox/mapbox-navigation-ios, pull requests merged in 2018-06, with the labels that each got.

#1385 Dead-reckon user puck
  MapboxCoreNavigation/CLLocation.swift
  MapboxCoreNavigationTests/LocationTests.swift
  MapboxCoreNavigationTests/RouteControllerTests.swift
Labels: ✓ ready for review

#1469 ImageDownloader creates and mutates downloads within a barrier block
  MapboxNavigation/ImageDownload.swift
  MapboxNavigation/ImageDownloader.swift
Labels: - bug, ⏎ Ready To Merge

#1509 Exit View Sizing Fix
  MapboxNavigation/RouteMapViewController.swift
Labels: - bug, ✓ ready for review
