Repository mapbox/mapbox-navigation-ios, pull requests merged in 2018-08, with the labels that each got.

#1576 Retrieve additional map attributes to display reliable current road name.
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/HighwayShield.swift
  MapboxNavigation/InstructionPresenter.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/Style.swift
  MapboxNavigation/UIImage.swift
Labels: ✓ ready for review

#1533 Break out events
  MapboxCoreNavigation/Array.swift
  MapboxCoreNavigation/Constants.swift
  MapboxCoreNavigation/CoreFeedbackEvent.swift
  MapboxCoreNavigation/EndOfRouteFeedback.swift
  MapboxCoreNavigation/EventDetails.swift
  MapboxCoreNavigation/EventsManager.swift
  MapboxCoreNavigation/MMEEventsManager.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigation/RouteControllerDelegate.swift
  MapboxCoreNavigation/RouteProgress.swift
  MapboxCoreNavigation/Router.swift
  MapboxCoreNavigation/SessionState.swift
  MapboxCoreNavigationTests/BridgingTests.m
  MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  MapboxCoreNavigationTests/RouteControllerTests.swift
  MapboxCoreNavigationTests/Support/MMEEventsManagerSpy.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Resources/Assets.xcassets/feedback-closed-road.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback-gps.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback-map-error.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback-missing-road.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback-no-turn-allowed.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback-wrong-directions.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback_car_crash.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback_routing.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback_turn_not_allowed.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/overview.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/volume_off.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/volume_up.imageset/Contents.json
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigationTests/LaneTests.swift
Labels: - refactor, topic: location, topic: telemetry, ⏎ Ready To Merge, ✓ ready for review

#1583 Ensures status view banner text doesn't get stuck on rerouting in simulation mode.
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/String+LocalizedConstants.swift
Labels: - bug, quick fix, ✓ ready for review

#1588 Fixed the disappearance of the drag step list handlebar defect
  MapboxNavigation/RouteMapViewController.swift
Labels: - bug, quick fix

#1584 Revised recent entries in the change log
  CHANGELOG.md
Labels: quick fix, ✓ ready for review

#1589 Fixed the partial style of user interface whenever styles are switched.
  CHANGELOG.md
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/RouteMapViewController.swift
Labels: - bug, ✓ ready for review

#1599 Don't force unwrap userInfo keys
  CHANGELOG.md
  MapboxNavigation/RouteMapViewController.swift
Labels: - crash

#1606 Missing telemetry vales
  MapboxCoreNavigation/EventDetails.swift
Labels: - bug, quick fix, topic: telemetry

#1610 Merge v0.19.1 back to master
  CHANGELOG.md
  Examples/Objective-CTests/Info.plist
  Examples/SwiftTests/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  RouteTest/Info.plist
Labels: - build

#1611 Remove stray reference to nonexistent script
  scripts/document.sh
Labels: - build, documentation, topic: documentation

#1613 Add incidents toggle
  CHANGELOG.md
  MapboxNavigation/MGLMapView.swift
Labels: - feature, topic: traffic

#1619 Upgrade to v4 navigation styles
  CHANGELOG.md
  Examples/Objective-C/Base.lproj/Main.storyboard
  Examples/Swift/Base.lproj/Main.storyboard
  MapboxNavigation/MGLStyle.swift
Labels: topic: cartography, topic: traffic

#1632 Cache pod master repo on CircleCI
  circle.yml
Labels: ✓ ready for review

#1640 Objective-C Example Bug: Doublespeak
  Examples/Objective-C/ViewController.m
Labels: quick fix, ✓ ready for review

#1645 Permit routeless events manager for unique telemetry events
  MapboxCoreNavigation/EventDetails.swift
  MapboxCoreNavigation/EventsManager.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/FeedbackViewController.swift
Labels: - refactor, CarPlay
