Repository mapbox/mapbox-navigation-ios, pull requests merged in 2018-02, with the labels that each got.

#617 Use MapboxVoice instead of aws
  CONTRIBUTING.md
  Cartfile
  Cartfile.resolved
  Examples/Swift/CustomViewController.swift
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/ErrorCode.swift
  MapboxNavigation/MapboxSpeechController.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/PollyVoiceController.swift
  MapboxNavigation/RouteVoiceController.swift
  README.md
  languages.md
Labels: ✓ ready for review

#1113 Restructure documentation
  CONTRIBUTING.md
  MapboxCoreNavigation/Constants.swift
  README.md
  docs/cover.md
  docs/img/navigation.png
  scripts/document.sh
Labels: documentation, topic: documentation

#1111 Localize map labels
  CHANGELOG.md
  Examples/Swift/ViewController.swift
  MapboxNavigation/MGLVectorSource.swift
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/RouteMapViewController.swift
  languages.md
Labels: topic: localization

#1119 Update delegate method argument documentation
  MapboxCoreNavigation/RouteController.swift
  MapboxNavigation/NavigationMapView.swift
Labels: documentation, topic: documentation

#1121 Fix double voice
  MapboxCoreNavigation/RouteController.swift
Labels: ✓ ready for review

#1133 Update custom example
  Examples/Swift/Base.lproj/Main.storyboard
  Examples/Swift/CustomViewController.swift
Labels: ✓ ready for review

#1130 Fix next banner
  MapboxNavigation/NextBannerView.swift
Labels: ✓ ready for review

#1132 Rename MapboxSpeechController.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/MapboxVoiceController.swift
Labels: ✓ ready for review

#1022 Telemetry improvements
  MapboxCoreNavigation/MMEEventsManager.swift
  MapboxCoreNavigation/RouteController.swift
Labels: ✓ ready for review

#1124 Move to constants, make a public
  MapboxCoreNavigation/Dictionary.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Constants.swift
  MapboxNavigation/Dictionary.swift
  MapboxNavigation/NavigationMapView.swift
Labels: ✓ ready for review

#1141 Prevent statusView from being shown if it is already visible
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/StatusView.swift
Labels: ✓ ready for review

#1112 Convert language documentation into a guide
  README.md
  docs/guides/Localization and Internationalization.md
  docs/jazzy.yml
Labels: documentation, topic: documentation, topic: localization, topic: voice, ⚠️ DO NOT MERGE

#1152 Add more RouteController tests
  MapboxCoreNavigationTests/RouteControllerTests.swift
  MapboxNavigation.xcodeproj/project.pbxproj
Labels: ✓ ready for review

#1167 Making StepsViewController.init(routeProgress:) public
  CHANGELOG.md
  MapboxNavigation/StepsViewController.swift
Labels: - bug

#1164 Reformat language support table
  docs/guides/Localization and Internationalization.md
Labels: topic: documentation, topic: localization
