Repository mapbox/mapbox-navigation-ios, pull requests merged in 2018-04, with the labels that each got.

#1296 Add Sequence.swift to MapboxNavigation podspec
  MapboxNavigation.podspec
Labels: - build, CocoaPods

#1304 Derive MapboxDirections.swift version from Cartfile
  scripts/document.sh
Labels: - build, documentation

#1313 Update tests for MapboxDirections 0.20.0
  MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift
Labels: - build

#1309 Allow developers to populate the label below the puck
  CHANGELOG.md
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/RouteMapViewController.swift
Labels: - feature, ✓ ready for review

#1328 Updates semaphore timeout to a read-only computed property
  MapboxNavigationTests/XCTestCase.swift
Labels: - build, - chore, - tests, general: experimental

#1076 Update to Maps SDK for iOS v4.0.0
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Examples/Swift/CustomViewController.swift
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Constants.swift
  MapboxNavigation/Dictionary.swift
  MapboxNavigation/MGLVectorSource.swift
  MapboxNavigation/MGLVectorTileSource.swift
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/RouteMapViewController.swift
Labels: - chore, ✓ ready for review

#1336 v0.17.0-beta.1
  Examples/Objective-CTests/Info.plist
  Examples/SwiftTests/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  README.md
  RELEASE.md
  RouteTest/Info.plist
  custom-navigation.md
Labels: - build

#1310 Rewrite discarding delegate method documentation
  MapboxNavigation/NavigationViewController.swift
Labels: documentation
