Repository mapbox/mapbox-navigation-ios, pull requests merged in 2018-03, with the labels that each got.

#1176 More robust distance formatting
  CHANGELOG.md
  MapboxCoreNavigation/DistanceFormatter.swift
  MapboxCoreNavigationTests/DistanceFormatterTests.swift
  MapboxNavigation/InstructionsBannerView.swift
  MapboxNavigation/Style.swift
Labels: - bug, topic: instructions, topic: localization

#1175 Avoid mirroring lanes
  CHANGELOG.md
  MapboxNavigation/LanesView.swift
Labels: - bug, topic: instructions, topic: localization

#1183 Disable current road name if access token is omitted
  CHANGELOG.md
  MapboxNavigation/RouteMapViewController.swift
Labels: - crash

#1182 Mirror constraints for right-to-left layout
  CHANGELOG.md
  MapboxNavigation/BottomBannerViewLayout.swift
  MapboxNavigation/InstructionsBannerViewLayout.swift
  MapboxNavigation/LanesView.swift
  MapboxNavigation/NavigationViewLayout.swift
  MapboxNavigation/NextBannerView.swift
  MapboxNavigation/Resources/Assets.xcassets/feedback-closed-road.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback-gps.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback-map-error.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback-missing-road.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback-no-turn-allowed.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback-wrong-directions.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback_car_crash.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback_routing.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback_turn_not_allowed.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/overview.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/report_checkmark.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/volume_off.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/volume_up.imageset/Contents.json
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/StatusView.swift
  MapboxNavigation/StepsViewController.swift
  MapboxNavigation/Style.swift
  MapboxNavigation/UIView.swift
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testMultilinePrimary@2x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testMultilinePrimary@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testPrimaryShieldAndSecondary@2x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testPrimaryShieldAndSecondary@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testSinglelinePrimary@2x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testSinglelinePrimary@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testSinglelinePrimaryAndSecondary@2x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testSinglelinePrimaryAndSecondary@3x.png
Labels: - bug, topic: design, topic: localization

#1193 Avoid mirroring checkmark in right-to-left layout
  MapboxNavigation/Resources/Assets.xcassets/report_checkmark.imageset/Contents.json
Labels: - bug, topic: localization

#1208 Fixing puck position
  MapboxNavigation/RouteMapViewController.swift
Labels: - bug, wip

#1212 Making NavigationViewController.voiceController a lazy var
  MapboxCoreNavigation/SimulatedLocationManager.swift
  MapboxNavigation/NavigationViewController.swift
Labels: - refactor, topic: voice, ✓ ready for review

#1188 Improve RouteController location mechanism
  CHANGELOG.md
  MapboxCoreNavigation/CLLocation.swift
  MapboxCoreNavigation/Constants.swift
  MapboxCoreNavigation/MBRouteController.h
  MapboxCoreNavigation/MBRouteController.m
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigationTests/LocationTests.swift
  MapboxCoreNavigationTests/RouteControllerTests.swift
Labels: - refactor, topic: location, ✓ ready for review

#1127 Enable night style when inside tunnel
  CHANGELOG.md
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigation/RouteProgress.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/StyleManager.swift
Labels: ✓ ready for review

#1222 Force-Unwrap anchor crash fix
  Cartfile.resolved
  MapboxNavigation/RouteMapViewController.swift
Labels: - crash, Injection Work, quick fix, release blocker, ✓ ready for review

#1143 Use user's course to reroute sooner
  MapboxCoreNavigation/Constants.swift
  MapboxCoreNavigation/RouteController.swift
Labels: - refactor, general: experimental, ⚠️ DO NOT MERGE

#1229 Update localization instructions
  CONTRIBUTING.md
Labels: documentation, topic: localization

#1231 Directions Feedback tool is no more
  CONTRIBUTING.md
Labels: documentation

#1230 Reroute proactively, not opportunistically
  CHANGELOG.md
  MapboxCoreNavigation/Constants.swift
  MapboxCoreNavigation/MBRouteController.h
  MapboxCoreNavigation/MBRouteController.m
  MapboxCoreNavigation/RouteController.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/RouteVoiceController.swift
Labels: - refactor, topic: location

#1228 Insufficient contrast for severe congestion text in night theme.
  CHANGELOG.md
  MapboxNavigation/DayStyle.swift
Labels: quick fix, ✓ ready for review

#1232 Replace delimiter when showing adjacent shields
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/InstructionPresenter.swift
  MapboxNavigationTests/Constants.swift
  MapboxNavigationTests/Fixtures.xcassets/us-101.imageset/Contents.json
  MapboxNavigationTests/Fixtures.xcassets/us-101.imageset/us-101@3x.png
  MapboxNavigationTests/ImageCacheTests.swift
  MapboxNavigationTests/ImageDownloaderTests.swift
  MapboxNavigationTests/ImageRepositoryTests.swift
  MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift
  MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAdjacentShields@3x.png
Labels: ✓ ready for review

#1220 Code-based FeedbackViewController
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/DialogViewController.swift
  MapboxNavigation/FeedbackCollectionViewCell.swift
  MapboxNavigation/FeedbackViewController.swift
  MapboxNavigation/Resources/Base.lproj/Navigation.storyboard
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/UIStackView.swift
Labels: - chore, - refactor, pink, ✓ ready for review

#1244 Update changelog
  CHANGELOG.md
Labels: documentation

#1252 Add Arabic, European Portuguese localizations
  .tx/config
  CHANGELOG.md
  Examples/Objective-C/ar.lproj/Main.strings
  Examples/Objective-C/pt-PT.lproj/Main.strings
  Examples/Swift/ar.lproj/Main.strings
  Examples/Swift/pt-PT.lproj/Main.strings
  MapboxCoreNavigation/Resources/ar.lproj/Localizable.strings
  MapboxCoreNavigation/Resources/pt-PT.lproj/Localizable.strings
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Resources/ar.lproj/Navigation.strings
  MapboxNavigation/Resources/pt-PT.lproj/Localizable.strings
  MapboxNavigation/Resources/pt-PT.lproj/Localizable.stringsdict
  MapboxNavigation/Resources/pt-PT.lproj/Navigation.strings
  docs/guides/Localization and Internationalization.md
Labels: topic: localization

#1254 Clean up feedback view controller strings
  Examples/Swift/bg.lproj/Main.strings
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/DialogViewController.swift
  MapboxNavigation/FeedbackViewController.swift
  MapboxNavigation/Resources/Base.lproj/Localizable.strings
  MapboxNavigation/Resources/Base.lproj/Navigation.strings
  MapboxNavigation/Resources/ar.lproj/Localizable.strings
  MapboxNavigation/Resources/ar.lproj/Navigation.strings
  MapboxNavigation/Resources/bg.lproj/Localizable.strings
  MapboxNavigation/Resources/bg.lproj/Navigation.strings
  MapboxNavigation/Resources/ca.lproj/Localizable.strings
  MapboxNavigation/Resources/ca.lproj/Navigation.strings
  MapboxNavigation/Resources/da.lproj/Localizable.strings
  MapboxNavigation/Resources/da.lproj/Navigation.strings
  MapboxNavigation/Resources/de.lproj/Localizable.strings
  MapboxNavigation/Resources/de.lproj/Navigation.strings
  MapboxNavigation/Resources/es.lproj/Localizable.strings
  MapboxNavigation/Resources/es.lproj/Navigation.strings
  MapboxNavigation/Resources/fr.lproj/Localizable.strings
  MapboxNavigation/Resources/fr.lproj/Navigation.strings
  MapboxNavigation/Resources/he.lproj/Localizable.strings
  MapboxNavigation/Resources/he.lproj/Localizable.stringsdict
  MapboxNavigation/Resources/he.lproj/Navigation.strings
  MapboxNavigation/Resources/hu.lproj/Localizable.strings
  MapboxNavigation/Resources/nl.lproj/Localizable.strings
  MapboxNavigation/Resources/nl.lproj/Navigation.strings
  MapboxNavigation/Resources/pt-BR.lproj/Localizable.strings
  MapboxNavigation/Resources/pt-BR.lproj/Navigation.strings
  MapboxNavigation/Resources/pt-PT.lproj/Localizable.strings
  MapboxNavigation/Resources/pt-PT.lproj/Navigation.strings
  MapboxNavigation/Resources/ru.lproj/Localizable.strings
  MapboxNavigation/Resources/ru.lproj/Navigation.strings
  MapboxNavigation/Resources/sv.lproj/Localizable.strings
  MapboxNavigation/Resources/sv.lproj/Navigation.strings
  MapboxNavigation/Resources/uk.lproj/Localizable.strings
  MapboxNavigation/Resources/uk.lproj/Navigation.strings
  MapboxNavigation/Resources/vi.lproj/Localizable.strings
  MapboxNavigation/Resources/vi.lproj/Navigation.strings
Labels: - bug, topic: localization

#1253 Steps banner view enabled via a steps list indicator bar
  CHANGELOG.md
  Examples/Objective-C/Assets.xcassets/AppIcon.appiconset/Contents.json
  MapboxNavigation/DayStyle.swift
  MapboxNavigation/InstructionsBannerView.swift
  MapboxNavigation/InstructionsBannerViewLayout.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/StepsViewController.swift
  MapboxNavigation/Style.swift
  MapboxNavigation/UIView.swift
  MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAbbreviateInstructions@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAbbreviateInstructionsIncludingDelimiter@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAbbreviateWestFremontAvenue@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAdjacentShields@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testInstructionsAndNextInstructions@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testLongDistance@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testMultilinePrimary@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testPrimaryShieldAndSecondary@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testSinglelinePrimary@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testSinglelinePrimaryAndSecondary@3x.png
Labels: - feature, wip, ✓ ready for review

#1274 Fix syntax error in changelog
  CHANGELOG.md
Labels: documentation
