Repository mapbox/mapbox-navigation-ios, pull requests merged in 2018-10, with the labels that each got.

#1754 Safely convert UIViewAnimationCurve to UIViewAnimationOptions
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigationTests/UIViewAnimationOptionsTests.swift
Labels: - bug, - crash, 🤖 TDD

#1618 Navigation Native, Part 2
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Examples/Objective-C/ViewController.m
  Examples/Swift/ViewController.swift
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/CLLocation.swift
  MapboxCoreNavigation/EventDetails.swift
  MapboxCoreNavigation/EventsManager.swift
  MapboxCoreNavigation/Feedback.swift
  MapboxCoreNavigation/MBFixLocation.swift
  MapboxCoreNavigation/NavigationRouteOptions.swift
  MapboxCoreNavigation/NavigationService.swift
  MapboxCoreNavigation/PortableRouteController.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigation/Router.swift
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  MapboxCoreNavigationTests/NavigationServiceTests.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/All Tests.xcscheme
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/ExitView.swift
  MapboxNavigation/GenericRouteShield.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigationTests/CarPlayManagerTests.swift
  MapboxNavigationTests/LaneTests.swift
  MapboxNavigationTests/LeaksSpec.swift
  MapboxNavigationTests/MapboxNavigationTests-Bridging.h
  MapboxNavigationTests/MapboxVoiceControllerTests.swift
  MapboxNavigationTests/NavigationViewControllerTests.swift
  MapboxNavigationTests/StepsViewControllerTests.swift
  MapboxNavigationTests/Support/FBSnapshotTestCase.swift
  README.md
  docs/cover.md
  docs/jazzy.yml
Labels: release blocker, ⏎ Ready To Merge, ✓ ready for review

#1763 Adjustable GPS Patience
  CHANGELOG.md
  MapboxCoreNavigation/CountdownTimer.swift
  MapboxCoreNavigation/NavigationService.swift
  MapboxCoreNavigationTests/NavigationServiceTests.swift
Labels: - feature, quick fix, ✓ ready for review, 🤖 TDD

#1762 Add location fallback for CarPlay navigation style
  CHANGELOG.md
  MapboxNavigation/CarPlayNavigationViewController.swift
Labels: - bug, CarPlay

#1764 Release v0.22.1
  CHANGELOG.md
  Examples/Objective-CTests/Info.plist
  Examples/SwiftTests/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  RouteTest/Info.plist
Labels: - build

#1782 MapboxNavigationService over-retain fix.
  MapboxCoreNavigation/CountdownTimer.swift
  MapboxCoreNavigation/NavigationService.swift
  MapboxCoreNavigationTests/MapboxNavigationServiceSpec.swift
  MapboxNavigation.xcodeproj/project.pbxproj
Labels: - bug, High Priority, release blocker, ✓ ready for review, 🤖 TDD

#1792 Removing CarPlayManager shared instance
  CHANGELOG.md
  Cartfile.resolved
  Examples/Swift/AppDelegate+CarPlay.swift
  Examples/Swift/AppDelegate.swift
  Examples/Swift/FavoritesList.swift
  MapboxCoreNavigation.podspec
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation/CarPlayManager+Search.swift
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/VisualInstruction.swift
  MapboxNavigationTests/CarPlayManagerTests.swift
  docs/cover.md
Labels: ⏎ Ready To Merge, ✓ ready for review

#1799 Allow map view delegate to apply gradient to route line
  CHANGELOG.md
  MapboxNavigation/NavigationMapView.swift
Labels: topic: cartography

#1759 Remove dependency on debug build of MapboxDirections
  MapboxNavigationTests/Fixtures/Fixture.swift
  MapboxNavigationTests/RouteControllerSnapshotTests.swift
  MapboxNavigationTests/SimulatedLocationManagerTests.swift
Labels: - tests

#1601 Remove RouteMapViewController dependency on MGLMapViewDelegate
  CHANGELOG.md
  Examples/Swift/ViewController.swift
  MapboxNavigation/CarPlayMapViewController.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/NavigationView.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: - bug, - refactor
