Repository mapbox/mapbox-navigation-ios, pull requests merged in 2018-05, with the labels that each got.

#1343 Clarify language support table
  docs/guides/Localization and Internationalization.md
Labels: documentation, topic: documentation, topic: localization, topic: voice

#1365 Adjusting flaky test continuation criteria
  MapboxNavigationTests/ImageDownloaderTests.swift
  MapboxNavigationTests/ImageRepositoryTests.swift
Labels: - tests

#1338 Custom road name feature-level and integration tests
  CHANGELOG.md
  MapboxCoreNavigationTests/Support/DummyURLSessionDataTask.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: - tests, ✓ ready for review

#1380 Fixing issue where exit codes weren't being detected correctly.
  MapboxNavigation/InstructionPresenter.swift
Labels: - bug, UI, quick fix, topic: instructions, ✓ ready for review

#1218 Enable simulated navigation for tunnel segments.
  CHANGELOG.md
  MapboxCoreNavigation/CLLocation.swift
  MapboxCoreNavigation/Constants.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigation/RouteProgress.swift
  MapboxCoreNavigation/SimulatedLocationManager.swift
  MapboxCoreNavigation/TunnelIntersectionManager.swift
  MapboxCoreNavigationTests/TunnelIntersectionManagerTests.swift
  MapboxCoreNavigationTests/routeWithTunnels_9thStreetDC.json
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/NavigationViewController.swift
Labels: - feature, ✓ ready for review

#1397 Fixed user puck stuck while in simulation mode.
  MapboxCoreNavigation/SimulatedLocationManager.swift
Labels: - bug, ✓ ready for review

#1396 Use MD5 for creating cache keys
  CHANGELOG.md
  MapboxCoreNavigation/MBRouteController.h
  MapboxCoreNavigation/MBRouteController.m
  MapboxCoreNavigationTests/MD5Tests.swift
  MapboxCoreNavigationTests/md5_crazy_strings.txt
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation.xcodeproj/xcshareddata/xcbaselines/35B711CE1E5E7AD2001EDA8D.xcbaseline/51BD5556-46A3-4CC6-A414-4933647ED596.plist
  MapboxNavigation.xcodeproj/xcshareddata/xcbaselines/35B711CE1E5E7AD2001EDA8D.xcbaseline/Info.plist
  MapboxNavigation/Cache.swift
  MapboxNavigation/MapboxNavigation.h
  MapboxNavigationTests/DataCacheTests.swift
  MapboxNavigationTests/InstructionPresenterTests.swift
Labels: ✓ ready for review

#1404 Remove OS_ACTIVITY_MODE from Objective-C example scheme
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example-Objective-C.xcscheme
Labels: - build, Objective-C

#1378 Clean up NavigationMapViewDelegate method names
  CHANGELOG.md
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/RouteMapViewController.swift
Labels: - refactor, Objective-C

#1413 Clean up delegate method names; use UUIDs for feedback IDs
  CHANGELOG.md
  Examples/Swift/ViewController.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigation/TunnelIntersectionManager.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/RouteMapViewController.swift
  docs/examples/Advanced.md
  docs/examples/Custom Destination Marker.md
  docs/examples/Custom Server.md
  docs/examples/Embedded Navigation.md
  docs/examples/Waypoint Arrival Screen.md
Labels: - bug, - refactor, Objective-C

#1394 Stop building i386
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
Labels: - build, release blocker

#1410 RouteController - Retain Cycles & Zombie Refs
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigationTests/RouteControllerTests.swift
Labels: - bug, quick fix, topic: stability, ✓ ready for review, 🤖 TDD

#1406 Changes to adopt the named arrival instructions from Directions API
  Cartfile
  Cartfile.resolved
  Examples/Swift/ViewController.swift
  MapboxCoreNavigation.podspec
  MapboxCoreNavigationTests/BridgingTests.m
  MapboxNavigation-Documentation.podspec
  MapboxNavigation/ManeuverView.swift
  MapboxNavigation/StepsViewController.swift
Labels: ✓ ready for review

#1372 Allow for unlimited amount of alt routes
  CHANGELOG.md
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/RouteMapViewController.swift
Labels: ✓ ready for review

#1414 Remove tunnel intersection manager callback mechanism
  CHANGELOG.md
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigation/TunnelIntersectionManager.swift
  MapboxCoreNavigationTests/TunnelIntersectionManagerTests.swift
Labels: - bug, - refactor, topic: location

#1441 Add failing test for tunnel + style refreshes
  MapboxNavigation/StyleManager.swift
  MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: ✓ ready for review, 🤖 TDD

#1417 Adding generic shield support to instruction banner.
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/DayStyle.swift
  MapboxNavigation/ExitView.swift
  MapboxNavigation/GenericRouteShield.swift
  MapboxNavigation/InstructionPresenter.swift
  MapboxNavigation/VisualInstructionComponent.swift
  MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift
  MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift
  MapboxNavigationTests/LaneTests.swift
  MapboxNavigationTests/ManeuverViewTests.swift
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAbbreviateInstructionsIncludingDelimiter@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testGenericShields@3x.png
Labels: - feature, ⏎ Ready To Merge, ✓ ready for review

#1448 Updating destination waypoint when route changes
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigationTests/Fixtures/EmptyStyle.json
  MapboxNavigationTests/Fixtures/Fixture.swift
  MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: - bug, UI, ⏎ Ready To Merge, ✓ ready for review, 🤖 TDD

#1459 Exit View Padding
  MapboxNavigation/ExitView.swift
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testExitShields@3x.png
Labels: UI, quick fix, size: S, topic: instructions, ⏎ Ready To Merge, ✓ ready for review

#1454 Stop rerouting when arriving at waypoint
  CHANGELOG.md
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigationTests/RouteControllerTests.swift
  MapboxCoreNavigationTests/Support/RouteControllerDelegateSpy.swift
  MapboxNavigation/NavigationViewController.swift
Labels: - feature, ✓ ready for review

#1462 Update translations from Transifex
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Resources/Base.lproj/Localizable.strings
  MapboxNavigation/Resources/ar.lproj/Localizable.strings
  MapboxNavigation/Resources/da.lproj/Localizable.strings
  MapboxNavigation/Resources/de.lproj/Localizable.strings
  MapboxNavigation/Resources/de.lproj/Localizable.stringsdict
  MapboxNavigation/Resources/es.lproj/Localizable.strings
  MapboxNavigation/Resources/fr.lproj/Localizable.strings
  MapboxNavigation/Resources/he.lproj/Localizable.strings
  MapboxNavigation/Resources/ko.lproj/Localizable.strings
  MapboxNavigation/Resources/pt-PT.lproj/Localizable.strings
  MapboxNavigation/Resources/ru.lproj/Localizable.strings
  MapboxNavigation/Resources/sv.lproj/Localizable.strings
  MapboxNavigation/Resources/uk.lproj/Localizable.strings
  MapboxNavigation/Resources/vi.lproj/Localizable.strings
  MapboxNavigation/Resources/zh-Hans.lproj/Localizable.strings
Labels: topic: localization

#1461 Update RouteControllerTests to use locations instead of implementation details
  Cartfile.resolved
  MapboxCoreNavigationTests/RouteControllerTests.swift
Labels: - tests, ⏎ Ready To Merge, ✓ ready for review
