Repository mapbox/mapbox-navigation-ios, pull requests merged in 2018-11, with the labels that each got.

#1819 Reduce default minimum frame rate to 20 fps
  CHANGELOG.md
  MapboxNavigation/NavigationMapView.swift
Labels: - performance

#1828 Update Transifex configuration for example consolidation
  .tx/config
Labels: - build, topic: localization

#1833 Fix rerouting at arrival logic
  CHANGELOG.md
  MapboxCoreNavigation/RouteController.swift
Labels: - bug, topic: location

#1820 Location Manager Simulation
  CHANGELOG.md
  Cartfile.resolved
  MapboxCoreNavigation/DispatchTimer.swift
  MapboxCoreNavigation/NavigationService.swift
  MapboxCoreNavigation/SimulatedLocationManager.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigationTests/SimulatedLocationManagerTests.swift
Labels: - bug, size: S, topic: stability, ✓ ready for review

#1834 Customize Directions Client in CarPlayManager.
  CHANGELOG.md
  Cartfile.resolved
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayManagerDelegate.swift
  MapboxNavigationTests/CarPlayManagerTests.swift
Labels: - bug, - refactor, user: support, ✓ ready for review, 🤖 TDD

#1836 Allow style customization in CarPlay
  CHANGELOG.md
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayManagerDelegate.swift
  MapboxNavigation/CarPlayMapViewController.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/StyleManager.swift
  MapboxNavigationTests/CarPlayManagerTests.swift
  MapboxNavigationTests/StyleManagerTests.swift
  TestHelper/Fixture.swift
Labels: - build, - feature, - refactor, CarPlay, topic: cartography

#1841 Adding support for multi-leg routes in CarPlayManager.
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  MapboxNavigation/CarPlayManager+Search.swift
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigationTests/CarPlayManagerTests.swift
Labels: - refactor, CarPlay

#1845 Fix CarPlay navigation map vanishing point
  CHANGELOG.md
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/NavigationMapView.swift
Labels: - bug, CarPlay

#1854 Fix metric measurements in CarPlay
  CHANGELOG.md
  MapboxCoreNavigation/DistanceFormatter.swift
  MapboxCoreNavigationTests/DistanceFormatterTests.swift
Labels: - bug, CarPlay, topic: instructions, topic: localization

#1847 Adding willArrive functionality to RouteController/NavigationService.
  CHANGELOG.md
  MapboxCoreNavigation/NavigationService.swift
  MapboxCoreNavigation/NavigationServiceDelegate.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigation/RouterDelegate.swift
  MapboxCoreNavigationTests/NavigationServiceTests.swift
  MapboxNavigation/NavigationViewController.swift
  TestHelper/NavigationServiceTestDoubles.swift
Labels: - feature, release blocker, 🤖 TDD

#1852 Allow CarPlayManagerDelegate to customize user location annotation views
  CHANGELOG.md
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayMapViewController.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/UserCourseView.swift
Labels: - bug, CarPlay

#1850 v0.25.0
  Bench/Info.plist
  BenchTests/Info.plist
  BenchUITests/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  README.md
  TestHelper/Info.plist
  custom-navigation.md
Labels: - build

#1856 Balance safe area insets when initializing CarPlay navigation map view
  CHANGELOG.md
  MapboxNavigation/CarPlayNavigationViewController.swift
Labels: - bug, CarPlay

#1859 Calculate route to routable location in CarPlay
  CHANGELOG.md
  MapboxNavigation/CarPlayManager+Search.swift
Labels: - bug, CarPlay, topic: search

#1861 Round distances in CarPlay
  MapboxCoreNavigation/DistanceFormatter.swift
  MapboxCoreNavigationTests/DistanceFormatterTests.swift
Labels: - bug, CarPlay
