Repository mapbox/mapbox-navigation-ios, pull requests merged in 2018-12, with the labels that each got.

#1868 Downsize shields in instructions in CarPlay
  CHANGELOG.md
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/ImageDownload.swift
  MapboxNavigation/NSAttributedString.swift
Labels: - bug, CarPlay, topic: instructions

#1880 Update documentation documentation
  MapboxNavigation/StepsViewController.swift
  README.md
  RELEASE.md
  docs/README.md
  scripts/document.sh
Labels: - build, - refactor, documentation, topic: documentation

#1882 Make NavigationSettings.shared accessible in Objective-C
  CHANGELOG.md
  MapboxCoreNavigation/NavigationSettings.swift
Labels: - bug, Objective-C

#1884 Incrementing navigator index for multi-leg routes.
  CHANGELOG.md
  MapboxCoreNavigation/PortableRouteController.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigation/Router.swift
Labels: - bug

#1883 Multi-leg nearby coordinate lookups.
  CHANGELOG.md
  MapboxCoreNavigation/CLLocation.swift
  MapboxCoreNavigation/EventDetails.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigation/RouteProgress.swift
  MapboxCoreNavigationTests/LocationTests.swift
  MapboxCoreNavigationTests/NavigationServiceTests.swift
  MapboxCoreNavigationTests/RouteProgressTests.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/RouteVoiceController.swift
  MapboxNavigationTests/NavigationViewControllerTests.swift
  MapboxNavigationTests/StepsViewControllerTests.swift
Labels: - bug, release blocker, ✓ ready for review

#1888 Fix infinite recursion when failing to download shield image
  CHANGELOG.md
  MapboxNavigation/InstructionPresenter.swift
Labels: - crash, topic: instructions, topic: stability

#1898 Fixing Maneuver Arrows around waypoints
  Example/ViewController.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/Route.swift
  MapboxNavigationTests/Fixtures/waypoint-after-turn.json
  MapboxNavigationTests/ManeuverArrowTests.swift
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverArrowTests/testManeuverArrowHandlesWaypointsCorrectly@3x.png
Labels: - bug

#1905 Moving navigation service stop into deinit method.
  MapboxNavigation/NavigationViewController.swift
Labels: - bug, quick fix, topic: stability

#1909 Upgrade to Mapbox Streets source v8
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/MGLVectorTileSource.swift
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigationTests/MGLVectorTileSourceTests.swift
Labels: - performance, topic: cartography, topic: localization
