Repository mapbox/mapbox-navigation-ios, pull requests merged in 2018-07, with the labels that each got.

#1549 Deredeclare CLLocationManagerDelegate conformance on MGLMapView
  Examples/Swift/Example-Swift-BridgingHeader.h
  Examples/Swift/MGLMapView+CustomAdditions.h
  Examples/Swift/MGLMapView+CustomAdditions.m
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/MGLMapView+MGLNavigationAdditions.h
  docs/guides/Simulating Routes.md
  docs/img/simulator-location.png
Labels: - refactor, topic: location

#1551 Core Navigation no longer supports iOS 8
  README.md
  docs/cover.md
Labels: documentation

#1552 Eviscerate jazzy guides
  .github/ISSUE_TEMPLATE.md
  CHANGELOG.md
  CONTRIBUTING.md
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  README.md
  docs/cover.md
  docs/examples/Advanced.md
  docs/examples/Basic.md
  docs/examples/Custom Destination Marker.md
  docs/examples/Custom Server.md
  docs/examples/Custom Voice Controller.md
  docs/examples/Embedded Navigation.md
  docs/examples/Styled UI Elements.md
  docs/examples/Waypoint Arrival Screen.md
  docs/guides/Localization and Internationalization.md
  docs/guides/Simulating Routes.md
  docs/guides/Storyboards.md
  docs/img/setup_ib.png
  docs/img/simulator-location.png
  docs/jazzy.yml
  scripts/document.sh
  scripts/update-guides.sh
Labels: - refactor, documentation

#1514 Integrated new directions API fields with the tertiary instruction and lane indications
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Examples/Swift/CustomViewController.swift
  MapboxCoreNavigation.podspec
  MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  MapboxCoreNavigationTests/RouteControllerTests.swift
  MapboxCoreNavigationTests/TunnelIntersectionManagerTests.swift
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/ExitView.swift
  MapboxNavigation/GenericRouteShield.swift
  MapboxNavigation/InstructionPresenter.swift
  MapboxNavigation/InstructionsBannerView.swift
  MapboxNavigation/LaneView.swift
  MapboxNavigation/LanesView.swift
  MapboxNavigation/ManeuverView.swift
  MapboxNavigation/NextBannerView.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/StepsViewController.swift
  MapboxNavigation/VisualInstruction.swift
  MapboxNavigationTests/Fixtures/Fixture.swift
  MapboxNavigationTests/Fixtures/route-for-lane-testing.json
  MapboxNavigationTests/InstructionPresenterTests.swift
  MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift
  MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift
  MapboxNavigationTests/LaneTests.swift
  MapboxNavigationTests/LeaksSpec.swift
  MapboxNavigationTests/ManeuverViewTests.swift
  MapboxNavigationTests/NavigationViewControllerTests.swift
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.LaneTests/testStraightRight_iPhone11_4_414x736@3x.png
  MapboxNavigationTests/StepsViewControllerTests.swift
Labels: ✓ ready for review

#1568 Ensure build phase inserts access token
  MapboxNavigation.xcodeproj/project.pbxproj
Labels: - build

#1558 Map labels are no longer blank and using China Map Style URLs if the application is configured to use Mapbox China APIs
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/MGLAccountManager.swift
  MapboxNavigation/MGLStyle.swift
  MapboxNavigation/NavigationMapView.swift
Labels: topic: localization

#1575 Basic Example EORVC Restoration.
  Cartfile.resolved
  Examples/Swift/ViewController.swift
Labels: - bug, quick fix, release blocker, ⏎ Ready To Merge, ✓ ready for review

#1581 Immediate End Of Route Events
  MapboxCoreNavigation/EndOfRouteFeedback.swift
  MapboxCoreNavigation/EventsManager.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigation/Router.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/RouteMapViewController.swift
Labels: - bug, quick fix, topic: telemetry
