Repository mapbox/mapbox-navigation-ios, pull requests merged in 2019-09, with the labels that each got.

#2224 Adding method for progress updates on the NVC delegate.
  CHANGELOG.md
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/NavigationViewControllerDelegate.swift
Labels: - feature, user: feature request

#2182 Full-screen modal presentation bugfix
  CHANGELOG.md
  Example/ViewController.swift
  MapboxNavigation/BottomBannerViewController.swift
  MapboxNavigation/BottomBannerViewLayout.swift
  MapboxNavigation/Style.swift
  README.md
  docs/guides/Reduce Memory Usage.md
Labels: - bug, UI, ✓ ready for review

#2226 v0.37.0
  Bench/Info.plist
  BenchTests/Info.plist
  BenchUITests/Info.plist
  CHANGELOG.md
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  README.md
  TestHelper/Info.plist
  custom-navigation.md
Labels: - build

#2239 Update suggested usage description
  README.md
  docs/cover.md
Labels: documentation, topic: documentation
