Repository mapbox/mapbox-navigation-ios, pull requests merged in 2019-03, with the labels that each got.

#1982 Added safe-area handling to BottomBannerViewController.
  CHANGELOG.md
  Cartfile.private
  Cartfile.resolved
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/BottomBannerViewController.swift
  MapboxNavigation/BottomBannerViewLayout.swift
  MapboxNavigation/Style.swift
  MapboxNavigationTests/BottomBannerSnapshotTests.swift
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.BottomBannerSnapshotTests/testBottomBannerViewControllerNoSafeArea_iPhone_8_Portrait_iOS_11.4@2x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.BottomBannerSnapshotTests/testBottomBannerViewController_iPhone_X_Portrait_iOS_12.1@3x.png
Labels: - bug, UI, quick fix, user: feedback

#2005 Carplay Arrival UI - Removal
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigationTests/CarPlayNavigationViewControllerTests.swift
Labels: CarPlay, UI

#2018 CarPlay Fixes (Short-term)
  BenchTests/BenchTests.swift
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  Example/CustomViewController.swift
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayManagerDelegate.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/MapboxVoiceController.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/RouteVoiceController.swift
  MapboxNavigationTests/CarPlayManagerTests.swift
  MapboxNavigationTests/CarPlayNavigationViewControllerTests.swift
  MapboxNavigationTests/LeaksSpec.swift
  MapboxNavigationTests/MapboxVoiceControllerTests.swift
  MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: - bug, - refactor, CarPlay, UI, backwards-incompatible, quick fix

#2021 CarPlay Continuity
  BenchTests/BenchTests.swift
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  Example/ViewController.swift
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayManagerDelegate.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigationTests/CarPlayManagerTests.swift
Labels: - bug, - refactor, CarPlay, UI, quick fix

#2024 End CarPlay when Phone Cancels Nav
  Example/ViewController.swift
Labels: - bug, quick fix

#2026 Carplay Natural End Navigation
  Example/ViewController.swift
  MapboxNavigation/NavigationViewController.swift
Labels: - bug, quick fix

#2025 Correct Signature Obsoletion for CarPlay
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigationTests/CarPlayManagerTests.swift
Labels: documentation, quick fix

#2014 Preserve via points after rerouting
  CHANGELOG.md
  MapboxCoreNavigation/RouteLeg.swift
  MapboxCoreNavigation/RouteOptions.swift
  MapboxCoreNavigation/RouteProgress.swift
  MapboxCoreNavigationTests/RouteProgressTests.swift
  MapboxNavigation.xcodeproj/project.pbxproj
Labels: - bug, topic: location

#2004 Safely unwrap spoken instruction
  MapboxCoreNavigation/RouteController.swift
Labels: - crash

#2027 Deprecate BottomBannerViewController(delegate:)
  CHANGELOG.md
  MapboxNavigation/BottomBannerViewController.swift
  MapboxNavigation/NavigationViewController.swift
Labels: - refactor, topic: architecture

#2031 Update localizations from Transifex
  MapboxCoreNavigation/Resources/de.lproj/Localizable.strings
  MapboxCoreNavigation/Resources/fr.lproj/Localizable.strings
  MapboxCoreNavigation/Resources/vi.lproj/Localizable.strings
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Resources/de.lproj/Localizable.strings
  MapboxNavigation/Resources/fr.lproj/Localizable.strings
  MapboxNavigation/Resources/hu.lproj/Localizable.stringsdict
  MapboxNavigation/Resources/sv.lproj/Localizable.strings
Labels: topic: localization

#2032 Add Japanese localization
  CHANGELOG.md
  Example/ja.lproj/Main.strings
  MapboxCoreNavigation/Resources/ja.lproj/Localizable.strings
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Resources/ja.lproj/Localizable.strings
  MapboxNavigation/Resources/ja.lproj/Localizable.stringsdict
  MapboxNavigation/Resources/ja.lproj/Navigation.strings
Labels: topic: localization

#2039 Fix Interface Builder designable compilation error
  CHANGELOG.md
  MapboxNavigation/LaneView.swift
Labels: - build, topic: design

#2033 Fix multi-waypoint selection in example application
  Example/ViewController.swift
Labels: - bug

#2041 Car Play Quick Fixes: Data Race Bug
  CHANGELOG.md
  Example/ViewController.swift
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigationTests/CarPlayManagerTests.swift
Labels: - bug, CarPlay, quick fix

#2043 Assert that obsoleted delegate method is not implemented
  MapboxNavigation/CarPlayNavigationViewController.swift
Labels: - bug, CarPlay

#2044 Ending Carplay on Arrival
  Example/ViewController.swift
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigationTests/CarPlayManagerTests.swift
Labels: - bug, quick fix

#2045 CarPlay-initiated navigation delegate fix
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  Example/AppDelegate.swift
  Example/ViewController.swift
  MapboxNavigation/NavigationViewController+Obsolete.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/UIViewController.swift
Labels: - bug, CarPlay, quick fix

#2051 Always hide compass on CarPlay during navigation
  CHANGELOG.md
  MapboxNavigation/CarPlayNavigationViewController.swift
Labels: - bug, CarPlay, topic: design

#2052 Remove unused list template code from CarPlayManager
  Example/AppDelegate+CarPlay.swift
  MapboxNavigation/CarPlayManager.swift
Labels: - refactor, CarPlay

#2053 CarPlay crash when starting from phone
  Example/ViewController.swift
Labels: - crash, CarPlay, quick fix

#2054 Carthage update.
  Cartfile.resolved
Labels: - build, quick fix

#2055 Releasing 0.30.0
  Bench/Info.plist
  BenchTests/Info.plist
  BenchUITests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  README.md
  TestHelper/Info.plist
Labels: - build, documentation

#2058 Upgrade to Swift 4.2
  CHANGELOG.md
  Example/AppDelegate.swift
  Example/CustomViewController.swift
  Example/ResizableView.swift
  Example/SettingsViewController.swift
  Example/ViewController.swift
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/DistanceFormatter.swift
  MapboxCoreNavigation/EventDetails.swift
  MapboxCoreNavigation/NavigationEventsManager.swift
  MapboxCoreNavigation/NavigationService.swift
  MapboxCoreNavigation/ScreenCapture.swift
  MapboxCoreNavigation/SessionState.swift
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/xcshareddata/xcschemes/PodInstall.xcscheme
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall/AppDelegate.swift
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/DistanceFormatterTests.swift
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/BottomBannerViewController.swift
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/DataCache.swift
  MapboxNavigation/ImageCache.swift
  MapboxNavigation/InstructionPresenter.swift
  MapboxNavigation/InstructionsBannerView.swift
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/RouteVoiceController.swift
  MapboxNavigation/StatusView.swift
  MapboxNavigation/StepsViewController.swift
  MapboxNavigation/Style.swift
  MapboxNavigation/StyleManager.swift
  MapboxNavigation/UIImage.swift
  MapboxNavigation/UIStackView.swift
  MapboxNavigationTests/BottomBannerSnapshotTests.swift
  MapboxNavigationTests/DataCacheTests.swift
  MapboxNavigationTests/ImageCacheTests.swift
  MapboxNavigationTests/ImageDownloaderTests.swift
  MapboxNavigationTests/ImageRepositoryTests.swift
  MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift
  MapboxNavigationTests/Support/ImageLoadingURLProtocolSpy.swift
  MapboxNavigationTests/UIViewAnimationOptionsTests.swift
  README.md
Labels: - build
