Repository mapbox/mapbox-navigation-ios, pull requests merged in 2019-07, with the labels that each got.

#2075 Navigation start on presentation
  MapboxNavigation/NavigationViewController.swift
Labels: - refactor, quick fix

#2177 MapboxMobileEvents v0.9.5
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation-Documentation.podspec
Labels: - build

#2178 Fixing broken UIAppearance on InstructionsBannerView
  CHANGELOG.md
  MapboxNavigation/InstructionsBannerViewLayout.swift
  MapboxNavigation/TopBannerViewController.swift
Labels: - bug, UI, release blocker, user: support

#2179 Can certain conditional CarPlay compilation
  CHANGELOG.md
  MapboxCoreNavigation/RouteProgress.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/Style.swift
Labels: - crash, CarPlay, CocoaPods

#2181 Update Jazzy theme
  docs/jazzy.yml
  scripts/document.sh
Labels: documentation

#2183 Fix auto-hiding status view
  CHANGELOG.md
  MapboxNavigation/StatusView.swift
Labels: - bug

#2188 Exclude Twitter reachability test from CocoaPods installation test
  .circleci/config.yml
Labels: - build, CocoaPods

#2192 Add completion handlers to camera change operations
  Cartfile.resolved
  Example/OfflineViewController.swift
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayMapViewController.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/RouteMapViewController.swift
Labels: - build

#2185 Fixing issue where steps controller grows from .zero when presented
  CHANGELOG.md
  MapboxNavigation/TopBannerViewController.swift
Labels: - bug, UI

#2068 Document various Core Navigation classes
  MapboxCoreNavigation/NavigationService.swift
  MapboxCoreNavigation/NavigationServiceDelegate.swift
  MapboxCoreNavigation/NavigationSettings.swift
  MapboxCoreNavigation/Router.swift
  MapboxCoreNavigation/RouterDelegate.swift
  MapboxNavigation/MapboxVoiceController.swift
  MapboxNavigation/NavigationOptions.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/NavigationViewControllerDelegate.swift
  MapboxNavigation/RouteVoiceController.swift
Labels: documentation, topic: documentation

#2193 Add common attributes to congestionless route polylines
  CHANGELOG.md
  MapboxNavigation/NavigationMapView.swift
Labels: - bug
