Repository mapbox/mapbox-navigation-ios, pull requests merged in 2019-12, with the labels that each got.

#2283 Lighten maneuver icons in user notifications in Dark Mode
  CHANGELOG.md
  MapboxNavigation/NavigationViewController.swift
Labels: - bug, topic: design, topic: instructions

#2288 Use built-in ISO date formatter
  MapboxCoreNavigation/Date.swift
Labels: - refactor, quick fix

#2114 Add speed limit data returned by MapboxDirections.swift to the RouteProgress object
  CHANGELOG.md
  Cartfile.resolved
  MapboxCoreNavigation/NavigationRouteOptions.swift
  MapboxCoreNavigation/RouteProgress.swift
  MapboxCoreNavigationTests/OptionsTests.swift
  MapboxCoreNavigationTests/RouteProgressTests.swift
Labels: - feature, topic: traffic

#2290 Clean up RouteController user info keys
  Example/CustomViewController.swift
  MapboxCoreNavigation/CoreConstants.swift
  MapboxCoreNavigation/LegacyRouteController.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigation/Router.swift
  MapboxCoreNavigation/SimulatedLocationManager.swift
  MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  MapboxCoreNavigationTests/NavigationServiceTests.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/MapboxVoiceController.swift
  MapboxNavigation/RouteVoiceController.swift
  MapboxNavigation/Style.swift
  MapboxNavigationTests/CarPlayNavigationViewControllerTests.swift
  MapboxNavigationTests/MapboxVoiceControllerTests.swift
Labels: documentation, topic: documentation
