Repository mapbox/mapbox-navigation-ios, pull requests merged in 2019-01, with the labels that each got.

#1846 Separate search component from the main carplay manager.
  CHANGELOG.md
  Cartfile.resolved
  Example/AppDelegate+CarPlay.swift
  Example/AppDelegate.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayManagerDelegate.swift
  MapboxNavigation/CarPlaySearchController+ CPSearchTemplateDelegate.swift
  MapboxNavigation/CarPlaySearchController.swift
  MapboxNavigationTests/CarPlayManagerTests.swift
Labels: - refactor, CarPlay, ✓ ready for review

#1928 Location Simulator Reroute Report
  Cartfile.resolved
  MapboxCoreNavigation/NavigationService.swift
  MapboxCoreNavigation/SimulatedLocationManager.swift
  MapboxCoreNavigationTests/NavigationServiceTests.swift
Labels: - bug, ✓ ready for review, 🤖 TDD

#1930 Silence reroute questioning if reroute is already inflight
  MapboxCoreNavigation/RouteController.swift
Labels: - performance, quick fix, size: S, ✓ ready for review

#1931 Silence `willReroute` when changing route via property.
  MapboxCoreNavigation/RouteController.swift
Labels: - performance, - refactor, quick fix, size: S, ✓ ready for review

#1932 Publicly exposing the EORVC presentation in the NVC
  MapboxNavigation/NavigationViewController.swift
Labels: - refactor, UI, quick fix, user: feature request, ✓ ready for review

#1933 Updated configuration in audio ducking for CarPlay.
  CHANGELOG.md
  MapboxNavigation/RouteVoiceController.swift
Labels: - bug, CarPlay

#1952 Fix file name conflict in documentation pod
  CHANGELOG.md
  MapboxCoreNavigation/CoreConstants.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/CarPlaySearchController+ CPSearchTemplateDelegate.swift
  MapboxNavigation/Locale.swift
Labels: - build, - refactor, CocoaPods, documentation

#1904 Migrate to nav-native’s route following
  BenchTests/BenchTests.swift
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/CLLocation.swift
  MapboxCoreNavigation/LegacyRouteController.swift
  MapboxCoreNavigation/MBFixLocation.swift
  MapboxCoreNavigation/MBNavigator.swift
  MapboxCoreNavigation/NavigationService.swift
  MapboxCoreNavigation/PortableRouteController.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigation/Router.swift
  MapboxCoreNavigationTests/BridgingTests.m
  MapboxCoreNavigationTests/CLLocationTests.swift
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  MapboxCoreNavigationTests/NavigationServiceTests.swift
  MapboxCoreNavigationTests/RouteProgressTests.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/BottomBannerView.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigationTests/Fixtures/route-with-instructions.json
  MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift
  MapboxNavigationTests/ManeuverViewTests.swift
  MapboxNavigationTests/NavigationViewControllerTests.swift
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testExitShields_iPhone_11_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testArriveNone_iPhone_11_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testArriveNone_iPhone_12_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testArrive_iPhone_11_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testArrive_iPhone_12_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.RouteControllerSnapshotTests/testRouteSnappingOvershooting_iPhone_11_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.RouteControllerSnapshotTests/testRouteSnappingOvershooting_iPhone_12_1@3x.png
  MapboxNavigationTests/RouteControllerSnapshotTests.swift
  TestHelper/Date.swift
  TestHelper/DummyLocationManager.swift
  TestHelper/routeWithInstructions.json
Labels: platform parity

#1912 Customizable Bottom Banner - Prep
  CHANGELOG.md
  Cartfile.resolved
  MapboxCoreNavigation/DispatchTimer.swift
  MapboxCoreNavigation/MBRouteController.h
  MapboxCoreNavigation/MBRouteController.m
  MapboxCoreNavigation/NavigationService.swift
  MapboxCoreNavigation/NavigationServiceDelegate.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigation/RouteProgress.swift
  MapboxCoreNavigation/RouterDelegate.swift
  MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/BottomBannerView.swift
  MapboxNavigation/InstructionsBannerView.swift
  MapboxNavigation/LanesView.swift
  MapboxNavigation/MapboxVoiceController.swift
  MapboxNavigation/NavigationComponent.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/NextBannerView.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigationTests/Support/FBSnapshotTestCase.swift
Labels: - feature, - refactor, High Priority, UI, size: M, topic: architecture, user: feature request, wip, ⏎ Ready To Merge, ✓ ready for review
