Repository mapbox/mapbox-navigation-ios, pull requests merged in 2019-06, with the labels that each got.

#2143 Depend on map SDK v5.0.x specifically
  Cartfile
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
Labels: - build

#2144 v0.34.0
  Bench/Info.plist
  BenchTests/Info.plist
  BenchUITests/Info.plist
  CHANGELOG.md
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  README.md
  TestHelper/Info.plist
  custom-navigation.md
Labels: - build

#2121 Top Banner Customization: Second Attempt
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  Example/CustomViewController.swift
  Example/ViewController.swift
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/BottomBannerViewLayout.swift
  MapboxNavigation/DayStyle.swift
  MapboxNavigation/ExitView.swift
  MapboxNavigation/FeedbackViewController.swift
  MapboxNavigation/LanesView.swift
  MapboxNavigation/NavigationComponent.swift
  MapboxNavigation/NavigationOptions.swift
  MapboxNavigation/NavigationView.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/NavigationViewLayout.swift
  MapboxNavigation/NextBannerView.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/StatusView.swift
  MapboxNavigation/StepsViewController.swift
  MapboxNavigation/Style.swift
  MapboxNavigation/StyleManager.swift
  MapboxNavigation/TopBannerViewController.swift
  MapboxNavigation/UIView.swift
  MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: - feature, - refactor, UI, size: L, user: feature request

#2156 Fix crash presenting NavigationViewController on iOS 13
  CHANGELOG.md
  MapboxCoreNavigation/NavigationSettings.swift
Labels: - crash

#2160 Bumped map-sdk version to 5.1
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
Labels: - build

#2134 Remove viewport workaround in CarPlay
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/NavigationEventsManagerTests.swift
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/NavigationMapView.swift
  TestHelper/MMEEventsManager+Spy.h
  TestHelper/MMEEventsManager+Spy.m
  TestHelper/NavigationEventsManagerTestDoubles.swift
  TestHelper/TestHelper.h
Labels: - performance, CarPlay

#2164 v0.35.0
  Bench/Info.plist
  BenchTests/Info.plist
  BenchUITests/Info.plist
  CHANGELOG.md
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  README.md
  TestHelper/Info.plist
  custom-navigation.md
Labels: - build
