Repository mapbox/mapbox-navigation-ios, pull requests merged in 2019-10, with the labels that each got.

#2206 Require iOS 10.0
  .circleci/config.yml
  CHANGELOG.md
  Example/ViewController.swift
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/DistanceFormatter.swift
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/DistanceFormatterTests.swift
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/BottomBannerViewController.swift
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/InstructionsBannerView.swift
  MapboxNavigation/NSAttributedString.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/RouteVoiceController.swift
  MapboxNavigation/VisualInstruction.swift
  MapboxNavigationTests/CarPlayManagerTests.swift
  MapboxNavigationTests/CarPlayNavigationViewControllerTests.swift
  MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.BottomBannerSnapshotTests/testBottomBannerViewController_iPhone_X_Portrait_iOS_13.1@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testLanesManeuver_iPhone6Plus_Portrait_iOS_13.1@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testRegularManeuver_iPhone6Plus_Portrait_iOS_13.1@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testTertiaryManeuver_iPhone6Plus_Portrait_iOS_13.1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.CarPlayCompassViewTests/testEN@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.CarPlayCompassViewTests/testHE@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAbbreviateInstructionsIncludingDelimiter_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAbbreviateInstructions_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAbbreviateWestFremontAvenue_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAdjacentShields_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testExitShields_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testGenericShields_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testInstructionsAndNextInstructions_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testLongDistance_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testMultilinePrimary_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testPrimaryShieldAndSecondary_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testSinglelinePrimaryAndSecondary_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testSinglelinePrimary_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testSweEngLongDistance_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testUkrainianLongDistance_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.LaneTests/testAllLanes30x30_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.LaneTests/testAllLanes90x90_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverArrowTests/testManeuverArrowHandlesWaypointsCorrectly@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testArriveNone_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testArrive_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testLeftUTurn_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testMergeRight_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testRightUTurn_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testRoundaboutTurnLeft_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testRoundabout_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testStraightRoundabout_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testTurnRight_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testTurnSlightRight_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.RouteControllerSnapshotTests/testRouteSnappingOvershooting_iPhone_13_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.SimulatedLocationManagerTests/testSimulateRouteDoublesBack_iPhone_13_1@3x.png
  README.md
Labels: - build, - refactor, CocoaPods, backwards-incompatible, topic: localization

#2232 Migrate to Swift 5
  .circleci/config.yml
  Example/CustomViewController.swift
  Example/SettingsItems.swift
  Example/ViewController+GuidanceCards.swift
  Example/ViewController.swift
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/EventDetails.swift
  MapboxCoreNavigation/LegacyRouteController.swift
  MapboxCoreNavigation/MBNavigator.swift
  MapboxCoreNavigation/NavigationEventsManager.swift
  MapboxCoreNavigation/RouteProgress.swift
  MapboxCoreNavigation/SimulatedLocationManager.swift
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/DistanceFormatterTests.swift
  MapboxCoreNavigationTests/RouteProgressTests.swift
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/InstructionPresenter.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/RatingControl.swift
  MapboxNavigation/RecentItem.swift
  MapboxNavigation/StatusView.swift
  MapboxNavigation/Style.swift
  MapboxNavigation/TopBannerViewController.swift
  MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift
  MapboxNavigationTests/LaneTests.swift
  MapboxNavigationTests/NavigationViewControllerTests.swift
  README.md
  TestHelper/NavigationEventsManagerTestDoubles.swift
Labels: - refactor

#2211 Simplify anchor point calculation and puck centering
  CHANGELOG.md
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayMapViewController.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/RouteMapViewController.swift
Labels: topic: camera

#2249 v0.38.0
  Bench/Info.plist
  BenchTests/Info.plist
  BenchUITests/Info.plist
  CHANGELOG.md
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  README.md
  TestHelper/Info.plist
  custom-navigation.md
Labels: - build
