Repository mapbox/mapbox-navigation-ios, pull requests merged in 2019-08, with the labels that each got.

#2197 Top Banner Swipe Gesture Fix
  CHANGELOG.md
  MapboxNavigation/NavigationViewController.swift
Labels: - bug, quick fix

#2200 Include docset title and version in masthead
  docs/theme/templates/header.mustache
  scripts/document.sh
Labels: - bug, documentation, topic: documentation

#2208 Require map SDK v5.2.x
  Cartfile
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
Labels: - build

#2220 Fix CarPlay example build
  Example/ViewController+GuidanceCards.swift
  MapboxNavigation.xcodeproj/project.pbxproj
Labels: - build, CarPlay

#2221 Determine user agent based on presence of MapboxNavigation
  MapboxCoreNavigation/NavigationEventsManager.swift
  MapboxCoreNavigation/NavigationService.swift
  MapboxCoreNavigationTests/NavigationServiceTests.swift
  MapboxNavigation/NavigationViewController.swift
Labels: - bug, - refactor, Regression, topic: telemetry

#2214 Reword low volume warning to be less passive
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/Resources/Base.lproj/Localizable.strings
  MapboxNavigation/Resources/da.lproj/Localizable.strings
  MapboxNavigation/Resources/de.lproj/Localizable.strings
  MapboxNavigation/Resources/es.lproj/Localizable.strings
  MapboxNavigation/Resources/fr.lproj/Localizable.strings
  MapboxNavigation/Resources/he.lproj/Localizable.strings
  MapboxNavigation/Resources/hu.lproj/Localizable.strings
  MapboxNavigation/Resources/ja.lproj/Localizable.strings
  MapboxNavigation/Resources/pt-PT.lproj/Localizable.strings
  MapboxNavigation/Resources/ru.lproj/Localizable.strings
  MapboxNavigation/Resources/sv.lproj/Localizable.strings
  MapboxNavigation/Resources/uk.lproj/Localizable.strings
  MapboxNavigation/Resources/vi.lproj/Localizable.strings
  MapboxNavigation/Resources/yo.lproj/Localizable.strings
  MapboxNavigation/Resources/zh-Hans.lproj/Localizable.strings
Labels: topic: instructions
