Repository mapbox/mapbox-navigation-ios, pull requests merged in 2019-02, with the labels that each got.

#1953 Update URLs
  CHANGELOG.md
  CONTRIBUTING.md
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/LegacyRouteController.swift
  MapboxCoreNavigation/NavigationRouteOptions.swift
  MapboxCoreNavigation/NavigationService.swift
  MapboxCoreNavigation/OfflineDirections.swift
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation/MGLMapView.swift
  MapboxNavigation/NavigationMapView.swift
  README.md
  docs/cover.md
  docs/jazzy.yml
  scripts/document.sh
Labels: - chore, documentation

#1915 Update MapboxVoiceController.swift
  MapboxNavigation/MapboxVoiceController.swift
Labels: topic: voice

#1959 Correct Local Variable Typo
  MapboxNavigation/RouteMapViewController.swift
Labels: - refactor

#1951 Bottom Banner Containerization
  Example/MBViewController.m
  Example/ViewController.swift
  MapboxCoreNavigation/LegacyRouteController.swift
  MapboxCoreNavigation/NavigationRouteOptions.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/BottomBannerViewController.swift
  MapboxNavigation/BottomBannerViewLayout.swift
  MapboxNavigation/DayStyle.swift
  MapboxNavigation/NavigationComponent.swift
  MapboxNavigation/NavigationCustomizable.swift
  MapboxNavigation/NavigationOptions.swift
  MapboxNavigation/NavigationView.swift
  MapboxNavigation/NavigationViewController+Obsolete.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/NavigationViewControllerDelegate.swift
  MapboxNavigation/NavigationViewLayout.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/Style.swift
  MapboxNavigation/UIView.swift
  MapboxNavigationTests/LeaksSpec.swift
  MapboxNavigationTests/MapboxVoiceControllerTests.swift
  MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: - feature, - refactor, UI, ongoing, size: L, topic: architecture, user: feature request, wip, ✓ ready for review

#1965 Locking down the navigationService after initialization.
  CHANGELOG.md
  MapboxNavigation/NavigationViewController.swift
Labels: quick fix, ✓ ready for review

#1964 Obsolete NavigationMapViewDelegate methods
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/NavigationMapViewDelegate.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/NavigationViewControllerDelegate.swift
  MapboxNavigation/RouteMapViewController.swift
Labels: backwards-incompatible, quick fix, ✓ ready for review

#1967 Fix compiler warning about deprecated delegate method
  MapboxNavigation/InstructionsBannerView.swift
Labels: - build

#1962 [CarPlay] Adds custom map buttons delegate for activity navigating.
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  Example/Assets.xcassets/carplay/Contents.json
  Example/Assets.xcassets/carplay/carplay_feedback.imageset/Contents.json
  Example/Assets.xcassets/carplay/carplay_feedback.imageset/carplay_feedback.pdf
  Example/Assets.xcassets/carplay/carplay_overview.imageset/Contents.json
  Example/Assets.xcassets/carplay/carplay_overview.imageset/carplay_overview.pdf
  Example/Assets.xcassets/carplay/carplay_star.imageset/Contents.json
  Example/Assets.xcassets/carplay/carplay_star.imageset/carplay_star.pdf
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayManagerDelegate.swift
  MapboxNavigation/CarPlayMapViewController.swift
  MapboxNavigation/Resources/Base.lproj/Localizable.strings
  MapboxNavigation/Resources/hu.lproj/Localizable.strings
  MapboxNavigation/Resources/pt-PT.lproj/Localizable.strings
  MapboxNavigation/Resources/ru.lproj/Localizable.strings
  MapboxNavigation/Resources/sv.lproj/Localizable.strings
  MapboxNavigation/Resources/vi.lproj/Localizable.strings
  MapboxNavigationTests/CarPlayManagerTests.swift
Labels: CarPlay, ✓ ready for review

#1954 Starting navigation sends route retrieval performance event
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/EventDetails.swift
  MapboxCoreNavigation/NavigationEventsManager.swift
  MapboxCoreNavigation/NavigationService.swift
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/NavigationServiceTests.swift
  MapboxNavigation-Documentation.podspec
  TestHelper/Fixture.swift
Labels: - performance, topic: telemetry

#1971 Silence warnings in LegacyRouteController about LegacyRouteController
  MapboxCoreNavigation/LegacyRouteController.swift
Labels: - build, - refactor

#1976 Fix coordinate bounds in offline region downloads
  Example/OfflineViewController.swift
Labels: - bug

#1983 Tell delegate when passing visual instruction point
  CHANGELOG.md
  MapboxCoreNavigation/LegacyRouteController.swift
Labels: - bug, Regression, topic: instructions

#1979 Fix a bug with multileg routes
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigationTests/NavigationServiceTests.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  TestHelper/CoreLocation.swift
  TestHelper/Fixtures/multileg-route.json
Labels: - bug, ✓ ready for review

#1985 Update StyleManagerDelegate method signatures
  CHANGELOG.md
  Example/CustomStyles.swift
  MapboxNavigation/CarPlayMapViewController.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/StyleManager.swift
  MapboxNavigationTests/StyleManagerTests.swift
Labels: - bug, CarPlay, Regression

#1981 Carplay Route Failure Delegate Messaging
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayManagerDelegate.swift
  MapboxNavigationTests/CarPlayManagerTests.swift
Labels: - feature, CarPlay, topic: architecture, topic: directions
