Repository mapbox/mapbox-navigation-ios, pull requests merged in 2019-05, with the labels that each got.

#2119 CarPlay - Show route estimates.
  CHANGELOG.md
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigationTests/CarPlayManagerTests.swift
  MapboxNavigationTests/CarPlayNavigationViewControllerTests.swift
Labels: - bug, CarPlay, quick fix, topic: instructions

#2120 Clean up CarPlay route preview pane
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/CPTrip.swift
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayManagerDelegate.swift
Labels: - bug, - feature, - refactor, CarPlay

#2123 v0.32.0
  Bench/Info.plist
  BenchTests/Info.plist
  BenchUITests/Info.plist
  CHANGELOG.md
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  README.md
  TestHelper/Info.plist
  custom-navigation.md
Labels: - build

#2133 Map SDK v5.0.0
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
Labels: - build

#2136 Streamline status view toggling and interactivity
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/NavigationView.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/Resources/Base.lproj/Localizable.strings
  MapboxNavigation/Resources/bg.lproj/Localizable.strings
  MapboxNavigation/Resources/da.lproj/Localizable.strings
  MapboxNavigation/Resources/es.lproj/Localizable.strings
  MapboxNavigation/Resources/fr.lproj/Localizable.strings
  MapboxNavigation/Resources/hu.lproj/Localizable.strings
  MapboxNavigation/Resources/ko.lproj/Localizable.strings
  MapboxNavigation/Resources/nl.lproj/Localizable.strings
  MapboxNavigation/Resources/pt-PT.lproj/Localizable.strings
  MapboxNavigation/Resources/ru.lproj/Localizable.strings
  MapboxNavigation/Resources/sv.lproj/Localizable.strings
  MapboxNavigation/Resources/uk.lproj/Localizable.strings
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/StatusView.swift
  MapboxNavigation/String+LocalizedConstants.swift
Labels: - refactor

#2137 Fix status view when rerouting
  CHANGELOG.md
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/RouteMapViewController.swift
Labels: - bug, - refactor, topic: location
