Repository mapbox/mapbox-navigation-ios, pull requests merged in 2019-04, with the labels that each got.

#2076 Delete conflicting files to fix jazzy docset generation
  CHANGELOG.md
  MapboxCoreNavigation/MinimumEditDistance.swift
  MapboxCoreNavigation/Route.swift
  MapboxCoreNavigation/Router.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Date.swift
  MapboxNavigation/String.swift
Labels: - build, documentation, topic: documentation

#2080 v0.31.0
  Bench/Info.plist
  BenchTests/Info.plist
  BenchUITests/Info.plist
  CHANGELOG.md
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  README.md
  TestHelper/Info.plist
  custom-navigation.md
Labels: - build

#2082 Remove .swift-version file
  .swift-version
Labels: - build

#2083 Link more MapboxDirections.swift symbols
  scripts/document.sh
Labels: - build, documentation, topic: documentation

#2108 Fix CarPlay documentation warnings
  MapboxNavigation/CarPlayManagerDelegate.swift
Labels: CarPlay, documentation

#2100 Update CarPlay tracking icon when tracking state changes
  CHANGELOG.md
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
Labels: CarPlay, topic: design
