Repository mapbox/mapbox-navigation-ios, pull requests merged in 2020-02, with the labels that each got.

#2329 Pass API hostname through to speech synthesizer
  CHANGELOG.md
  MapboxNavigation/NavigationViewController.swift
Labels: - bug, topic: voice

#2332 Update analytics script in docs template
  docs/theme/templates/doc.mustache
Labels: documentation, topic: documentation

#2338 Fix crash when using dynamic UIColors in guidance card styling
  CHANGELOG.md
  Cartfile.resolved
  MapboxNavigation/ExitView.swift
  MapboxNavigation/GenericRouteShield.swift
  MapboxNavigation/InstructionsCardContainerView.swift
Labels: - crash
