Repository mapbox/mapbox-navigation-ios, pull requests merged in 2020-01, with the labels that each got.

#2291 Show speed limit indicator during turn-by-turn navigation
  CHANGELOG.md
  Cartfile.resolved
  MapboxCoreNavigation/RouteProgress.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/DayStyle.swift
  MapboxNavigation/NavigationView.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/NavigationViewLayout.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/SpeedLimitStyleKit.swift
  MapboxNavigation/SpeedLimitView.swift
Labels: - feature, CarPlay, UI, topic: traffic

#2296 Make InstructionsCardViewController reusable independently of NavigationComponent
  Cartfile.resolved
  MapboxNavigation/InstructionsCardViewController.swift
Labels: topic: instructions

#2301 Require map SDK v5.5.0 in v0.37.x
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
Labels: - build

#2303 v0.37.1
  Bench/Info.plist
  BenchTests/Info.plist
  BenchUITests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  TestHelper/Info.plist
Labels: - build

#2304 v0.38.2
  Bench/Info.plist
  BenchTests/Info.plist
  BenchUITests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  TestHelper/Info.plist
Labels: - build

#2302 Require map SDK v5.6.0
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/CoreConstants.swift
  MapboxCoreNavigation/NavigationEventsManager.swift
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/NavigationEventsManagerTests.swift
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
Labels: - build

#2297 Cleanup of Deprecated / Obsoleted Symbols
  CHANGELOG.md
  MapboxCoreNavigation/LegacyRouteController.swift
  MapboxCoreNavigation/NavigationEventsManager.swift
  MapboxCoreNavigation/OfflineDirections.swift
  MapboxCoreNavigation/RouteProgress.swift
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/BottomBannerViewController.swift
  MapboxNavigation/InstructionsBannerView.swift
  MapboxNavigation/MapboxVoiceController.swift
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/NavigationMapViewDelegate.swift
  MapboxNavigation/NavigationViewController+Obsolete.swift
  MapboxNavigation/StatusView.swift
Labels: - bug, quick fix

#2307 Add taginfo project file
  taginfo.json
Labels: Needs platform parity ticket, documentation, topic: directions, topic: documentation

#2306 Fix warning about casting SpeechError to URLError
  MapboxNavigation/MapboxVoiceController.swift
Labels: - build, topic: voice

#2308 Add conversions between Turf and MGLShape
  CHANGELOG.md
  MapboxCoreNavigation/RouteLeg.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/MGLShape.swift
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/RouteMapViewController.swift
Labels: - refactor

#2311 Document default initializers in place
  MapboxCoreNavigation/NavigationServiceDelegate.swift
  MapboxCoreNavigation/UnimplementedLogging.swift
  MapboxNavigation/CarPlayManagerDelegate.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/FeedbackViewController.swift
  MapboxNavigation/InstructionLabel.swift
  MapboxNavigation/InstructionsBannerView.swift
  MapboxNavigation/InstructionsCardContainerView.swift
  MapboxNavigation/NavigationMapViewDelegate.swift
  MapboxNavigation/NavigationViewControllerDelegate.swift
  MapboxNavigation/RouteVoiceController.swift
  MapboxNavigation/StyleManager.swift
Labels: documentation, topic: documentation

#2313 Inline conversion from Route to JSON string
  MapboxCoreNavigation/Route.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxNavigation.xcodeproj/project.pbxproj
Labels: - build, documentation, topic: documentation

#2315 Make End Navigation button localizable
  CHANGELOG.md
  MapboxNavigation/Resources/Base.lproj/Navigation.storyboard
  MapboxNavigation/Resources/Base.lproj/Navigation.strings
Labels: - bug, topic: localization

#2317 Require map SDK v5.5.0 in v0.37.x (redux)
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
Labels: - build

#2324 Update translations from Transifex
  MapboxCoreNavigation/Resources/es.lproj/Localizable.strings
  MapboxNavigation/Resources/de.lproj/Localizable.strings
  MapboxNavigation/Resources/fr.lproj/Localizable.strings
  MapboxNavigation/Resources/hu.lproj/Localizable.strings
  MapboxNavigation/Resources/ja.lproj/Localizable.strings
  MapboxNavigation/Resources/pt-PT.lproj/Localizable.strings
  MapboxNavigation/Resources/sv.lproj/Localizable.strings
  MapboxNavigation/Resources/yo.lproj/Localizable.strings
Labels: topic: localization

#2323 Gracefully snapshot route shield when window is absent
  CHANGELOG.md
  MapboxNavigation/InstructionPresenter.swift
Labels: - crash

#2321 v0.37.2
  Bench/Info.plist
  BenchTests/Info.plist
  BenchUITests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  TestHelper/Info.plist
Labels: - build

#2322 v0.38.3
  Bench/Info.plist
  BenchTests/Info.plist
  BenchUITests/Info.plist
  CHANGELOG.md
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  TestHelper/Info.plist
Labels: - build

#2328 Revert navigation event timestamps from RFC 3339 to previous format
  MapboxCoreNavigation/Date.swift
  MapboxCoreNavigationTests/DateTests.swift
  MapboxNavigation.xcodeproj/project.pbxproj
Labels: - bug, topic: telemetry
