Repository mapbox/mapbox-navigation-ios, pull requests merged in 2020-10, with the labels that each got.

#2669 Fix default visibility of the UserCourseView
  MapboxNavigation/NavigationMapView.swift
Labels: - bug

#2670 Fix CarPlay crash on iOS 14 after a navigation session
  MapboxNavigation/CarPlayManager.swift
Labels: - bug, CarPlay, ⚠️ DO NOT MERGE

#2690 Solve the End of route view UI broken before iOS 11
  CHANGELOG.md
  MapboxNavigation/Resources/Base.lproj/Navigation.storyboard
Labels: - bug, Regression, UI

#2378 Rerouting waypoints fix
  Example/CustomViewController.swift
  MapboxNavigation/RouteMapViewController.swift
Labels: - bug, ✓ ready for review

#2696 Metrics Trigger update
  .circleci/config.yml
Labels: - build, quick fix, ✓ ready for review

#2648 Update to Navigation Native 22.0.5 which uses Mapbox Common 7.1.2.
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Date.swift
  MapboxCoreNavigation/Navigator.swift
  MapboxCoreNavigation/OfflineDirections.swift
  MapboxCoreNavigation/PassiveLocationDataSource.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  MapboxCoreNavigationTests/NavigationServiceTests.swift
  MapboxNavigation-Documentation.podspec
Labels: - build, - chore, topic: location

#2699 Update to Maps SDK 6.2.2 and remove previous workaround to prevent excessive calls to `layoutSubviews()`.
  CHANGELOG.md
  Cartfile.resolved
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation/NavigationMapView.swift
Labels: - bug, UI

#2653 Add offline support to Navigation SDK and example application.
  CHANGELOG.md
  Example/AppDelegate.swift
  Example/Base.lproj/Localizable.strings
  Example/CustomViewController.swift
  Example/ResizableView.swift
  Example/SettingsItems.swift
  Example/SettingsViewController.swift
  Example/UIViewController.swift
  Example/ViewController.swift
  MapboxCoreNavigation/LegacyRouteController.swift
  MapboxCoreNavigation/MBXPeerWrapper.h
  MapboxCoreNavigation/NavigationLocationManager.swift
  MapboxCoreNavigation/NavigationService.swift
  MapboxCoreNavigation/OfflineDirections.swift
  MapboxCoreNavigation/PassiveLocationDataSource.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigation/Router.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/NavigationOptions.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/PassiveLocationManager.swift
  OfflineService/OfflineDataItem.swift
  OfflineService/OfflineDataRegionTableViewCell.swift
  OfflineService/OfflineDataRegionTableViewCell.xib
  OfflineService/OfflineServiceConstants.swift
  OfflineService/OfflineServiceDataSource.swift
  OfflineService/OfflineServiceError.swift
  OfflineService/OfflineServiceManager.swift
  OfflineService/OfflineServiceUtils.swift
  OfflineService/OfflineServiceViewController.swift
Labels: - feature, UI

#2706 v1.1.0-beta.2
  Bench/Info.plist
  BenchTests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  README.md
  TestHelper/Info.plist
Labels: - build, - chore

#2712 Revert changes which were added to support Offline Service.
  CHANGELOG.md
  Example/Base.lproj/Localizable.strings
  Example/CustomViewController.swift
  Example/ResizableView.swift
  Example/SettingsItems.swift
  Example/SettingsViewController.swift
  Example/ViewController.swift
  MapboxCoreNavigation/LegacyRouteController.swift
  MapboxCoreNavigation/NavigationService.swift
  MapboxCoreNavigation/OfflineDirections.swift
  MapboxCoreNavigation/PassiveLocationDataSource.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigation/Router.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/NavigationOptions.swift
  MapboxNavigation/NavigationViewController.swift
  OfflineService/OfflineDataItem.swift
  OfflineService/OfflineDataRegionTableViewCell.swift
  OfflineService/OfflineDataRegionTableViewCell.xib
  OfflineService/OfflineServiceConstants.swift
  OfflineService/OfflineServiceDataSource.swift
  OfflineService/OfflineServiceError.swift
  OfflineService/OfflineServiceManager.swift
  OfflineService/OfflineServiceUtils.swift
  OfflineService/OfflineServiceViewController.swift
Labels: - chore

#2623 Custom Route shapes fix
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/NavigationMapViewDelegate.swift
Labels: - bug, Regression, topic: cartography, topic: traffic

#2715 Custom Route shape tailwork
  CHANGELOG.md
  MapboxNavigation/NavigationMapView.swift
Labels: - bug, quick fix
