Repository mapbox/mapbox-navigation-ios, pull requests merged in 2020-08, with the labels that each got.

#2408 Add junction views.
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/ImageDownloader.swift
  MapboxNavigation/InstructionsCardViewController.swift
  MapboxNavigation/JunctionView.swift
  MapboxNavigation/TopBannerViewController.swift
  MapboxNavigation/URLSession.swift
Labels: - feature

#2510 [Guidance Cards][Part 4] Remove InstructionsCardStyle class
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/DayInstructionsCardStyle.swift
  MapboxNavigation/InstructionsCardCell.swift
  MapboxNavigation/InstructionsCardContainerView.swift
  MapboxNavigation/InstructionsCardStyle.swift
  MapboxNavigation/InstructionsCardView.swift
  MapboxNavigation/InstructionsCardViewController.swift
  MapboxNavigationTests/InstructionsCardCollectionTests.swift
Labels: - refactor

#2518 Fix warnings related to styling (end of route) in Interface Builder.
  CHANGELOG.md
  MapboxNavigation/Resources/Base.lproj/Navigation.storyboard
Labels: - bug, UI

#2477 MapboxNavigationNative v18.0.1
  CHANGELOG.md
  CONTRIBUTING.md
  Cartfile
  Cartfile.resolved
  Example/Base.lproj/Localizable.strings
  Example/SettingsViewController.swift
  Example/en.lproj/Localizable.stringsdict
  Example/yo.lproj/Localizable.stringsdict
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/FixLocation.swift
  MapboxCoreNavigation/Navigator.swift
  MapboxCoreNavigation/OfflineDirections.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigationTests/CLLocationTests.swift
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/NavigationServiceTests.swift
  MapboxCoreNavigationTests/OfflineRoutingTests.swift
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
Labels: - chore, backwards-incompatible

#2523 Navigation Style V5
  CHANGELOG.md
  Example/Base.lproj/Main.storyboard
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/DayStyle.swift
  MapboxNavigation/MGLStyle.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/Style.swift
Labels: UI, topic: design

#2532 Tests fix
  MapboxCoreNavigationTests/NavigationEventsManagerTests.swift
  MapboxNavigationTests/Support/TokenTestViewController.swift
Labels: - build, - tests, release blocker

#2496 Pre-release doc update
  MapboxCoreNavigation/Feedback.swift
  docs/cover.md
  docs/jazzy.yml
Labels: documentation, topic: documentation

#2530 Remove unused code.
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/InstructionsCard+Font.swift
  MapboxNavigation/UIColor+InstructionsCard.swift
Labels: - refactor

#2539 Remove deprecated methods.
  CHANGELOG.md
  MapboxNavigation/NavigationMapView.swift
Labels: - chore

#2528 Fix issue which causes speech synthesizer to fallback and speak two voice instructions at the same time.
  MapboxNavigation/MapboxSpeechSynthesizer.swift
Labels: - bug

#2535 Building extrusion highlights
  CHANGELOG.md
  Example/ViewController.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/DayStyle.swift
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/WaypointStyle.swift
  docs/jazzy.yml
Labels: - feature, UI

#2543 Update Mapbox Speech to v0.3.1.
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
Labels: - chore

#2410 Add location manager for free drive
  CHANGELOG.md
  Example/ViewController.swift
  MapboxCoreNavigation/BundleAdditions.swift
  MapboxCoreNavigation/CoreConstants.swift
  MapboxCoreNavigation/MBXPeerWrapper.h
  MapboxCoreNavigation/MapboxCoreNavigation.h
  MapboxCoreNavigation/NavigationEventsManager.swift
  MapboxCoreNavigation/PassiveLocationDataSource.swift
  MapboxCoreNavigation/SkuTokenProvider.swift
  MapboxCoreNavigation/URLSession.swift
  MapboxCoreNavigationTests/PassiveLocationDataSourceTests.swift
  MapboxCoreNavigationTests/SkuTokenProviderTests.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxCoreNavigation.xcscheme
  MapboxNavigation/PassiveLocationManager.swift
  MapboxNavigation/URLSession.swift
Labels: - feature, release blocker, topic: location

#2557 Remove routes in case if removeRoutes() was called.
  MapboxNavigation/NavigationMapView.swift
Labels: - bug, UI

#2558 Fix map view flickering.
  MapboxNavigation/NavigationMapView.swift
Labels: - bug, UI

#2509 Remove offline
  CHANGELOG.md
  Example/Base.lproj/Localizable.strings
  Example/OfflineViewController.swift
  Example/Settings.swift
  Example/SettingsItems.swift
  Example/SettingsViewController.swift
  Example/ViewController.swift
  MapboxCoreNavigation/OfflineDirections.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  docs/jazzy.yml
Labels: - refactor, topic: directions

#2564 Add fix which allows to dismiss FeedbackViewController on both iPad and iPhone.
  MapboxNavigation/FeedbackViewController.swift
Labels: - bug, UI

#2565 Update Maps SDK to 6.1.0-beta.2.
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
Labels: - build

#2566 Fix conflicts when generating documentation from combined module
  MapboxCoreNavigation/BundleAdditions.swift
  MapboxCoreNavigation/NavigationEventsManager.swift
  MapboxCoreNavigation/URLSession.swift
  MapboxNavigation-Documentation.podspec
  MapboxNavigation/Bundle.swift
  scripts/document.sh
Labels: - build, documentation, topic: documentation

#2570 Add fix which allows to remove waypoints when pressing on them.
  Example/ViewController.swift
Labels: - bug

#2567 Rename navigation guidance day/night style methods to navigation day/night style methods.
  CHANGELOG.md
  MapboxNavigation/MGLAccountManager.swift
  MapboxNavigation/MGLStyle.swift
Labels: - refactor, release blocker

#2575 v1.0.0-rc.2
  Bench/Info.plist
  BenchTests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  README.md
  TestHelper/Info.plist
Labels: - build

#2577 v1.1.0-alpha.1
  Bench/Info.plist
  BenchTests/Info.plist
  CHANGELOG.md
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  README.md
  TestHelper/Info.plist
Labels: - build
