Repository mapbox/mapbox-navigation-ios, pull requests merged in 2020-07, with the labels that each got.

#2440 OHHTTPStubs dependency
  Example/AppDelegate.swift
  ExampleUITests/ExampleUITests.swift
  ExampleUITests/Info.plist
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigationTests/NavigationViewControllerTests.swift
  MapboxNavigationTests/SKUTests.swift
  MapboxNavigationTests/Support/TokenTestViewController.swift
  ViewController+UITests.swift
Labels: - build, CarPlay

#2439 Rework Feedback UI assets to allow tinting.
  MapboxNavigation/FeedbackCollectionViewCell.swift
  MapboxNavigation/FeedbackViewController.swift
  MapboxNavigation/Resources/Assets.xcassets/feedback/confusing_audio.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback/confusing_audio.imageset/confusing_audio.pdf
  MapboxNavigation/Resources/Assets.xcassets/feedback/illegal_route.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback/illegal_route.imageset/illegal_route.pdf
  MapboxNavigation/Resources/Assets.xcassets/feedback/incorrect_visual.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback/incorrect_visual.imageset/incorrect_visual.pdf
  MapboxNavigation/Resources/Assets.xcassets/feedback/road_closure.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback/road_closure.imageset/road_closure.pdf
  MapboxNavigation/Resources/Assets.xcassets/feedback/route_quality.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback/route_quality.imageset/route_quality.pdf
Labels: - bug

#2396 Remove deprecated methods.
  CHANGELOG.md
  MapboxNavigation/NavigationViewControllerDelegate.swift
Labels: - refactor, backwards-incompatible

#2446 Mobile metrics hook
  .circleci/config.yml
Labels: - build

#2455 Change iOS version to match the one that is currently available in Circle CI.
  .circleci/config.yml
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.BottomBannerSnapshotTests/testBottomBannerViewController_iPhone_X_Portrait_iOS_13.4.1@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testLanesManeuver_iPhone6Plus_Portrait_iOS_13.4.1@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testRegularManeuver_iPhone6Plus_Portrait_iOS_13.4.1@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testTertiaryManeuver_iPhone6Plus_Portrait_iOS_13.4.1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAbbreviateInstructionsIncludingDelimiter_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAbbreviateInstructions_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAbbreviateWestFremontAvenue_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAdjacentShields_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testExitShields_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testGenericShields_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testInstructionsAndNextInstructions_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testLongDistance_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testMultilinePrimary_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testPrimaryShieldAndSecondary_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testSinglelinePrimaryAndSecondary_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testSinglelinePrimary_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testSweEngLongDistance_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testUkrainianLongDistance_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.LaneTests/testAllLanes30x30_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.LaneTests/testAllLanes90x90_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testArriveNone_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testArrive_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testLeftUTurn_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testMergeRight_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testRightUTurn_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testRoundaboutTurnLeft_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testRoundabout_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testStraightRoundabout_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testTurnRight_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testTurnSlightRight_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.RouteControllerSnapshotTests/testRouteSnappingOvershooting_iPhone_13_4_1@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.SimulatedLocationManagerTests/testSimulateRouteDoublesBack_iPhone_13_4_1@3x.png
Labels: quick fix

#2459 Fix crash in example app when placing route destination marker.
  Example/ViewController.swift
Labels: - crash

#2374 Offline Directions errors-clarification
  MapboxCoreNavigation/OfflineDirections.swift
  MapboxCoreNavigation/Resources/Base.lproj/Localizable.strings
  MapboxCoreNavigation/Resources/de.lproj/Localizable.strings
  MapboxCoreNavigation/Resources/es.lproj/Localizable.strings
  MapboxCoreNavigation/Resources/fr.lproj/Localizable.strings
  MapboxCoreNavigation/Resources/ja.lproj/Localizable.strings
  MapboxCoreNavigation/Resources/pt-PT.lproj/Localizable.strings
  MapboxCoreNavigation/Resources/ru.lproj/Localizable.strings
  MapboxCoreNavigation/Resources/sv.lproj/Localizable.strings
  MapboxCoreNavigation/Resources/vi.lproj/Localizable.strings
  MapboxCoreNavigation/Resources/yo.lproj/Localizable.strings
Labels: - bug, user: support, ✓ ready for review

#2466 Remove old testable references.
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxNavigation.xcscheme
Labels: quick fix

#2437 Upgrade to Mapbox Maps SDK for iOS v6.0.0
  .circleci/config.yml
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  README.md
Labels: - build, backwards-incompatible

#2473 Fix crash in action sheet when presenting on iPad.
  Example/ViewController.swift
Labels: - crash

#2483 Upgrade MapboxDirections to 0.33.0.
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation-Documentation.podspec
Labels: - build

#2348 Speech controller refactor
  CHANGELOG.md
  Example/CustomViewController.swift
  Example/ViewController.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/AVAudioSession.swift
  MapboxNavigation/Error.swift
  MapboxNavigation/MapboxSpeechSynthesizer.swift
  MapboxNavigation/MapboxVoiceController.swift
  MapboxNavigation/MultiplexedSpeechSynthesizer.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/RouteVoiceController.swift
  MapboxNavigation/SpeechSynthesizing.swift
  MapboxNavigation/SystemSpeechSynthesizer.swift
  MapboxNavigationTests/MapboxVoiceControllerTests.swift
  MapboxNavigationTests/SpeechSynthesizersControllerTests.swift
  MapboxNavigationTests/Support/NavigationViewControllerTestDoubles.swift
  TestHelper/Fixture.swift
Labels: - refactor, backwards-incompatible, release blocker, topic: voice

#2482 Fix CarPlayNavigationViewController tests
  MapboxNavigationTests/CarPlayManagerTests.swift
Labels: - crash, - tests, CarPlay

#2487 Fix top banner and steps cells alignment in landscape mode.
  MapboxNavigation/BottomBannerViewLayout.swift
  MapboxNavigation/StepsViewController.swift
  MapboxNavigation/TopBannerViewController.swift
Labels: - bug, UI

#2485 Consume Navigation Native through SDK Registry
  .circleci/config.yml
  Cartfile
  Cartfile.resolved
  README.md
Labels: CI, dependency management

#2479 Make sure to access application state from UI thread.
  MapboxCoreNavigation/EventDetails.swift
  MapboxCoreNavigationTests/NavigationEventsManagerTests.swift
Labels: - bug

#2494 MapboxSpeechSynthesizer API update
  MapboxNavigation/MapboxSpeechSynthesizer.swift
  MapboxNavigation/MultiplexedSpeechSynthesizer.swift
Labels: quick fix, topic: voice, ✓ ready for review

#2500 Fix crash when passing Dictionary to NSExpression.
  Example/ViewController.swift
  MapboxNavigation/NavigationMapView.swift
Labels: - bug, - crash

#2505 Add temporary fix which creates separate source for main route casing.
  MapboxNavigation/NavigationMapView.swift
Labels: - bug, Regression, UI

#2506 Fix vanishing route line arrival crash.
  MapboxNavigation/NavigationMapView.swift
Labels: - bug, - crash

#2515 Stop speaking instructions in case if voice is muted.
  MapboxNavigation/RouteVoiceController.swift
Labels: - bug
