Repository mapbox/mapbox-navigation-ios, pull requests merged in 2020-06, with the labels that each got.

#2359 Puck desaturation while Location updates are missing
  MapboxNavigation/DayStyle.swift
  MapboxNavigation/UserCourseView.swift
Labels: - feature, size: S, topic: design, topic: location

#2390 Fix code snippet in Configuration section.
  README.md
  docs/cover.md
Labels: documentation

#2373 RouteController Delegate fix for no voice navigation
  MapboxCoreNavigation/RouteController.swift
Labels: - bug, topic: voice, ✓ ready for review

#2376 Resume camera update
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/RouteMapViewController.swift
Labels: - bug, topic: location, ✓ ready for review

#2387 Puck Location fix
  MapboxNavigation/NavigationMapView.swift
Labels: - bug, user: support

#2385 Add Greek Translation
  Example/el.lproj/Main.strings
  MapboxCoreNavigation/Resources/el.lproj/Localizable.strings
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Resources/el.lproj/Localizable.strings
  MapboxNavigation/Resources/el.lproj/Localizable.stringsdict
  MapboxNavigation/Resources/el.lproj/Navigation.strings
Labels: topic: localization

#2393 Update Turf v0.5.0
  Cartfile
  Cartfile.resolved
  Example/OfflineViewController.swift
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/CLLocation.swift
  MapboxCoreNavigation/LegacyRouteController.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigation/RouteProgress.swift
  MapboxCoreNavigation/SimulatedLocationManager.swift
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/RouteProgressTests.swift
  MapboxNavigation-Documentation.podspec
  MapboxNavigation/InstructionPresenter.swift
  MapboxNavigation/MGLShape.swift
  MapboxNavigation/Match.swift
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/Route.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/VisualInstructionComponent.swift
  MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift
  MapboxNavigationTests/RouteTests.swift
Labels: - build

#2405 Re-enable MAU
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/AppDelegate.swift
  ExampleUITests/ExampleUITests.swift
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/MBXAccounts+CoreNavigationAdditions.m
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigationTests/SKUIDTestable.swift
  MapboxNavigationTests/SKUTests.swift
Labels: - build, - feature

#2404 Update nav native dependency to 9.2.1 version
  .circleci/config.yml
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/FixLocation.swift
  MapboxCoreNavigation/RouteState.swift
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/Extensions/RouteStateTests.swift
  MapboxNavigation.xcodeproj/project.pbxproj
Labels: - tests, platform parity, topic: directions, topic: location

#2412 Update nav-native to 9.2.1
  .circleci/config.yml
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/FixLocation.swift
  MapboxCoreNavigation/RouteState.swift
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/Extensions/RouteStateTests.swift
  MapboxCoreNavigationTests/NavigationServiceTests.swift
  MapboxNavigation.xcodeproj/project.pbxproj
Labels: - tests, platform parity, topic: directions, topic: location

#2418 Make vanishing route opt-in
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/RouteMapViewController.swift
Labels: - feature, UI

#2377 Fade route line during navigation
  CHANGELOG.md
  MapboxNavigation/DayStyle.swift
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/NavigationMapViewDelegate.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/NavigationViewControllerDelegate.swift
  MapboxNavigation/RouteMapViewController.swift
Labels: - feature, UI, backwards-incompatible

#2427 Xcode 11.5
  .circleci/config.yml
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.BottomBannerSnapshotTests/testBottomBannerViewController_iPhone_X_Portrait_iOS_13.5@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testLanesManeuver_iPhone6Plus_Portrait_iOS_13.5@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testRegularManeuver_iPhone6Plus_Portrait_iOS_13.5@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testTertiaryManeuver_iPhone6Plus_Portrait_iOS_13.5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAbbreviateInstructionsIncludingDelimiter_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAbbreviateInstructions_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAbbreviateWestFremontAvenue_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAdjacentShields_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testExitShields_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testGenericShields_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testInstructionsAndNextInstructions_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testLongDistance_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testMultilinePrimary_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testPrimaryShieldAndSecondary_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testSinglelinePrimaryAndSecondary_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testSinglelinePrimary_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testSweEngLongDistance_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testUkrainianLongDistance_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.LaneTests/testAllLanes30x30_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.LaneTests/testAllLanes90x90_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testArriveNone_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testArrive_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testLeftUTurn_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testMergeRight_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testRightUTurn_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testRoundaboutTurnLeft_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testRoundabout_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testStraightRoundabout_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testTurnRight_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testTurnSlightRight_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.RouteControllerSnapshotTests/testRouteSnappingOvershooting_iPhone_13_5@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.SimulatedLocationManagerTests/testSimulateRouteDoublesBack_iPhone_13_5@3x.png
Labels: - build, - tests

#2422 Disable 32-bit architectures
  MapboxNavigation.xcodeproj/project.pbxproj
Labels: - build
