Repository mapbox/mapbox-navigation-ios, pull requests merged in 2020-11, with the labels that each got.

#2710 Fix speed multiplier
  CHANGELOG.md
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/TopBannerViewController.swift
Labels: - bug

#2725 Add speed limit feedback.
  CHANGELOG.md
  MapboxCoreNavigation/Feedback.swift
  MapboxNavigation/FeedbackItem.swift
  MapboxNavigation/FeedbackSubtypeViewController.swift
  MapboxNavigation/Resources/Base.lproj/Localizable.strings
Labels: UI, iOS

#2718 Prevent clear map button disappearance when pressing on route.
  CHANGELOG.md
  Example/ViewController.swift
Labels: - bug, UI, iOS

#2728 Add workaround which allows to perform maneuver view redrawing in time.
  CHANGELOG.md
  MapboxNavigation/NavigationViewController.swift
Labels: - bug, UI, iOS

#2705 Allow to customize the bottom banner view height
  CHANGELOG.md
  MapboxNavigation/NavigationView.swift
  MapboxNavigation/NavigationViewLayout.swift
  MapboxNavigation/RouteMapViewController.swift
Labels: - bug, UI, iOS

#2735 Add Ukrainian localization.
  CHANGELOG.md
  Example/uk.lproj/Main.strings
  MapboxNavigation/Resources/uk.lproj/Localizable.strings
  MapboxNavigation/Resources/uk.lproj/Localizable.stringsdict
  MapboxNavigation/Resources/uk.lproj/Navigation.strings
Labels: UI, iOS

#2664 create a halo view for reduced accuracy in userCourseView
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/DayStyle.swift
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/UserCourseView.swift
  MapboxNavigation/UserHaloCourseView.swift
  docs/jazzy.yml
Labels: - feature, UI, iOS, topic: location

#2738 v1.1.0
  Bench/Info.plist
  BenchTests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  README.md
  TestHelper/Info.plist
  custom-navigation.md
Labels: - build

#2721 create templates for github issue and pr
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#2454 Test for out-of-band navigator calls.
  MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
Labels: - tests, topic: location

#2743 Update project files to Xcode 12.2.
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Bench.xcscheme
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example-CarPlay.xcscheme
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxCoreNavigation.xcscheme
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxNavigation.xcscheme
Labels: - build, iOS

#2719 Allow styling each route differently
  CHANGELOG.md
  MapboxNavigation/NavigationMapView.swift
Labels: UI, iOS
