Repository mapbox/mapbox-navigation-ios, pull requests merged in 2020-04, with the labels that each got.

#2352 Minimize NSObject inheritance
  MapboxCoreNavigation/EndOfRouteFeedback.swift
  MapboxCoreNavigation/NavigationSettings.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigation/RouteProgress.swift
  MapboxNavigation/DataCache.swift
  MapboxNavigation/FeedbackItem.swift
  MapboxNavigation/MapboxVoiceController.swift
  MapboxNavigation/NavigationOptions.swift
  MapboxNavigation/RouteVoiceController.swift
  MapboxNavigation/StyleManager.swift
Labels: - refactor, backwards-incompatible

#2357 Constrain current route shield; simplify current road name label
  CHANGELOG.md
  MapboxNavigation/InstructionPresenter.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/UIImage.swift
Labels: - bug, - refactor

#2350 Directions Interface Compatibility Update
  Cartfile
  Cartfile.resolved
  Example/AppDelegate+CarPlay.swift
  Example/CustomViewController.swift
  Example/ViewController+GuidanceCards.swift
  Example/ViewController.swift
  MapboxCoreNavigation/EventDetails.swift
  MapboxCoreNavigation/LegacyRouteController.swift
  MapboxCoreNavigation/NavigationRouteOptions.swift
  MapboxCoreNavigation/NavigationService.swift
  MapboxCoreNavigation/OfflineDirections.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigation/RouteProgress.swift
  MapboxCoreNavigation/Router.swift
  MapboxCoreNavigationTests/LocationTests.swift
  MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  MapboxCoreNavigationTests/MapboxNavigationServiceSpec.swift
  MapboxCoreNavigationTests/NavigationEventsManagerTests.swift
  MapboxCoreNavigationTests/NavigationServiceTests.swift
  MapboxCoreNavigationTests/OfflineRoutingTests.swift
  MapboxCoreNavigationTests/RouteProgressTests.swift
  MapboxCoreNavigationTests/TunnelAuthorityTests.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/CPTrip.swift
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayManagerDelegate.swift
  MapboxNavigation/MapboxVoiceController.swift
  MapboxNavigation/Match.swift
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigationTests/CarPlayManagerTests.swift
  MapboxNavigationTests/CarPlayNavigationViewControllerTests.swift
  MapboxNavigationTests/GuidanceCardsSnapshotTests.swift
  MapboxNavigationTests/InstructionsCardCollectionTests.swift
  MapboxNavigationTests/LeaksSpec.swift
  MapboxNavigationTests/MapboxVoiceControllerTests.swift
  MapboxNavigationTests/NavigationMapViewTests.swift
  MapboxNavigationTests/NavigationViewControllerTests.swift
  MapboxNavigationTests/RouteControllerSnapshotTests.swift
  MapboxNavigationTests/RouteTests.swift
  MapboxNavigationTests/StepsViewControllerTests.swift
  TestHelper/DirectionsSpy.swift
  TestHelper/Fixture.swift
Labels: - refactor, epic

#2151 Add MapboxAccounts
  .circleci/config.yml
  CHANGELOG.md
  Cartfile
  Cartfile.private
  Cartfile.resolved
  Example/AppDelegate.swift
  ExampleUITests/ExampleUITests.swift
  ExampleUITests/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/MBXAccounts+CoreNavigationAdditions.h
  MapboxCoreNavigation/MBXAccounts+CoreNavigationAdditions.m
  MapboxCoreNavigation/MapboxCoreNavigation.h
  MapboxCoreNavigation/NavigationService.swift
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxNavigation.xcscheme
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigationTests/ImageDownloaderTests.swift
  MapboxNavigationTests/SKUIDTestable.swift
  MapboxNavigationTests/SKUTestable.swift
  MapboxNavigationTests/SKUTests.swift
  README.md
  ViewController+UITests.swift
  docs/cover.md
Labels: - feature, backwards-incompatible

#2360 Fix Xcode 11.4 builds
  .circleci/config.yml
  Cartfile.private
  Cartfile.resolved
  MapboxNavigationTests/CarPlayManagerTests.swift
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.BottomBannerSnapshotTests/testBottomBannerViewController_iPhone_X_Portrait_iOS_13.4@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testLanesManeuver_iPhone6Plus_Portrait_iOS_13.4@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testRegularManeuver_iPhone6Plus_Portrait_iOS_13.4@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testTertiaryManeuver_iPhone6Plus_Portrait_iOS_13.4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAbbreviateInstructionsIncludingDelimiter_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAbbreviateInstructions_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAbbreviateWestFremontAvenue_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAdjacentShields_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testExitShields_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testGenericShields_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testInstructionsAndNextInstructions_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testLongDistance_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testMultilinePrimary_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testPrimaryShieldAndSecondary_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testSinglelinePrimaryAndSecondary_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testSinglelinePrimary_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testSweEngLongDistance_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testUkrainianLongDistance_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.LaneTests/testAllLanes30x30_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.LaneTests/testAllLanes90x90_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testArriveNone_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testArrive_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testLeftUTurn_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testMergeRight_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testRightUTurn_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testRoundaboutTurnLeft_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testRoundabout_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testStraightRoundabout_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testTurnRight_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testTurnSlightRight_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.RouteControllerSnapshotTests/testRouteSnappingOvershooting_iPhone_13_4@3x.png
  MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.SimulatedLocationManagerTests/testSimulateRouteDoublesBack_iPhone_13_4@3x.png
Labels: - build

#2362 v0.39.1
  Bench/Info.plist
  BenchTests/Info.plist
  BenchUITests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  TestHelper/Info.plist
Labels: - build
