Repository mapbox/mapbox-navigation-ios, pull requests merged in 2020-12, with the labels that each got.

#2737 Update vanishing point calculation with a location based implementation
  CHANGELOG.md
  Cartfile.resolved
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/VanishingRouteLine.swift
  MapboxNavigationTests/Fixtures/route-for-vanishing-route-line.json
  MapboxNavigationTests/NavigationMapViewTests.swift
Labels: UI, iOS

#2755 Swipe bugs (instructions cards and right-to-left languages)
  CHANGELOG.md
  MapboxNavigation/InstructionsCardViewController.swift
  MapboxNavigation/NavigationViewController.swift
Labels: - bug, UI, iOS, topic: instructions, topic: localization

#2759 Update Mapbox Navigation to v1.2.0-alpha.3.
  Bench/Info.plist
  BenchTests/Info.plist
  CHANGELOG.md
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  README.md
  TestHelper/Info.plist
Labels: iOS

#2768 Use custom CocoaPods version for all build jobs.
  .circleci/config.yml
  Gemfile
Labels: - build, iOS

#2741 Add ability to override congestion levels for specific road classes.
  CHANGELOG.md
  Example/ViewController.swift
  MapboxCoreNavigation/RouteLeg.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/DayStyle.swift
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigationTests/NavigationMapViewTests.swift
  TestHelper/Fixtures/route-with-missing-road-classes.json
  TestHelper/Fixtures/route-with-mixed-road-classes.json
  TestHelper/Fixtures/route-with-not-present-road-classes.json
  TestHelper/Fixtures/route-with-road-classes-single-congestion.json
  TestHelper/Fixtures/route-with-same-congestion-different-road-classes.json
  scripts/.gitignore
Labels: UI, iOS

#2769 Make `NavigationAnnotation` public.
  CHANGELOG.md
  MapboxNavigation/Style.swift
Labels: UI, iOS

#2763 Allow customizing the floating buttons
  CHANGELOG.md
  Cartfile.resolved
  MapboxNavigation/NavigationView.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/NavigationViewLayout.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/Style.swift
  docs/jazzy.yml
Labels: - feature, UI

#2770 MapboxNavigationNative v28.1
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
Labels: - build, dependency management

#2772 v1.2.0-beta.1
  Bench/Info.plist
  BenchTests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  README.md
  TestHelper/Info.plist
Labels: - build

#2773 Improve MapboxNavigation project structure.
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/AVAudioSession.swift
  MapboxNavigation/Cache.swift
  MapboxNavigation/CarPayCompassView.swift
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/CarPlaySearchController+CPSearchTemplateDelegate.swift
  MapboxNavigation/Constants.swift
  MapboxNavigation/DashedLineView.swift
  MapboxNavigation/DayStyle.swift
  MapboxNavigation/Error.swift
  MapboxNavigation/ErrorCode.swift
  MapboxNavigation/ExitView.swift
  MapboxNavigation/FeedbackItem.swift
  MapboxNavigation/FeedbackViewController.swift
  MapboxNavigation/HighwayShield.swift
  MapboxNavigation/InstructionPresenter.swift
  MapboxNavigation/InstructionsCardCell.swift
  MapboxNavigation/InstructionsCardCollectionDelegate.swift
  MapboxNavigation/InstructionsCardContainerView.swift
  MapboxNavigation/InstructionsCardView.swift
  MapboxNavigation/InstructionsCardViewController.swift
  MapboxNavigation/JunctionView.swift
  MapboxNavigation/LaneView.swift
  MapboxNavigation/ManeuverView.swift
  MapboxNavigation/MapboxSpeechSynthesizer.swift
  MapboxNavigation/MultiplexedSpeechSynthesizer.swift
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/NavigationMapViewDelegate.swift
  MapboxNavigation/NavigationView.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/NightStyle.swift
  MapboxNavigation/RecentItem.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigation/RouteVoiceController.swift
  MapboxNavigation/SpeechSynthesizing.swift
  MapboxNavigation/SpeedLimitView.swift
  MapboxNavigation/StyleKitMarker.swift
  MapboxNavigation/StyleManager.swift
  MapboxNavigation/SystemSpeechSynthesizer.swift
  MapboxNavigation/TopBannerViewController.swift
  MapboxNavigation/UIDevice.swift
  MapboxNavigation/UIEdgeInsets.swift
  MapboxNavigation/UserCourseView.swift
  MapboxNavigation/UserHaloCourseView.swift
  MapboxNavigation/VanishingRouteLine.swift
  MapboxNavigation/VisualInstruction.swift
  docs/jazzy.yml
Labels: - build, - chore, - refactor
