Repository mapbox/mapbox-navigation-ios, pull requests merged in 2020-09, with the labels that each got.

#2585 Update to MapboxDirections v0.33.2.
  CHANGELOG.md
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation-Documentation.podspec
Labels: - build

#2576 Make Second Level Feedback strings localizable
  Example/Base.lproj/Localizable.strings
  Example/ViewController.swift
  MapboxNavigation/FeedbackItem.swift
  MapboxNavigation/FeedbackSubtypeViewController.swift
  MapboxNavigation/Resources/Base.lproj/Localizable.strings
  MapboxNavigation/Resources/en.lproj/Localizable.stringsdict
Labels: release blocker, topic: localization

#2586 Update day/night style URLs.
  MapboxNavigation/MGLStyle.swift
Labels: - chore, UI, release blocker

#2580 Fix traffic congestion rendering issues.
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/NavigationMapViewDelegate.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/NavigationViewControllerDelegate.swift
  MapboxNavigation/RouteMapViewController.swift
Labels: - bug, UI

#2581 Make updateRoute(_:) public.
  CHANGELOG.md
  Example/ViewController.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/RouteMapViewController.swift
Labels: UI

#2596 Remove rounding corners method which is causing presentation issues in end of route view. (#2590)
  MapboxNavigation/EndOfRouteViewController.swift
  MapboxNavigation/UIView.swift
Labels: - chore

#2366 Route Refresh
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/AppDelegate+CarPlay.swift
  Example/CustomViewController.swift
  Example/ViewController.swift
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/CoreConstants.swift
  MapboxCoreNavigation/LegacyRouteController.swift
  MapboxCoreNavigation/NavigationRouteOptions.swift
  MapboxCoreNavigation/NavigationService.swift
  MapboxCoreNavigation/NavigationServiceDelegate.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigation/RouteProgress.swift
  MapboxCoreNavigation/Router.swift
  MapboxCoreNavigation/RouterDelegate.swift
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/LocationTests.swift
  MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  MapboxCoreNavigationTests/MapboxNavigationServiceSpec.swift
  MapboxCoreNavigationTests/NavigationEventsManagerTests.swift
  MapboxCoreNavigationTests/NavigationServiceTests.swift
  MapboxCoreNavigationTests/RouteProgressTests.swift
  MapboxCoreNavigationTests/TunnelAuthorityTests.swift
  MapboxNavigation-Documentation.podspec
  MapboxNavigation/CPTrip.swift
  MapboxNavigation/CarPlayManager.swift
  MapboxNavigation/CarPlayManagerDelegate.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/NavigationViewControllerDelegate.swift
  MapboxNavigation/RouteMapViewController.swift
  MapboxNavigationTests/CarPlayManagerTests.swift
  MapboxNavigationTests/CarPlayNavigationViewControllerTests.swift
  MapboxNavigationTests/GuidanceCardsSnapshotTests.swift
  MapboxNavigationTests/InstructionsCardCollectionTests.swift
  MapboxNavigationTests/LeaksSpec.swift
  MapboxNavigationTests/NavigationViewControllerTests.swift
  MapboxNavigationTests/RouteControllerSnapshotTests.swift
  MapboxNavigationTests/SpeechSynthesizersControllerTests.swift
  MapboxNavigationTests/StepsViewControllerTests.swift
  README.md
  docs/cover.md
Labels: - feature, - refactor, platform parity, release blocker, topic: directions

#2598 Fix compiler errors in BenchTests
  Bench/BenchViewController.swift
  BenchTests/BenchTests.swift
  TestHelper/SpeechAPISpy.swift
Labels: - build, - performance, - tests

#2599 v1.0.0-rc.3
  Bench/Info.plist
  BenchTests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  README.md
  TestHelper/Info.plist
Labels: - build

#2604 Building highlights before reaching the destination (#2582)
  Example/ViewController.swift
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/RouteMapViewController.swift
Labels: - build

#2601 Add ability to control hiding/showing vanishing route line.
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
Labels: - bug, CarPlay, UI

#2606 Update Maps SDK to 6.1.0.
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
Labels: - build, - chore

#2607 Fix NextBannerView presentation.
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/NextBannerView.swift
Labels: - bug, UI

#2613 Fix info button alignment and improve bottom banner height constraints for various device models.
  CHANGELOG.md
  MapboxNavigation/BottomBannerViewLayout.swift
  MapboxNavigation/NavigationView.swift
  MapboxNavigation/NavigationViewLayout.swift
  MapboxNavigation/RouteMapViewController.swift
Labels: - bug, UI

#2616 Update German, Vietnamese translations
  MapboxNavigation/Resources/de.lproj/Localizable.strings
  MapboxNavigation/Resources/de.lproj/Localizable.stringsdict
  MapboxNavigation/Resources/de.lproj/Navigation.strings
  MapboxNavigation/Resources/vi.lproj/Localizable.strings
  MapboxNavigation/Resources/vi.lproj/Localizable.stringsdict
Labels: topic: localization

#2612 Removed the timer and state management for building highlights
  Example/ViewController.swift
  MapboxNavigation/NavigationMapView.swift
  MapboxNavigation/NavigationViewController.swift
  MapboxNavigation/RouteMapViewController.swift
Labels: UI

#2614 Update size of collection view cell with instructions when device is rotated.
  MapboxNavigation/InstructionsCardView.swift
  MapboxNavigation/InstructionsCardViewController.swift
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testLanesManeuver_iPhone6Plus_Portrait_iOS_13.4.1@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testLanesManeuver_iPhone6Plus_Portrait_iOS_13.5@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testLanesManeuver_iPhone_8_Plus_Portrait_iOS_12.1@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testLanesManeuver_iPhone_8_Plus_Portrait_iOS_12.2@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testLanesManeuver_iPhone_8_Plus_Portrait_iOS_13.5@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testRegularManeuver_iPhone6Plus_Portrait_iOS_13.4.1@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testRegularManeuver_iPhone6Plus_Portrait_iOS_13.5@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testRegularManeuver_iPhone_8_Plus_Portrait_iOS_12.1@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testRegularManeuver_iPhone_8_Plus_Portrait_iOS_12.2@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testRegularManeuver_iPhone_8_Plus_Portrait_iOS_13.5@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testTertiaryManeuver_iPhone6Plus_Portrait_iOS_13.4.1@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testTertiaryManeuver_iPhone6Plus_Portrait_iOS_13.5@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testTertiaryManeuver_iPhone_8_Plus_Portrait_iOS_12.1@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testTertiaryManeuver_iPhone_8_Plus_Portrait_iOS_12.2@3x.png
  MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testTertiaryManeuver_iPhone_8_Plus_Portrait_iOS_13.5@3x.png
Labels: - bug, UI

#2619 v1.0.0-rc.4
  Bench/Info.plist
  BenchTests/Info.plist
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  README.md
  TestHelper/Info.plist
Labels: - build, - chore

#2624 Cherry-pick of making RouteProgress Congestion data readonly
  CHANGELOG.md
  MapboxCoreNavigation/RouteProgress.swift
Labels: - refactor

#2625 Match Android for Feedback event JSON keys and the sending of a single event per category
  MapboxCoreNavigation/CoreFeedbackEvent.swift
  MapboxCoreNavigation/Feedback.swift
  MapboxNavigation/FeedbackItem.swift
  MapboxNavigation/FeedbackSubtypeViewController.swift
  MapboxNavigation/Resources/Base.lproj/Localizable.strings
Labels: - refactor, topic: telemetry

#2622 Send Feedback event subtypes
  MapboxCoreNavigation/CoreFeedbackEvent.swift
  MapboxCoreNavigation/EventDetails.swift
  MapboxCoreNavigation/Feedback.swift
  MapboxNavigation/FeedbackItem.swift
  MapboxNavigation/FeedbackSubtypeViewController.swift
  MapboxNavigation/Resources/Base.lproj/Localizable.strings
Labels: - bug, topic: telemetry

#2621 Add new positioning category for nav feedback
  MapboxCoreNavigation/CoreFeedbackEvent.swift
  MapboxCoreNavigation/EventDetails.swift
  MapboxCoreNavigation/Feedback.swift
  MapboxNavigation/CarPlayNavigationViewController.swift
  MapboxNavigation/FeedbackItem.swift
  MapboxNavigation/FeedbackSubtypeViewController.swift
  MapboxNavigation/FeedbackViewController.swift
  MapboxNavigation/Resources/Assets.xcassets/feedback/positioning.imageset/Contents.json
  MapboxNavigation/Resources/Assets.xcassets/feedback/positioning.imageset/category_position.pdf
  MapboxNavigation/Resources/Base.lproj/Localizable.strings
Labels: - feature, topic: telemetry

#2628 Revert use of convertToSnakeCase JSON Encoding strategy.
  MapboxCoreNavigation/EventDetails.swift
Labels: - bug, topic: telemetry

#2630 Fix sizing of FeedbackViewCategoryCell
  MapboxNavigation/FeedbackCollectionViewCell.swift
  MapboxNavigation/FeedbackViewController.swift
Labels: - bug, topic: design, topic: telemetry

#2627 Document guidance cards, junction views
  CHANGELOG.md
  Example/ViewController+GuidanceCards.swift
  MapboxNavigation/InstructionsCardContainerView.swift
  MapboxNavigation/InstructionsCardViewController.swift
  MapboxNavigation/JunctionView.swift
  MapboxNavigation/TopBannerViewController.swift
  docs/jazzy.yml
Labels: documentation, topic: documentation, topic: instructions

#2615 Codable Progress classes
  CHANGELOG.md
  MapboxCoreNavigation/EventDetails.swift
  MapboxCoreNavigation/RouteLegProgress.swift
  MapboxCoreNavigation/RouteProgress.swift
  MapboxCoreNavigation/RouteStepProgress.swift
  MapboxCoreNavigationTests/RouteProgressTests.swift
  MapboxNavigation.xcodeproj/project.pbxproj
Labels: - refactor

#2620 Avoid manual index arithmetic
  MapboxNavigation/NavigationMapView.swift
Labels: - crash, - refactor

#2633 Avoid reconfiguring passive navigator
  MapboxCoreNavigation/PassiveLocationDataSource.swift
  MapboxCoreNavigationTests/PassiveLocationDataSourceTests.swift
Labels: - crash, topic: location

#2640 Remove unused variable in FeedbackViewController
  MapboxNavigation/FeedbackViewController.swift
Labels: - build, topic: telemetry

#2569 Update screenshot
  docs/img/navigation.png
Labels: - chore, documentation, topic: documentation

#2635 Improve performance of Wayname calculation
  MapboxNavigation/RouteMapViewController.swift
Labels: - performance

#2644 Update translations for v1.0.0
  Example/el.lproj/Main.strings
  Example/es.lproj/Main.strings
  MapboxCoreNavigation/Resources/es.lproj/Localizable.strings
  MapboxNavigation/Resources/de.lproj/Localizable.strings
  MapboxNavigation/Resources/el.lproj/Navigation.strings
  MapboxNavigation/Resources/es.lproj/Localizable.strings
  MapboxNavigation/Resources/es.lproj/Localizable.stringsdict
  MapboxNavigation/Resources/es.lproj/Navigation.strings
  MapboxNavigation/Resources/ru.lproj/Navigation.strings
  MapboxNavigation/Resources/uk.lproj/Navigation.strings
  MapboxNavigation/Resources/vi.lproj/Localizable.strings
  MapboxNavigation/Resources/vi.lproj/Navigation.strings
Labels: - chore, topic: localization

#2642 Vanished Route line flickering
  CHANGELOG.md
  MapboxCoreNavigation/LegacyRouteController.swift
  MapboxCoreNavigation/RouteController.swift
  MapboxCoreNavigation/RouteProgress.swift
  MapboxCoreNavigation/Router.swift
Labels: - bug, UI

#2643 Upscaling FPS on plugged in device
  CHANGELOG.md
  MapboxNavigation/NavigationMapView.swift
Labels: - bug, - performance, topic: camera

#2579 Add automated test of PassiveLocationDataSource
  MapboxCoreNavigation/PassiveLocationDataSource.swift
  MapboxCoreNavigationTests/PassiveLocationDataSourceTests.swift
Labels: - tests, topic: location

#2646 v1.0.0
  Bench/Info.plist
  BenchTests/Info.plist
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  README.md
  TestHelper/Info.plist
  custom-navigation.md
  docs/cover.md
  docs/jazzy.yml
Labels: - build, backwards-incompatible

#2651 v1.1.0-alpha.2
  Bench/Info.plist
  BenchTests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Info.plist
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxCoreNavigationTests/Info.plist
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation/Info.plist
  MapboxNavigationTests/Info.plist
  README.md
  TestHelper/Info.plist
Labels: - build

#2659 Prevent updates to `UserCourseView` when layoutSubviews() is called.
  MapboxNavigation/NavigationMapView.swift
Labels: - bug, UI

#2661 Skip shape annotations when inserting route line into style
  MapboxNavigation/NavigationMapView.swift
Labels: - bug, UI

#2662 MapboxNavigationNative v18.0.5
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation-Documentation.podspec
Labels: - build
