Repository mapbox/mapbox-navigation-ios, pull requests merged in 2021-01, with the labels that each got.

#2774 Address build error with Carthage dependencies and Xcode 12.3
  MapboxNavigation.xcodeproj/project.pbxproj
  input.xcfilelist
  output.xcfilelist
Labels: - build

#2780 Embed Example-CarPlay, Bench dependencies using Carthage
  MapboxNavigation.xcodeproj/project.pbxproj
Labels: - build, CarPlay

#2781 MapboxNavigationNative v29.0
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxCoreNavigation/Tunnel.swift
  MapboxCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock
  MapboxNavigation-Documentation.podspec
Labels: - build, - crash
