Repository mapbox/mapbox-navigation-ios, pull requests merged in 2021-12, with the labels that each got.

#3620 Respect heading while walking
  CHANGELOG.md
  Sources/MapboxCoreNavigation/CoreConstants.swift
  Sources/MapboxCoreNavigation/LegacyRouteController.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/RouteProgress.swift
  Sources/MapboxCoreNavigation/Router.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationViewportDataSource.swift
Labels: topic: location, UI

#3614 Update dependencies.
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/BillingHandler.swift
  Sources/MapboxCoreNavigation/FixLocation.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxNavigation/NavigationCameraStateTransition.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/TestHelper/Fixtures/route-for-off-route.json
  Sources/TestHelper/Fixtures/route-with-10-legs.json
  Sources/TestHelper/Fixtures/route-with-lanes.json
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/BillingHandlerTests.swift
  Tests/MapboxCoreNavigationTests/CLLocationTests.swift
  Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  Tests/MapboxCoreNavigationTests/RouteControllerTests.swift
  Tests/MapboxNavigationTests/NavigationCameraTests.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
  Tests/MapboxNavigationTests/SKUTests.swift
Labels: build

#3634 Allow maneuver arrow styling.
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: bug, UI

#3635 Add `TopBannerViewControllerDelegate` documentation.
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/TopBannerViewController.swift
  Sources/MapboxNavigation/TopBannerViewControllerDelegate.swift
Labels: UI, drop-in

#3639 Use public token on CircleCI
  .circleci/config.yml
Labels: build

#3637 Add debug common sdk script
  scripts/debug_common_sdk.sh
Labels: op-ex

#3618 Improve Example app to no zoom animation after active navigation
  Example/ViewController.swift
Labels: improvement

#3454 Rerouting avoiding Dangerous Maneuvers
  CHANGELOG.md
  Example/ViewController.swift
  Sources/MapboxCoreNavigation/NavigationService.swift
  Sources/MapboxCoreNavigation/NavigationServiceDelegate.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/RouteProgress.swift
  Sources/MapboxCoreNavigation/Router.swift
  Sources/MapboxCoreNavigation/RouterDelegate.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewControllerDelegate.swift
  Sources/TestHelper/DirectionsSpy.swift
  Sources/TestHelper/NavigationServiceTestDoubles.swift
  Sources/TestHelper/RouterDelegateSpy.swift
  Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
  Tests/MapboxCoreNavigationTests/RouteControllerTests.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: platform parity, improvement, v2.x

#3646 Remove `maxPitch` parameter, which is not used.
  Sources/MapboxNavigation/NavigationViewportDataSource.swift
Labels: op-ex

#3650 Update RouteVoiceController doc
  Sources/MapboxNavigation/RouteVoiceController.swift
Labels: documentation

#3659 v2.1.1
  CHANGELOG.md
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
Labels: build

#3662 Extract MapboxNavigationNative_Private usage into type alias
  Sources/MapboxCoreNavigation/MapboxRoutingProvider.swift
Labels: build, release blocker

#3656 Fix debug scripts
  scripts/debug_common_sdk.sh
  scripts/debug_navigation_native.sh
Labels: op-ex

#3644 Use a snapped location instead of a raw location during off-route detection process.
  CHANGELOG.md
  Sources/MapboxCoreNavigation/RouteController.swift
Labels: bug, Core

#3651 Add documentation for `InstructionsBannerViewDelegate`.
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/InstructionsBannerView.swift
  Sources/MapboxNavigation/InstructionsBannerViewDelegate.swift
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  docs/jazzy.yml
Labels: UI, drop-in

#3581 Add ability to use custom rounding mechanism
  Sources/MapboxCoreNavigation/DistanceFormatter.swift
Labels: CarPlay, improvement

#3665 Upgrade to MapboxMaps v10.2
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  Package.resolved
  Package.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: build

#3666 Release v2.2.0-beta.1
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build
