Repository mapbox/mapbox-navigation-ios, pull requests merged in 2021-04, with the labels that each got.

#2905 Metrics config fix
  .circleci/config.yml
Labels: - bug, - build, CI

#2897 Refactor StyleManager's appearance refresh logic to no longer use UIWindow loop
  CHANGELOG.md
  Sources/MapboxNavigation/StyleManager.swift
Labels: - bug, - refactor

#2909 Fix route selection regression and annotation selection
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: - bug, UI

#2882 Add more turn lane configurations
  CHANGELOG.md
  Sources/MapboxNavigation/LaneView.swift
  Sources/MapboxNavigation/LanesStyleKit.swift
  Tests/MapboxNavigationTests/LaneViewTests.swift
Labels: - bug, - refactor, topic: instructions

#2832 Implement support for CPTemplateApplicationSceneDelegate UIScene-based CarPlay on iOS 13 and above
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  Example/AppDelegate.swift
  Example/FavoritesList.swift
  Example/Info.plist
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/CPMapTemplate.swift
  Sources/MapboxNavigation/CPTrip.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayManagerDelegate.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/CarPlaySearchController+CPSearchTemplateDelegate.swift
  Sources/MapboxNavigation/CarPlaySearchController.swift
  Sources/MapboxNavigation/CongestionLevel.swift
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/NightStyle.swift
  Sources/MapboxNavigation/RecentItem.swift
  Sources/MapboxNavigation/UIScreen.swift
  Sources/MapboxNavigation/VisualInstruction.swift
  Tests/MapboxNavigationTests/CPMapTemplateTests.swift
  Tests/MapboxNavigationTests/CarPlayManagerTests.swift
Labels: - feature, CarPlay

#2915 Fix RouteMapViewController deallocation issue.
  Sources/MapboxNavigation/RouteMapViewController.swift
Labels: - bug

#2899 Avoid disabling telemetry events after starting navigation
  Sources/MapboxCoreNavigation/NavigationEventsManager.swift
Labels: iOS, topic: telemetry

#2916 Add history methods to PassiveLocationDataSource
  Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
Labels: - feature, quick fix, topic: location

#2917 Minor tail work to add missing documentation for CarPlay changes in last commit
  CHANGELOG.md
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example-CarPlay.xcscheme
  Sources/MapboxNavigation/CarPlayManagerDelegate.swift
Labels: CarPlay, documentation, topic: documentation

#2918 Fix MapboxCoreNavigationTests failures with reset of navigator before location update each time
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxCoreNavigation.xcscheme
  Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
  Tests/MapboxCoreNavigationTests/PassiveLocationDataSourceTests.swift
Labels: - bug, - tests

#2826 Navigation camera viewport API.
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  Example/CustomViewController.swift
  Example/ViewController+FreeDrive.swift
  Example/ViewController+GuidanceCards.swift
  Example/ViewController.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Bench.xcscheme
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example-CarPlay.xcscheme
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxCoreNavigation.xcscheme
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxNavigation.xcscheme
  Sources/MapboxNavigation/Array.swift
  Sources/MapboxNavigation/BoundingBox.swift
  Sources/MapboxNavigation/CLLocationDirection.swift
  Sources/MapboxNavigation/CameraOptions.swift
  Sources/MapboxNavigation/CameraStateTransition.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/Collection.swift
  Sources/MapboxNavigation/MapView.swift
  Sources/MapboxNavigation/NavigationCamera.swift
  Sources/MapboxNavigation/NavigationCameraConstants.swift
  Sources/MapboxNavigation/NavigationCameraDebugView.swift
  Sources/MapboxNavigation/NavigationCameraState.swift
  Sources/MapboxNavigation/NavigationCameraStateTransition.swift
  Sources/MapboxNavigation/NavigationCameraType.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationMapViewDelegate.swift
  Sources/MapboxNavigation/NavigationView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewportDataSource.swift
  Sources/MapboxNavigation/Route.swift
  Sources/MapboxNavigation/RouteMapViewController.swift
  Sources/MapboxNavigation/UIEdgeInsets.swift
  Sources/MapboxNavigation/UserCourseView.swift
  Sources/MapboxNavigation/UserHaloCourseView.swift
  Sources/MapboxNavigation/ViewportDataSource.swift
  Sources/MapboxNavigation/ViewportDataSourceType.swift
  docs/jazzy.yml
Labels: - feature, - refactor

#2932 v2.0.0 beta.5
  Bench/Info.plist
  BenchTests/Info.plist
  Cartfile
  Cartfile.resolved
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
  README.md
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxNavigation/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  Tests/TestHelper/Info.plist
  custom-navigation.md
Labels: - build

#2924 Fix MapboxCoreNavigation bundle when building with SPM
  MapboxNavigation.xcodeproj/project.pbxproj
  Package.swift
  Sources/MapboxCoreNavigation/BundleAdditions.swift
  Sources/MapboxCoreNavigation/EventDetails.swift
  Sources/MapboxCoreNavigation/LegacyRouteController.swift
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxCoreNavigation/NavigationEventsManager.swift
  Sources/MapboxCoreNavigation/NavigationService.swift
  Sources/MapboxCoreNavigation/URLSession.swift
  Sources/MapboxNavigation/MBXInfo.plist
  Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  scripts/update-version.sh
Labels: - bug, release blocker, topic: telemetry

#2927 Add integration test for Swift Package Manager
  .circleci/config.yml
  Tests/SPMTest/SPMTest.xcodeproj/project.pbxproj
  Tests/SPMTest/SPMTest.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Tests/SPMTest/SPMTest.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Tests/SPMTest/SPMTest/AppDelegate.swift
  Tests/SPMTest/SPMTest/Assets.xcassets/AccentColor.colorset/Contents.json
  Tests/SPMTest/SPMTest/Assets.xcassets/AppIcon.appiconset/Contents.json
  Tests/SPMTest/SPMTest/Assets.xcassets/Contents.json
  Tests/SPMTest/SPMTest/Base.lproj/LaunchScreen.storyboard
  Tests/SPMTest/SPMTest/Base.lproj/Main.storyboard
  Tests/SPMTest/SPMTest/Info.plist
  Tests/SPMTest/SPMTest/SceneDelegate.swift
  Tests/SPMTest/SPMTest/ViewController.swift
  scripts/build_spm_integration_test.sh
Labels: - build, - tests

#2940 Rename CLLocationDirection.swift to CLLocationDirection+Camera.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/CLLocationDirection+Camera.swift
Labels: - build

#2930 Upgrade to Mapbox Maps v10.0.0-beta.18, Mapbox Navigation Native v48.0.4 and Mapbox Common v11.0.2.
  .circleci/config.yml
  BenchTests/BenchTests.swift
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/CustomViewController.swift
  Example/ViewController+FreeDrive.swift
  Example/ViewController+GuidanceCards.swift
  Example/ViewController.swift
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/Accounts.swift
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/Directions.swift
  Sources/MapboxCoreNavigation/EHorizon/ElectronicHorizonEdgeMetadata.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadGraph.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectsStore.swift
  Sources/MapboxCoreNavigation/Navigator.swift
  Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
  Sources/MapboxCoreNavigation/PredictiveCacheManager.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/SkuTokenProvider.swift
  Sources/MapboxNavigation/CameraOptions.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/CredentialsManager.swift
  Sources/MapboxNavigation/Double.swift
  Sources/MapboxNavigation/MapView.swift
  Sources/MapboxNavigation/MapboxMapsStyle.swift
  Sources/MapboxNavigation/NavigationCameraStateTransition.swift
  Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewportDataSource.swift
  Sources/MapboxNavigation/RouteMapViewController.swift
  Sources/TestHelper/NavigationPlotter.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: - build, blocked

#2931 Fix the simulate route options in Example
  Example/ViewController.swift
Labels: - bug, topic: location

#2950 v2.0.0-beta.6
  Bench/Info.plist
  BenchTests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: - build

#2902 RouteMapViewController refactor
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/ArrivalController.swift
  Sources/MapboxNavigation/CameraController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/MapView.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationMapViewDelegate.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewData.swift
  Sources/MapboxNavigation/OrnamentsController.swift
  Sources/MapboxNavigation/RouteLineController.swift
  Sources/MapboxNavigation/RouteMapViewController.swift
  Sources/MapboxNavigation/Style.swift
  Sources/MapboxNavigation/VectorSource.swift
  Sources/MapboxNavigation/WayNameView.swift
Labels: - refactor, Core

#2894 Add archiving step on Circle CI
  .circleci/config.yml
Labels: - build

#2825 Add ability to override main and alternative route lines.
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/Array.swift
  Sources/MapboxNavigation/Constants.swift
  Sources/MapboxNavigation/MapView.swift
  Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationMapViewDelegate.swift
  Sources/MapboxNavigation/NavigationMapViewIdentifiers.swift
  Sources/MapboxNavigation/NavigationViewControllerDelegate.swift
  Sources/MapboxNavigation/Route.swift
  Sources/MapboxNavigation/RouteLineType.swift
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
Labels: - refactor, UI

#2949 Remove `ElectronicHorizon` struct
  CHANGELOG.md
  Example/ViewController+FreeDrive.swift
  Example/ViewController.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/CoreConstants.swift
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/EHorizon/ElectronicHorizon.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadGraph.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadGraphEdge.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadGraphEdgeMetadata.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadGraphPath.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadGraphPosition.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectsStore.swift
Labels: - refactor

#2961 Added delegate, which is called after adding final destination PointAnnotation.
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationMapViewDelegate.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewControllerDelegate.swift
Labels: UI

#2963 Active Guidance crash
  Sources/MapboxNavigation/NavigationViewController.swift
Labels: - bug, - crash, - refactor, release blocker

#2955 Exposing TileStores
  CHANGELOG.md
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: iOS

#2833 Add the ability to show specific route leg with color overriding
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/Route.swift
Labels: UI, iOS

#2966 Fix issues with calling NavigationViewControllerDelegate methods.
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewControllerDelegate.swift
  Sources/MapboxNavigation/NavigationViewData.swift
  Sources/MapboxNavigation/OrnamentsController.swift
  Sources/MapboxNavigation/RouteLineController.swift
Labels: - bug, UI

#2942 Highlight lanes based on active direction
  CHANGELOG.md
  Sources/MapboxNavigation/LanesView.swift
  Sources/MapboxNavigation/VisualInstruction.swift
Labels: - feature, UI
