Repository mapbox/mapbox-navigation-ios, pull requests merged in 2021-03, with the labels that each got.

#2843 Fix the EndOfRouteViewController crush
  Sources/MapboxNavigation/Resources/Base.lproj/Navigation.storyboard
Labels: - bug, - crash, UI, iOS

#2724 Right to Left Language instruction card swipe bug
  CHANGELOG.md
  Sources/MapboxNavigation/InstructionsCardViewController.swift
Labels: - bug, UI, iOS, topic: instructions, topic: localization

#2844 v1.3.0-beta.1
  Bench/Info.plist
  BenchTests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxNavigation/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  Tests/TestHelper/Info.plist
  custom-navigation.md
Labels: - build

#2823 Navigator Tiles management
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/Navigator.swift
  Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxNavigation/PassiveLocationManager.swift
Labels: - refactor, iOS, ✓ ready for review

#2830 Predictive Caching Integration
  CHANGELOG.md
  Example/ViewController.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/PredictiveCacheManager.swift
  Sources/MapboxCoreNavigation/PredictiveCacheOptions.swift
  Sources/MapboxNavigation/MapView.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationOptions.swift
  Sources/MapboxNavigation/NavigationViewController.swift
Labels: - feature, High Priority, iOS, platform parity

#2847 Speed limit view updates during free-driving
  Example/ViewController+FreeDrive.swift
  Example/ViewController.swift
  Sources/MapboxCoreNavigation/CoreConstants.swift
  Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
Labels: - feature, Core, iOS

#2837 Remove MGLMapboxAccessToken usage.
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
  Tests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: - build

#2827 Add ability to port building highlighting feature
  CHANGELOG.md
  Example/ViewController.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/Expression.swift
  Sources/MapboxNavigation/Feature.swift
  Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
Labels: - feature, UI, iOS

#2854 Update to Mapbox Geocoder 0.14.0.
  MapboxNavigation.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
Labels: - build, dependency management, topic: search

#2848 Onboard Routing
  CHANGELOG.md
  Example/ViewController.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/Directions.swift
  Sources/MapboxCoreNavigation/Router.swift
  Sources/MapboxNavigation/CarPlayManager.swift
Labels: - feature, Core, iOS, platform parity

#2853 Merge v1.3 to v2.0 except route duration annotations
  CHANGELOG.md
Labels: - chore

#2855 Fix partially visible maneuver problem
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: UI, iOS

#2856 v2.0.0-beta.1
  Bench/Info.plist
  BenchTests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxNavigation/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  Tests/TestHelper/Info.plist
  custom-navigation.md
Labels: - build

#2859 Fix the End-of-route feedback view
  Sources/MapboxNavigation/Resources/Base.lproj/Navigation.storyboard
Labels: - bug, UI

#2747 Allow the use of multiple status banners
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/NavigationComponent.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/StatusView.swift
  Sources/MapboxNavigation/TopBannerViewController.swift
  Tests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  Tests/MapboxNavigationTests/StatusViewTests.swift
Labels: - refactor, UI, iOS

#2863 Fix Example build on CI
  .circleci/config.yml
  MapboxNavigation.xcodeproj/project.pbxproj
Labels: - build

#2861 Remove TestHelper’s dependency on MapboxNavigation
  MapboxNavigation.xcodeproj/project.pbxproj
  Tests/MapboxCoreNavigationTests/RouteControllerTests.swift
  Tests/MapboxCoreNavigationTests/SimulatedLocationManagerTests.swift
Labels: - build, - tests, Core

#2834 Electronic horizon
  CHANGELOG.md
  Example/ViewController+FreeDrive.swift
  Example/ViewController.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/CoreConstants.swift
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/EHorizon/ElectronicHorizon.swift
  Sources/MapboxCoreNavigation/EHorizon/ElectronicHorizonEdge.swift
  Sources/MapboxCoreNavigation/EHorizon/ElectronicHorizonEdgeMetadata.swift
  Sources/MapboxCoreNavigation/EHorizon/ElectronicHorizonOptions.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadGraph.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadGraphPath.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadGraphPosition.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadName.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectDistanceInfo.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectEdgeLocation.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectLocation.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectMetadata.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectType.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectsStore.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectsStoreDelegate.swift
  Sources/MapboxCoreNavigation/MapboxStreetsRoadClass.swift
  Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
  Sources/MapboxCoreNavigation/RouteController.swift
Labels: - feature, topic: location

#2858 Support Driving Side flag
  Sources/MapboxCoreNavigation/EHorizon/ElectronicHorizonEdgeMetadata.swift
Labels: quick fix, topic: location, ✓ ready for review

#2872 Fix destination annotation incorrectly placed below route line
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: - bug, UI

#2875 v2.0.0-beta.2
  Bench/Info.plist
  BenchTests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxNavigation/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  Tests/TestHelper/Info.plist
  custom-navigation.md
Labels: - build

#2874 Fix MapboxCoreNavigationTests and TestHelper build errors
  MapboxNavigation.xcodeproj/project.pbxproj
  Tests/MapboxCoreNavigationTests/PassiveLocationDataSourceTests.swift
  Tests/TestHelper/CoreLocation.swift
Labels: - build, - tests

#2871 Don't trigger viewDidLoad in NavigationViewController.init
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationViewController.swift
Labels: - bug

#2877 Remove waypoint styling delegate methods.
  Example/ViewController.swift
Labels: - chore

#2880 Fix memory leak when showing shield icon.
  Sources/MapboxNavigation/RouteMapViewController.swift
Labels: - bug

#2881 Fix automatic day/night switching
  CHANGELOG.md
  Sources/MapboxNavigation/StyleManager.swift
  Sources/MapboxNavigation/VanishingRouteLine.swift
Labels: - bug

#2878 CI metrics hook for V2 branch
  .circleci/config.yml
Labels: CI, iOS, ✓ ready for review

#2896 Fix crash when switching between day / night modes
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: - bug

#2884 Upgrade to MapboxMaps v10.0.0-beta.16, MapboxNavigationNative v47.0.0
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/CustomViewController.swift
  Example/ViewController.swift
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/EHorizon/ElectronicHorizonEdgeMetadata.swift
  Sources/MapboxCoreNavigation/PredictiveCacheManager.swift
  Sources/MapboxCoreNavigation/RouteState.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/MapView.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/RouteMapViewController.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Extensions/RouteStateTests.swift
Labels: - build, UI

#2898 v2.0.0-beta.3
  Bench/Info.plist
  BenchTests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxNavigation/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  Tests/TestHelper/Info.plist
  custom-navigation.md
Labels: - build

#2886 Integrate Mapbox Maps CameraView and CameraAnimator.
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/CustomViewController.swift
  Example/CustomViewportDataSource.swift
  Example/NavigationCameraDebugView.swift
  Example/ViewController+FreeDrive.swift
  Example/ViewController.swift
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Bench.xcscheme
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example-CarPlay.xcscheme
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxCoreNavigation.xcscheme
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxNavigation.xcscheme
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/EHorizon/ElectronicHorizonEdgeMetadata.swift
  Sources/MapboxCoreNavigation/PredictiveCacheManager.swift
  Sources/MapboxCoreNavigation/RouteState.swift
  Sources/MapboxNavigation/CameraStateTransition.swift
  Sources/MapboxNavigation/CameraView.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/MapView.swift
  Sources/MapboxNavigation/NavigationCamera.swift
  Sources/MapboxNavigation/NavigationCameraConstants.swift
  Sources/MapboxNavigation/NavigationCameraStateTransition.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewportDataSource.swift
  Sources/MapboxNavigation/RouteMapViewController.swift
  Sources/MapboxNavigation/ViewportDataSource.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Extensions/RouteStateTests.swift
Labels: - feature, UI

#2901 Fix MapView annotation selection not working
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: - bug, UI

#2876 Allow the Navigator set access token other than in Info.plist
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/BundleAdditions.swift
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/LegacyRouteController.swift
  Sources/MapboxCoreNavigation/NavigationService.swift
  Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
  Sources/MapboxCoreNavigation/PredictiveCacheManager.swift
  Sources/MapboxCoreNavigation/PredictiveCacheOptions.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  Tests/MapboxCoreNavigationTests/NavigationEventsManagerTests.swift
  Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
  Tests/MapboxCoreNavigationTests/RouteControllerTests.swift
  Tests/MapboxCoreNavigationTests/SimulatedLocationManagerTests.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
  Tests/TestHelper/CoreLocation.swift
  Tests/TestHelper/Fixture.swift
Labels: - bug, - build, - tests
