Repository mapbox/mapbox-navigation-ios, pull requests merged in 2021-08, with the labels that each got.

#3209 Do not show traffic by default in `CarPlayMapViewController`.
  Sources/MapboxNavigation/CarPlayMapViewController.swift
Labels: - bug, CarPlay, UI

#3162 Update to Mapbox Maps `v10.0.0-rc.5` and Navigation Native `v60.0.0`.
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/EHorizon/DistancedRoadObject.swift
  Sources/MapboxCoreNavigation/EHorizon/OpenLROrientation.swift
  Sources/MapboxCoreNavigation/EHorizon/OpenLRSideOfRoad.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectType.swift
  Sources/MapboxCoreNavigation/Incident.swift
  Sources/MapboxCoreNavigation/MapboxStreetsRoadClass.swift
  Sources/MapboxCoreNavigation/PassiveLocationManager.swift
  Sources/MapboxCoreNavigation/RestStop.swift
  Sources/MapboxCoreNavigation/RouteState.swift
  Sources/MapboxCoreNavigation/TollCollection.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxNavigationTests/NavigationCameraTests.swift
Labels: - build

#3205 Fix route line visibility.
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/RouteLineController.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: - bug

#3217 GenericRouteShield caching
  CHANGELOG.md
  Sources/MapboxNavigation/GenericRouteShield.swift
Labels: - bug, quick fix, user: support

#3182 RouteResponse usage refactoring
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/AppDelegate+CarPlay.swift
  Example/CustomViewController.swift
  Example/ViewController.swift
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.swift
  README.md
  Sources/MapboxCoreNavigation/ActiveNavigationEventDetails.swift
  Sources/MapboxCoreNavigation/LegacyRouteController.swift
  Sources/MapboxCoreNavigation/NavigationEventsManager.swift
  Sources/MapboxCoreNavigation/NavigationService.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/RouteProgress.swift
  Sources/MapboxCoreNavigation/Router.swift
  Sources/MapboxCoreNavigation/SessionState.swift
  Sources/MapboxNavigation/CPTrip.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayManagerDelegate.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/TestHelper/Fixture.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/LocationTests.swift
  Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  Tests/MapboxCoreNavigationTests/MapboxNavigationServiceSpec.swift
  Tests/MapboxCoreNavigationTests/NavigationEventsManagerTests.swift
  Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
  Tests/MapboxCoreNavigationTests/RouteControllerTests.swift
  Tests/MapboxCoreNavigationTests/RouteProgressTests.swift
  Tests/MapboxCoreNavigationTests/TunnelAuthorityTests.swift
  Tests/MapboxNavigationTests/CarPlayManagerTests.swift
  Tests/MapboxNavigationTests/CarPlayNavigationViewControllerTests.swift
  Tests/MapboxNavigationTests/GuidanceCardsSnapshotTests.swift
  Tests/MapboxNavigationTests/InstructionsCardCollectionTests.swift
  Tests/MapboxNavigationTests/LeaksSpec.swift
  Tests/MapboxNavigationTests/NavigationCameraTests.swift
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
  Tests/MapboxNavigationTests/SpeechSynthesizersControllerTests.swift
  Tests/MapboxNavigationTests/StepsViewControllerTests.swift
  Tests/MapboxNavigationTests/Support/CarPlayUtils.swift
  docs/cover.md
Labels: - refactor, backwards-incompatible

#3222 Fix retain cycle causing crash in RouteOverlayController on NavigationMapView reuse
  CHANGELOG.md
  Sources/MapboxNavigation/RouteLineController.swift
Labels: - crash

#3223 Make `NavigationService` optional.
  Sources/MapboxNavigation/CarPlayManagerDelegate.swift
  Tests/MapboxNavigationTests/CarPlayManagerTests.swift
  Tests/MapboxNavigationTests/Support/CarPlayUtils.swift
Labels: - bug, CarPlay

#3201 Improve the performance of vanishing route line feature
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/Route.swift
  Sources/MapboxNavigation/RouteLineController.swift
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
Labels: - performance, - refactor, UI

#3226 Reorganize `MapboxNavigationTests` target project structure to match groups in `MapboxNavigation`.
  MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example-CarPlay.xcscheme
  MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
  MapboxNavigation.xcodeproj/project.pbxproj
  Package.swift
  Tests/MapboxNavigationTests/CGSize.swift
  Tests/MapboxNavigationTests/CarPlayUtils.swift
  Tests/MapboxNavigationTests/Constants.swift
  Tests/MapboxNavigationTests/ImageDownloadOperationSpy.swift
  Tests/MapboxNavigationTests/ImageLoadingURLProtocolSpy.swift
  Tests/MapboxNavigationTests/LaneSnapshotTests.swift
  Tests/MapboxNavigationTests/LeaksSpec.swift
  Tests/MapboxNavigationTests/ManeuverArrowSnapshotTests.swift
  Tests/MapboxNavigationTests/ManeuverViewSnapshotTests.swift
  Tests/MapboxNavigationTests/MapboxNavigationTests-Bridging.h
  Tests/MapboxNavigationTests/NavigationViewControllerTestDoubles.swift
  Tests/MapboxNavigationTests/Snapshot++.swift
  Tests/MapboxNavigationTests/Support/Utils.swift
  Tests/MapboxNavigationTests/Support/XCTestCase++.swift
  Tests/MapboxNavigationTests/TokenTestViewController.swift
  Tests/MapboxNavigationTests/UIViewController.swift
  Tests/MapboxNavigationTests/XCTestCase.swift
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/InstructionsBannerViewSnapshotTests/testGenericShields.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/LaneSnapshotTests/verifyAllLanes-size.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/LaneSnapshotTests/verifyAllLanes-size.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/ManeuverArrowSnapshotTests/testManeuverArrowHandlesWaypointsCorrectly.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/ManeuverViewSnapshotTests/testArrive.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/ManeuverViewSnapshotTests/testArriveNone.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/ManeuverViewSnapshotTests/testLeftUTurn.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/ManeuverViewSnapshotTests/testMergeRight.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/ManeuverViewSnapshotTests/testRightUTurn.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/ManeuverViewSnapshotTests/testRoundabout.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/ManeuverViewSnapshotTests/testRoundaboutTurnLeft.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/ManeuverViewSnapshotTests/testStraightRoundabout.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/ManeuverViewSnapshotTests/testTurnRight.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/ManeuverViewSnapshotTests/testTurnSlightRight.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/CarPlayCompassViewSnapshotTests/testCarPlayCompassView.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/CarPlayCompassViewSnapshotTests/testCarPlayCompassView.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/GuidanceCardsSnapshotTests/testLanesManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/GuidanceCardsSnapshotTests/testRegularManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/GuidanceCardsSnapshotTests/testTertiaryManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/InstructionsBannerViewSnapshotTests/testGenericShields.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/InstructionsBannerViewSnapshotTests/testInstructionsAndNextInstructions.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/InstructionsBannerViewSnapshotTests/testPrimaryShieldAndSecondary.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/LaneSnapshotTests/verifyAllLanes-size.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/LaneSnapshotTests/verifyAllLanes-size.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/LaneTests/verifyAllLanes-size.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/LaneTests/verifyAllLanes-size.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/ManeuverArrowSnapshotTests/testManeuverArrowHandlesWaypointsCorrectly.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/ManeuverViewSnapshotTests/testArrive.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/ManeuverViewSnapshotTests/testArriveNone.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/ManeuverViewSnapshotTests/testLeftUTurn.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/ManeuverViewSnapshotTests/testMergeRight.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/ManeuverViewSnapshotTests/testRightUTurn.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/ManeuverViewSnapshotTests/testRoundabout.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/ManeuverViewSnapshotTests/testRoundaboutTurnLeft.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/ManeuverViewSnapshotTests/testStraightRoundabout.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/ManeuverViewSnapshotTests/testTurnRight.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/ManeuverViewSnapshotTests/testTurnSlightRight.1.png
Labels: - refactor, - tests

#3229 Fix route preview on CarPlay.
  Sources/MapboxNavigation/CarPlayManager.swift
Labels: - bug, UI, CarPlay

#3235 Fix buggy default MapboxNavigationService creation if custom one is provided
  Sources/MapboxNavigation/NavigationViewController.swift
Labels: - bug

#3244 Allow the resume button to stop preview for top banner and guidance cards
  Sources/MapboxNavigation/CameraController.swift
Labels: - bug, UI

#3248 Update Mapbox Navigation dependencies.
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectMatcher.swift
  Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
Labels: - build

#3238 Fix missing feedback subtype descriptions
  CHANGELOG.md
  Sources/MapboxCoreNavigation/Feedback.swift
Labels: - bug

#3250 Add subgraph case to RoadObjectLocation
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectLocation.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadSubgraphEdge.swift
Labels: - bug, iOS

#3253 Update source localization files
  Example/en.lproj/Localizable.strings
  Sources/MapboxCoreNavigation/Resources/en.lproj/Localizable.strings
Labels: topic: localization, - chore

#3218 CarPlay vanishing route line
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: - bug, UI

#3242 Add `NavigationGeocodedPlacemarkTests` tests.
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/CarPlayTestHelper/CPMapTemplate+MBTestable.m
  Sources/MapboxNavigation/NavigationGeocodedPlacemark.swift
  Tests/MapboxNavigationTests/NavigationGeocodedPlacemarkTests.swift
Labels: - tests, CarPlay

#3247 Add automated tests for `RecentItem`.
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/RecentItem.swift
  Tests/MapboxNavigationTests/RecentItemTests.swift
Labels: - tests, CarPlay

#3245 Introduce IdleTimerManager to streamline idle timer management and fix bugs
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/OnMainQueue.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayManagerDelegate.swift
  Sources/MapboxNavigation/IdleTimerManager.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Tests/MapboxCoreNavigationTests/IdleTimerManagerTests.swift
Labels: - bug

#3264 Add `testRunningAnimators`. Fix crash in `NavigationCameraStateTransition.stopAnimators()`.
  Sources/MapboxNavigation/NavigationCameraStateTransition.swift
  Tests/MapboxNavigationTests/NavigationCameraTests.swift
Labels: - bug, - crash, topic: camera

#3262 Fix failing `testRecentItemsSavingAndLoading`.
  Sources/MapboxNavigation/RecentItem.swift
  Tests/MapboxNavigationTests/RecentItemTests.swift
Labels: - bug, - tests

#3258 Remove `Bench` and `BenchTests` targets.
  Bench/AppDelegate.swift
  Bench/Assets.xcassets/AppIcon.appiconset/Contents.json
  Bench/Assets.xcassets/Contents.json
  Bench/Base.lproj/LaunchScreen.storyboard
  Bench/BenchViewController.swift
  Bench/ControlRouteViewController.swift
  Bench/Info.plist
  BenchTests/BenchTests.swift
  BenchTests/Info.plist
  BenchTests/SpeechSynthesizerSpy.swift
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Bench.xcscheme
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/TestHelper/Fixtures/DCA-Arboretum.trace.json
  Sources/TestHelper/Fixtures/PipeFittersUnion-FourSeasonsBoston.trace.json
  Sources/TestHelper/TestCase.swift
Labels: - build

#3257 Let current road label named from navigation status instead of Electronic Horizon
  CHANGELOG.md
  Sources/MapboxCoreNavigation/CoreConstants.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxNavigation/OrnamentsController.swift
Labels: - refactor, UI

#3266 Fix the tail work of the road name label based on status.
  CHANGELOG.md
  Sources/MapboxCoreNavigation/CoreConstants.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxNavigation/OrnamentsController.swift
Labels: - bug

#3265 Disable filtering by navigation status origin
  CHANGELOG.md
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
Labels: - bug

#3195 Rerouting after arrival
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewControllerDelegate.swift
  Sources/TestHelper/DirectionsSpy.swift
  Sources/TestHelper/Fixture.swift
  Sources/TestHelper/RouterDelegateSpy.swift
  Tests/MapboxCoreNavigationTests/RouteControllerTests.swift
Labels: - bug

#3215 New properties in NavigationSettings
  CHANGELOG.md
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/LegacyRouteController.swift
  Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
  Sources/MapboxCoreNavigation/NavigationService.swift
  Sources/MapboxCoreNavigation/NavigationSettings.swift
  Sources/MapboxCoreNavigation/PassiveLocationManager.swift
  Sources/MapboxCoreNavigation/PredictiveCacheManager.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/Router.swift
  Sources/MapboxCoreNavigation/TileStore.swift
  Sources/MapboxCoreNavigation/TilesetDescriptorFactory.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationOptions.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/TestHelper/TestCase.swift
  Tests/MapboxCoreNavigationTests/MapboxNavigationServiceSpec.swift
  Tests/MapboxCoreNavigationTests/NativeHandlersFactoryTests.swift
  Tests/MapboxCoreNavigationTests/NavigationEventsManagerTests.swift
  Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
  Tests/MapboxCoreNavigationTests/PassiveLocationManagerTests.swift
  Tests/MapboxCoreNavigationTests/RouteControllerTests.swift
  Tests/MapboxCoreNavigationTests/TilesetDescriptorFactoryTests.swift
  Tests/MapboxNavigationTests/CarPlayManagerTests.swift
  Tests/MapboxNavigationTests/CarPlayNavigationViewControllerTests.swift
  Tests/MapboxNavigationTests/CarPlayUtils.swift
  Tests/MapboxNavigationTests/InstructionsCardCollectionTests.swift
  Tests/MapboxNavigationTests/LeaksSpec.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
  Tests/MapboxNavigationTests/SpeechSynthesizersControllerTests.swift
  Tests/MapboxNavigationTests/StepsViewControllerTests.swift
Labels: release blocker, backwards-incompatible

#3273 Do not use bearing when navigation camera transitions to the overview mode.
  Sources/MapboxNavigation/NavigationViewportDataSource.swift
Labels: topic: camera, UI

#3255 To improve the vanishing route line when rerouting happens
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/RouteLineController.swift
Labels: - bug, UI

#3275 Fix navigation camera transition to overview mode.
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/Array.swift
  Sources/MapboxNavigation/NavigationViewportDataSource.swift
  Tests/MapboxNavigationTests/ArrayTests.swift
Labels: - bug, topic: camera, UI

#3284 Replace SHORT_VERSION in generated docs.
  scripts/document.sh
Labels: documentation

#3219 CarPlay refactoring and bugfixing.
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayManagerDelegate.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/MapTemplateProvider.swift
  Sources/MapboxNavigation/MapTemplateProviderDelegate.swift
Labels: UI, CarPlay

#3283 Improve navigation camera transition.
  Sources/MapboxNavigation/NavigationCameraStateTransition.swift
  Sources/MapboxNavigation/UserCourseView.swift
Labels: topic: camera, UI

#3311 Quick fix the refresh shows all route line during navigation.
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: quick fix
