Repository mapbox/mapbox-navigation-ios, pull requests merged in 2021-07, with the labels that each got.

#3131 Add slack notifications for failed builds on main branch
  .circleci/config.yml
Labels: - build

#3118 Restore some tests
  MapboxNavigation.xcodeproj/project.pbxproj
  Package.swift
  Sources/CarPlayTestHelper/CPMapTemplate+MBTestable.m
  Sources/CarPlayTestHelper/CPNavigationSessionFake.m
  Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
  Sources/TestHelper/XCTestCase++.swift
  Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
  Tests/MapboxNavigationTests/CarPlayManagerTests.swift
  Tests/MapboxNavigationTests/LeaksSpec.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
  Tests/MapboxNavigationTests/Support/AccessToken.swift
  Tests/MapboxNavigationTests/Support/XCTestCase++.swift
Labels: - tests

#3138 Fix some tests
  Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: - tests

#3140 Fix testGeneratingAnArrivalEvent test
  Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
Labels: - tests

#3139 Update to Mapbox Navigation Native `v55.0.0`.
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/Directions.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: - build

#3137 Change access level of styleManager in CarPlay
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Labels: - feature

#2999 Remove optional dependency on MapboxGeocoder.swift for search on CarPlay
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  Example/AppDelegate.swift
  Example/en.lproj/Localizable.strings
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/CarPlayActivity.swift
  Sources/MapboxNavigation/CarPlayCompassView.swift
  Sources/MapboxNavigation/CarPlayManagerDelegate.swift
  Sources/MapboxNavigation/CarPlaySearchController+CPSearchTemplateDelegate.swift
  Sources/MapboxNavigation/CarPlaySearchController.swift
  Sources/MapboxNavigation/CarPlaySearchControllerDelegate.swift
  Sources/MapboxNavigation/NavigationGeocodedPlacemark.swift
  Sources/MapboxNavigation/RecentItem.swift
  Sources/MapboxNavigation/Resources/ca.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/de.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/en.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/es.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/fr.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/hu.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/ja.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/pt-PT.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/ru.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/sv.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/tr.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/uk.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/vi.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/yo.lproj/Localizable.strings
  Tests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  Tests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/xcshareddata/xcschemes/PodInstall.xcscheme
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxNavigationTests/Support/CarPlayUtils.swift
  docs/jazzy.yml
Labels: - refactor, CarPlay, backwards-incompatible, topic: architecture, topic: search

#3142 Mapbox Navigation `v2.0.0-beta.16`.
  Bench/Info.plist
  BenchTests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: - build

#3123 Update the mapSDK puck in NavigationMapView with location course for bearing
  Example/ViewController+FreeDrive.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/RouteLineController.swift
Labels: - refactor, UI

#3144 A quick fix for the location update under non-simulation case
  Sources/MapboxNavigation/NavigationViewController.swift
Labels: - bug, topic: location

#3127 Improve performance of Array.boundingBoxPoints by 5x
  Sources/MapboxNavigation/Array.swift
  Tests/MapboxNavigationTests/ArrayTests.swift
Labels: - performance

#3055 Remove some redundant force unwraps
  CHANGELOG.md
  Sources/MapboxCoreNavigation/EventDetails.swift
  Sources/MapboxCoreNavigation/NavigationEventsManager.swift
  Sources/MapboxCoreNavigation/NavigationService.swift
  Sources/MapboxNavigation/CameraController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewData.swift
  Sources/MapboxNavigation/OrnamentsController.swift
  Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: - refactor, backwards-incompatible

#3149 Fix update-version.sh script
  scripts/update-version.sh
Labels: release blocker

#3150 Fix issue, which prevents from disabling traffic.
  Sources/MapboxNavigation/MapView.swift
Labels: - bug

#3153 Allow the hard stop of route line gradient
  CHANGELOG.md
  Sources/MapboxNavigation/Expression.swift
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: UI

#3158 S2ler/fix warnings
  Package.swift
  Sources/MapboxCoreNavigation/NavigationService.swift
  Sources/MapboxNavigation/CarPlaySearchControllerDelegate.swift
Labels: - chore

#3155 Add center distance and bearing change threshold before start the camera animation
  CHANGELOG.md
  Sources/MapboxNavigation/CameraStateTransition.swift
  Sources/MapboxNavigation/NavigationCamera.swift
  Sources/MapboxNavigation/NavigationCameraStateTransition.swift
  Sources/MapboxNavigation/Utils.swift
Labels: - performance, topic: camera

#3164 Fix getting latest descriptors
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
  Sources/MapboxCoreNavigation/TileStore.swift
  Sources/MapboxCoreNavigation/TilesetDescriptorFactory.swift
  Sources/TestHelper/AccessToken.swift
  Tests/MapboxCoreNavigationTests/TilesetDescriptorFactoryTests.swift
Labels: - bug

#3169 Remove `NavigationMapView.prepareForInterfaceBuilder()`.
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: UI

#3167 Reload `MapView` style when `StyleManager` changes its appearance.
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewController.swift
Labels: UI

#3163 Fix issue, which was causing problems with adding final destination `PointAnnotation`.
  Sources/MapboxNavigation/NavigationMapView.swift
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
Labels: - bug, UI

#3172 Fix `CameraOptions` update issues.
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationCameraStateTransition.swift
Labels: - bug, UI

#3179 Add `tileSetIdentifier` parameter usage.
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/MapView.swift
  Tests/MapboxNavigationTests/MapViewTests.swift
Labels: - bug, UI

#3183 Remove MapboxGeocoder.swift dependency
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  MapboxNavigation-Documentation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  Package.resolved
  Package.swift
  Sources/MapboxNavigation/NavigationGeocodedPlacemark.swift
  Sources/MapboxNavigation/RecentItem.swift
  Sources/TestHelper/CoreLocation.swift
  Tests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxNavigationTests/Support/CarPlayUtils.swift
  docs/cover.md
Labels: - build, - refactor, CarPlay, dependency management

#3068 Add `.pathShape(for:)` and `.position(for:)` methods to RoadGraph.
  Sources/MapboxCoreNavigation/EHorizon/RoadGraph.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadGraphPath.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadGraphPosition.swift
Labels: - feature, Core, topic: location

#3185 Remove `MapboxGeocoder` references.
  Cartfile.private
  Cartfile.resolved
  MapboxNavigation.xcodeproj/project.pbxproj
Labels: - build, CarPlay

#3186 NavigationMapView injection
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationOptions.swift
  Sources/MapboxNavigation/NavigationView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: - feature

#3159 Implement a new method to change route
  CHANGELOG.md
  Sources/MapboxCoreNavigation/LegacyRouteController.swift
  Sources/MapboxCoreNavigation/NavigationService.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/Router.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Tests/MapboxCoreNavigationTests/NavigationEventsManagerTests.swift
  Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
  docs/guides/Using Map Matching.md
Labels: - bug, backwards-incompatible, release blocker

#3189 Fix installation instructions in v1.x docsets
  1.0.0-rc.1/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.0.0-rc.1/index.html
  1.0.0-rc.2/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.0.0-rc.2/index.html
  1.0.0-rc.3/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.0.0-rc.3/index.html
  1.0.0-rc.4/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.0.0-rc.4/index.html
  1.0.0-rc.5/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.0.0-rc.5/index.html
  1.0.0/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.0.0/index.html
  1.1.0-alpha.1/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.1.0-alpha.1/index.html
  1.1.0-alpha.2/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.1.0-alpha.2/index.html
  1.1.0-beta.1/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.1.0-beta.1/index.html
  1.1.0-beta.2/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.1.0-beta.2/index.html
  1.1.0-rc.1/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.1.0-rc.1/index.html
  1.1.0/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.1.0/index.html
  1.2.0-alpha.1/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.2.0-alpha.1/index.html
  1.2.0-alpha.2/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.2.0-alpha.2/index.html
  1.2.0-alpha.3/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.2.0-alpha.3/index.html
  1.2.0-beta.1/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.2.0-beta.1/index.html
  1.2.0-rc.1/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.2.0-rc.1/index.html
  1.2.0/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.2.0/index.html
  1.2.1/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.2.1/index.html
  1.3.0-beta.1/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.3.0-beta.1/index.html
  1.3.0/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.3.0/index.html
  1.4.0/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.4.0/index.html
  1.4.1/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  1.4.1/index.html
  2.0.0-alpha.1/docsets/MapboxNavigation.docset/Contents/Resources/Documents/index.html
  2.0.0-alpha.1/index.html
Labels: documentation, topic: documentation

#3190 Add final destination annotation delegate method.
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayManagerDelegate.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayMapViewControllerDelegate.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewControllerDelegate.swift
  Sources/MapboxNavigation/NavigationMapViewDelegate.swift
  Sources/MapboxNavigation/NavigationViewControllerDelegate.swift
  Tests/MapboxNavigationTests/CarPlayManagerTests.swift
  Tests/MapboxNavigationTests/MapViewTests.swift
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
  docs/jazzy.yml
Labels: CarPlay, UI

#3007 Application allowed to include user metadata in feedback events
  CHANGELOG.md
  Sources/MapboxCoreNavigation/ActiveNavigationEventDetails.swift
  Sources/MapboxCoreNavigation/CoreFeedbackEvent.swift
  Sources/MapboxCoreNavigation/EventDetails.swift
  Sources/MapboxCoreNavigation/NavigationEventsManager.swift
  Sources/MapboxCoreNavigation/PassiveNavigationEventDetails.swift
Labels: Core, topic: telemetry

#3161 Fix feedback creation moment
  Sources/MapboxNavigation/FeedbackSubtypeViewController.swift
  Sources/MapboxNavigation/FeedbackViewController.swift
Labels: - bug, topic: telemetry

#3148 Cover Navigation Camera functionality with tests.
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/CameraStateTransition.swift
  Sources/MapboxNavigation/NavigationCamera.swift
  Sources/TestHelper/Fixtures/route-for-navigation-camera-bearing-smoothing.json
  Sources/TestHelper/Fixtures/route-for-navigation-camera.json
  Tests/MapboxNavigationTests/NavigationCameraTests.swift
Labels: - tests

#3199 Rename RouterDataSource.locationProvider to locationManagerType
  CHANGELOG.md
  Sources/MapboxCoreNavigation/ActiveNavigationEventDetails.swift
  Sources/MapboxCoreNavigation/LegacyRouteController.swift
  Sources/MapboxCoreNavigation/NavigationEventsManager.swift
  Sources/MapboxCoreNavigation/NavigationLocationManager.swift
  Sources/MapboxCoreNavigation/NavigationService.swift
  Sources/MapboxCoreNavigation/Router.swift
  Sources/TestHelper/NavigationServiceTestDoubles.swift
  Tests/MapboxCoreNavigationTests/RouteControllerTests.swift
Labels: - refactor, backwards-incompatible

#3197 Add `SpeedLimitView` to `CarPlayMapViewController`.
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayMapViewController.swift
Labels: CarPlay, UI

#3198 v2.0.0-beta.19
  Bench/Info.plist
  BenchTests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: - build

#2980 Fix Index out of bounds crash in RouteLegProgress.currentStep
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/RouteLegProgress.swift
Labels: - bug

#3177 Replace JSON with Expressions in route duration annotation styling.
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: - refactor, UI

#3211 v2.0.0-beta.20
  Bench/Info.plist
  BenchTests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: - build

#3208 Make `NavigationService` optional to be able to skip implementation of delegate method on client side.
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayManagerDelegate.swift
  Tests/MapboxNavigationTests/MapViewTests.swift
Labels: CarPlay, UI
