Repository mapbox/mapbox-navigation-ios, pull requests merged in 2021-10, with the labels that each got.

#3424 Make `CarPlayMapViewController` and `CarPlayNavigationViewController` subclassable.
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Labels: UI, CarPlay

#3429 Allow to completely hide `SpeedLimitView`.
  CHANGELOG.md
  Sources/MapboxNavigation/SpeedLimitView.swift
Labels: UI, CarPlay

#3425 Remove `Bundle.ensureSuggestedTileURLExists()`, `Bundle.suggestedTileURL` and `Bundle.suggestedTileURL(version:)`, which are no longer used.
  CHANGELOG.md
  Sources/MapboxCoreNavigation/BundleAdditions.swift
Labels: backwards incompatible

#3417 Extend ReplayLocationManager with new callbacks
  Sources/MapboxCoreNavigation/ReplayLocationManager.swift
Labels: op-ex

#3314 inTunnels simulation
  CHANGELOG.md
  Example/CustomViewController.swift
  Example/ViewController.swift
  Sources/MapboxCoreNavigation/NavigationService.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/NavigationOptions.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Tests/MapboxNavigationTests/CarPlayManagerTests.swift
Labels: feature

#3416 Fix the preview crash resulted from the table view scrolling quickly.
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/Route.swift
  Sources/MapboxNavigation/StepsViewController.swift
  Tests/MapboxNavigationTests/RouteTests.swift
Labels: UI, topic: stability

#3437 Use count instead of endIndex
  Sources/MapboxNavigation/InstructionsCardViewController.swift
Labels: op-ex, UI

#3442 Only allow the current guidance card be highlighted.
  CHANGELOG.md
  Sources/MapboxNavigation/InstructionsCardCell.swift
  Sources/MapboxNavigation/InstructionsCardContainerView.swift
  Sources/MapboxNavigation/InstructionsCardViewController.swift
Labels: bug, UI

#3537 v2.1.0-alpha.2
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build
