Repository mapbox/mapbox-navigation-ios, pull requests merged in 2021-06, with the labels that each got.

#3045 Rename RoadObjectsStore to RoadObjectStore
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectStore.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectsStoreDelegate.swift
  Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
  Sources/MapboxCoreNavigation/RouteController.swift
Labels: - refactor

#3029 Partially implement MapboxNavigationTests in SPM
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
  Sources/CarPlayTestHelper/CPBarButton+MBTestable.m
  Sources/CarPlayTestHelper/CPMapTemplate+MBTestable.mm
  Sources/CarPlayTestHelper/CPNavigationSessionFake.m
  Sources/CarPlayTestHelper/CarPlayTestHelper.h
  Sources/CarPlayTestHelper/FakeCPInterfaceController.m
  Sources/CarPlayTestHelper/Info.plist
  Sources/CarPlayTestHelper/include/CPBarButton+MBTestable.h
  Sources/CarPlayTestHelper/include/CPMapTemplate+MBTestable.h
  Sources/CarPlayTestHelper/include/CPNavigationSessionFake.h
  Sources/CarPlayTestHelper/include/FakeCPInterfaceController.h
  Sources/TestHelper/Fixture.swift
  Sources/TestHelper/Fixtures/Images.xcassets/80px-I-280.imageset/80px-I-280.svg.png
  Sources/TestHelper/Fixtures/Images.xcassets/80px-I-280.imageset/Contents.json
  Sources/TestHelper/Fixtures/Images.xcassets/Contents.json
  Sources/TestHelper/Fixtures/Images.xcassets/i-280.imageset/Contents.json
  Sources/TestHelper/Fixtures/Images.xcassets/i-280.imageset/i-280@3x.png
  Sources/TestHelper/Fixtures/Images.xcassets/us-101.imageset/Contents.json
  Sources/TestHelper/Fixtures/Images.xcassets/us-101.imageset/us-101@3x.png
  Sources/TestHelper/Fixtures/md5_crazy_strings.txt
  Sources/TestHelper/Fixtures/route-for-vanishing-route-line.json
  Sources/TestHelper/Fixtures/waypoint-after-turn.json
  Tests/MapboxNavigationTests/CarPlayCompassViewTests.swift
  Tests/MapboxNavigationTests/CarPlayManagerTests.swift
  Tests/MapboxNavigationTests/CarPlayNavigationViewControllerTests.swift
  Tests/MapboxNavigationTests/Constants.swift
  Tests/MapboxNavigationTests/DataCacheTests.swift
  Tests/MapboxNavigationTests/Fixtures/EmptyStyle.json
  Tests/MapboxNavigationTests/Fixtures/route-doubling-back.json
  Tests/MapboxNavigationTests/Fixtures/route-for-lane-testing.json
  Tests/MapboxNavigationTests/Fixtures/route-with-banner-instructions.json
  Tests/MapboxNavigationTests/Fixtures/route-with-lanes.json
  Tests/MapboxNavigationTests/Fixtures/route-with-straight-roundabout.json
  Tests/MapboxNavigationTests/Fixtures/sthlm-double-back-replay.json
  Tests/MapboxNavigationTests/Fixtures/sthlm-double-back.json
  Tests/MapboxNavigationTests/InstructionPresenterTests.swift
  Tests/MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift
  Tests/MapboxNavigationTests/InstructionsCardCollectionTests.swift
  Tests/MapboxNavigationTests/LaneTests.swift
  Tests/MapboxNavigationTests/LeaksSpec.swift
  Tests/MapboxNavigationTests/ManeuverArrowTests.swift
  Tests/MapboxNavigationTests/ManeuverViewTests.swift
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
  Tests/MapboxNavigationTests/SKUTestable.swift
  Tests/MapboxNavigationTests/SKUTests.swift
  Tests/MapboxNavigationTests/SpeechSynthesizersControllerTests.swift
  Tests/MapboxNavigationTests/StatusViewTests.swift
  Tests/MapboxNavigationTests/StepsViewControllerTests.swift
  Tests/MapboxNavigationTests/StringTests.swift
  Tests/MapboxNavigationTests/StyleManagerTests.swift
  Tests/MapboxNavigationTests/Support/AccessToken.swift
  Tests/MapboxNavigationTests/Support/CarPlayUtils.swift
  Tests/MapboxNavigationTests/Support/ImageDownloadOperationSpy.swift
  Tests/MapboxNavigationTests/Support/TokenTestViewController.swift
  Tests/MapboxNavigationTests/Support/Utils.swift
Labels: - tests

#3030 Add running tests using Package.swift
  .circleci/config.yml
Labels: - tests, CI

#3025 Fix ImageCache image cost estimation logic
  Sources/MapboxNavigation/ImageCache.swift
  Sources/MapboxNavigation/UIImage.swift
Labels: - performance, UI

#2495 Fix the moment of custom feedback event creation
  CHANGELOG.md
  Sources/MapboxNavigation/FeedbackSubtypeViewController.swift
  Sources/MapboxNavigation/FeedbackViewController.swift
Labels: - bug

#3031 Bring back xcframework based Carthage support for MapboxCoreNavigation
  .circleci/config.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Cartfile
  Cartfile.resolved
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxNavigation.xcscheme
  README.md
  Tests/SPMTest/SPMTest.xcodeproj/project.pbxproj
  Tests/SPMTest/SPMTest.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Tests/SPMTest/SPMTest.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Tests/SPMTest/SPMTest/AppDelegate.swift
  Tests/SPMTest/SPMTest/Assets.xcassets/AccentColor.colorset/Contents.json
  Tests/SPMTest/SPMTest/Assets.xcassets/AppIcon.appiconset/Contents.json
  Tests/SPMTest/SPMTest/Assets.xcassets/Contents.json
  Tests/SPMTest/SPMTest/Base.lproj/LaunchScreen.storyboard
  Tests/SPMTest/SPMTest/Base.lproj/Main.storyboard
  Tests/SPMTest/SPMTest/Info.plist
  Tests/SPMTest/SPMTest/SceneDelegate.swift
  Tests/SPMTest/SPMTest/ViewController.swift
  custom-navigation.md
  scripts/build_spm_integration_test.sh
  scripts/wcarthage.sh
Labels: - build, dependency management

#3053 v2.0.0 beta.12
  Bench/Info.plist
  BenchTests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: - build

#3054 Fix release version bumping
  Bench/Info.plist
  BenchTests/Info.plist
  Example/Info.plist
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
Labels: - build

#3050 Fixing Navigation end event loss of cancelling
  CHANGELOG.md
  Sources/MapboxCoreNavigation/NavigationEventsManager.swift
  Sources/MapboxCoreNavigation/NavigationService.swift
Labels: - bug, Core

#3016 Add ability to show arrival UI for CarPlay
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  Example/ViewController.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayManagerDelegate.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Tests/MapboxNavigationTests/CarPlayNavigationViewControllerTests.swift
  Tests/MapboxNavigationTests/Support/CarPlayUtils.swift
Labels: CarPlay, UI

#3057 Tile verification fix
  Sources/MapboxCoreNavigation/TileStore.swift
Labels: - bug, quick fix

#3059 Catch up with `main`.
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
Labels: - build, - chore

#2968 Allow to use map SDK location layer during turn-by-turn navigation
  CHANGELOG.md
  Example/CustomViewController.swift
  Example/ViewController+FreeDrive.swift
  Example/ViewController.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/NavigationLocationManager.swift
  Sources/MapboxCoreNavigation/ReplayLocationManager.swift
  Sources/MapboxCoreNavigation/SimulatedLocationManager.swift
  Sources/MapboxNavigation/CameraController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationMapViewIdentifiers.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/UserCourseView.swift
  Sources/MapboxNavigation/UserHaloCourseView.swift
  Sources/MapboxNavigation/UserLocationStyle.swift
  docs/jazzy.yml
Labels: UI

#3014 Navigator Tile version switching
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/CoreConstants.swift
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectMatcher.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectStore.swift
  Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
  Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
  Sources/MapboxCoreNavigation/PredictiveCacheManager.swift
  Sources/MapboxCoreNavigation/RouteController.swift
Labels: - feature, Core

#3039 Update Mapbox Maps to `v10.0.0-beta.21` and Navigation Native `52.0.0`.
  BenchTests/BenchTests.swift
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/CustomViewController.swift
  Example/ViewController+FreeDrive.swift
  Example/ViewController.swift
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/Directions.swift
  Sources/MapboxCoreNavigation/EHorizon/DistancedRoadObject.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectLocation.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectMatcher.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectType.swift
  Sources/MapboxCoreNavigation/Geometry.swift
  Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
  Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
  Sources/MapboxCoreNavigation/Result+Expected.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/TileStore.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/MapView.swift
  Sources/MapboxNavigation/MapboxMapsStyle.swift
  Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/OrnamentsController.swift
  Sources/MapboxNavigation/ResourceOptionsManager.swift
  Sources/MapboxNavigation/WayNameView.swift
  Sources/TestHelper/NavigationPlotter.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
  Tests/MapboxNavigationTests/CarPlayManagerTests.swift
  Tests/MapboxNavigationTests/LeaksSpec.swift
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
Labels: - build, UI

#3073 Fix state switching in overview button on CarPlay.
  Example/AppDelegate+CarPlay.swift
Labels: - bug, UI

#3074 Update refinement
  CHANGELOG.md
  Sources/MapboxCoreNavigation/CoreConstants.swift
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
  Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
  Sources/MapboxCoreNavigation/RouteController.swift
Labels: - refactor, topic: location

#3075 Fix the new user location layer in CarPlay
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Labels: - bug, CarPlay, UI

#3076 v2.0.0-beta.13
  Bench/Info.plist
  BenchTests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  Tests/MapboxNavigationTests/ManeuverArrowTests.swift
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
  custom-navigation.md
Labels: - build

#3072 Fix issues in ImageDownload and ImageDownloader
  Sources/MapboxNavigation/ImageDownload.swift
  Sources/MapboxNavigation/ImageDownloader.swift
  Tests/MapboxNavigationTests/ImageDownloaderTests.swift
  Tests/MapboxNavigationTests/Support/ImageLoadingURLProtocolSpy.swift
Labels: - bug, - crash, - refactor, - tests

#3083 Fix #3056 RouteController shouldDiscard location logic
  CHANGELOG.md
  Sources/MapboxCoreNavigation/RouteController.swift
  Tests/TestHelper/NavigationServiceTestDoubles.swift
Labels: - bug

#3082 v1.4.1
  Bench/Info.plist
  BenchTests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxNavigation/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  Tests/TestHelper/Info.plist
Labels: - build

#3085 Catch up with `main` branch.
  CHANGELOG.md
Labels: - build, - chore

#3088 Remove `--allow-warnings` flag from `config.yml`.
  .circleci/config.yml
Labels: - build, - chore

#3089 Fixes the race in ImageDownload
  Sources/MapboxNavigation/ImageDownload.swift
Labels: - bug

#3036 CarPlay refactoring and clean up.
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  Example/AppDelegate.swift
  Example/Base.lproj/Main.storyboard
  Example/CustomViewController.swift
  Example/UIViewController.swift
  Example/ViewController.swift
  Example/WaypointConfirmationViewController.swift
  Example/en.lproj/Localizable.strings
  Example/uk.lproj/Localizable.strings
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayManagerDelegate.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewControllerDelegate.swift
  Sources/MapboxNavigation/CarPlaySearchController+CPSearchTemplateDelegate.swift
  Sources/MapboxNavigation/CarPlaySearchController.swift
  Sources/MapboxNavigation/CarPlaySearchControllerDelegate.swift
  Sources/MapboxNavigation/RatingControl.swift
  Sources/MapboxNavigation/RouteVoiceController.swift
  Tests/MapboxNavigationTests/CarPlayManagerTests.swift
  Tests/MapboxNavigationTests/CarPlayNavigationViewControllerTests.swift
  docs/jazzy.yml
Labels: - refactor, CarPlay

#3092 Restore testSKUTokensMatch test case
  Tests/MapboxNavigationTests/SKUTests.swift
  Tests/MapboxNavigationTests/Support/TokenTestViewController.swift
  Tests/MapboxNavigationTests/Support/Utils.swift
Labels: - tests

#3100 Fix alternative route line selection.
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: - bug, UI

#3091 Create NavigationLocationProvider for NavigationMapView
  CHANGELOG.md
  Example/CustomViewController.swift
  Example/ViewController+FreeDrive.swift
  Example/ViewController.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/CoreConstants.swift
  Sources/MapboxCoreNavigation/EHorizon/ElectronicHorizonOptions.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadGraph.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadGraphEdge.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectStore.swift
  Sources/MapboxCoreNavigation/PassiveLocationManager.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/NavigationLocationProvider.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationViewportDataSource.swift
  Sources/MapboxNavigation/PassiveLocationProvider.swift
  Sources/MapboxNavigation/ViewportDataSourceType.swift
  Tests/MapboxCoreNavigationTests/PassiveLocationManagerTests.swift
  docs/cover.md
  docs/jazzy.yml
Labels: - feature, - refactor, Core

#3077 Update to Mapbox Maps `v10.0.0-rc.1`, Mapbox Directions `v2.0.0-beta.5`, Turf `v2.0.0-beta.1`.
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/ViewController.swift
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/Directions.swift
  Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
  Sources/MapboxCoreNavigation/TileStoreConfiguration.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationViewportDataSource.swift
  Sources/MapboxNavigation/Route.swift
  Tests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxNavigationTests/SKUTests.swift
Labels: - build

#3101 Bring back `MapView.preferredFramesPerSecond` property usage.
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: - bug, UI

#3110 Fix `FeedbackViewController` presentation on iPad.
  Sources/MapboxNavigation/Transitioning.swift
Labels: - bug, UI

#3109 Fix final annotation modification.
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationMapViewDelegate.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewControllerDelegate.swift
Labels: - bug, UI

#3112 Fix more lane icon edge cases and tests
  Package.swift
  Sources/MapboxNavigation/LaneView.swift
  Tests/MapboxNavigationTests/LaneViewTests.swift
Labels: - bug, - tests, topic: instructions

#3113 Update to NavNative `54.0.0` and Maps `10.0.0-rc.2`
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectMatcher.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectMatcherDelegate.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: - build

#3114 Separate example targets
  .circleci/config.yml
  CONTRIBUTING.md
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation-SPM.xcodeproj/xcshareddata/xcbaselines/35B711CE1E5E7AD2001EDA8D.xcbaseline/51BD5556-46A3-4CC6-A414-4933647ED596.plist
  MapboxNavigation-SPM.xcodeproj/xcshareddata/xcbaselines/35B711CE1E5E7AD2001EDA8D.xcbaseline/DE43C589-1E37-4086-B867-7E50F2C9F487.plist
  MapboxNavigation-SPM.xcodeproj/xcshareddata/xcbaselines/35B711CE1E5E7AD2001EDA8D.xcbaseline/F6C31427-6859-412C-B6C0-9E436C247941.plist
  MapboxNavigation-SPM.xcodeproj/xcshareddata/xcbaselines/35B711CE1E5E7AD2001EDA8D.xcbaseline/Info.plist
  MapboxNavigation-SPM.xcodeproj/xcshareddata/xcbaselines/35CDA81821908F320072B675.xcbaseline/Info.plist
  MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Bench.xcscheme
  MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example-CarPlay.xcscheme
  MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
  MapboxNavigation.xcodeproj/project.pbxproj
Labels: - build

#3125 Fix style image flipping in current road name label
  Sources/MapboxNavigation/WayNameView.swift
Labels: - bug, topic: instructions

#3106 Adjust the layer position to make puck layer at topmost
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationMapViewIdentifiers.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: - bug, UI
