Repository mapbox/mapbox-navigation-ios, pull requests merged in 2021-02, with the labels that each got.

#2793 MapboxNavigationNative v30.0.0, MapboxCommon v9.2.0
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  Package.resolved
  Package.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: - build, dependency management

#2795 v1.2.1
  Bench/Info.plist
  BenchTests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxNavigation/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  Tests/TestHelper/Info.plist
Labels: - build

#2727 Update snapshot tests for iOS 14
  .circleci/config.yml
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/MapboxNavigation.xcscheme
  Sources/MapboxNavigation/InstructionsCardContainerView.swift
  Sources/MapboxNavigation/StyleManager.swift
  Tests/MapboxNavigationTests/CarPlayManagerTests.swift
  Tests/MapboxNavigationTests/FailureDiffs/MapboxNavigationTests.GuidanceCardsSnapshotTests/diff_testLanesManeuver_iPhone6Plus_Portrait_iOS_13.5@3x.png
  Tests/MapboxNavigationTests/FailureDiffs/MapboxNavigationTests.GuidanceCardsSnapshotTests/diff_testRegularManeuver_iPhone6Plus_Portrait_iOS_13.5@3x.png
  Tests/MapboxNavigationTests/FailureDiffs/MapboxNavigationTests.GuidanceCardsSnapshotTests/diff_testTertiaryManeuver_iPhone6Plus_Portrait_iOS_13.5@3x.png
  Tests/MapboxNavigationTests/FailureDiffs/MapboxNavigationTests.GuidanceCardsSnapshotTests/failed_testLanesManeuver_iPhone6Plus_Portrait_iOS_13.5@3x.png
  Tests/MapboxNavigationTests/FailureDiffs/MapboxNavigationTests.GuidanceCardsSnapshotTests/failed_testRegularManeuver_iPhone6Plus_Portrait_iOS_13.5@3x.png
  Tests/MapboxNavigationTests/FailureDiffs/MapboxNavigationTests.GuidanceCardsSnapshotTests/failed_testTertiaryManeuver_iPhone6Plus_Portrait_iOS_13.5@3x.png
  Tests/MapboxNavigationTests/FailureDiffs/MapboxNavigationTests.GuidanceCardsSnapshotTests/reference_testLanesManeuver_iPhone6Plus_Portrait_iOS_13.5@3x.png
  Tests/MapboxNavigationTests/FailureDiffs/MapboxNavigationTests.GuidanceCardsSnapshotTests/reference_testRegularManeuver_iPhone6Plus_Portrait_iOS_13.5@3x.png
  Tests/MapboxNavigationTests/FailureDiffs/MapboxNavigationTests.GuidanceCardsSnapshotTests/reference_testTertiaryManeuver_iPhone6Plus_Portrait_iOS_13.5@3x.png
  Tests/MapboxNavigationTests/GuidanceCardsSnapshotTests.swift
  Tests/MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.BottomBannerSnapshotTests/testBottomBannerViewControllerNoSafeArea_iPhone_8_Portrait_iOS_14.1@2x.png
  Tests/MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.BottomBannerSnapshotTests/testBottomBannerViewController_iPhone_X_Portrait_iOS_14.1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testLanesManeuver_iPhone_8_Plus_Portrait_iOS_14.1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testRegularManeuver_iPhone_8_Plus_Portrait_iOS_14.1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.GuidanceCardsSnapshotTests/testTertiaryManeuver_iPhone_8_Plus_Portrait_iOS_14.1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.InstructionsCard/testInstructionsCardCollection_iPhone_X_Portrait_iOS_14.1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages/MapboxNavigationTests.InstructionsCardSnapshotTest/testInstructionsCardCollection_iPhone_X_Portrait_iOS_14.1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAbbreviateInstructionsIncludingDelimiter_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAbbreviateInstructions_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAbbreviateWestFremontAvenue_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testAdjacentShields_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testExitShields_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testGenericShields_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testInstructionsAndNextInstructions_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testLongDistance_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testMultilinePrimary_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testPrimaryShieldAndSecondary_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testSinglelinePrimaryAndSecondary_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testSinglelinePrimary_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testSweEngLongDistance_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.InstructionsBannerViewSnapshotTests/testUkrainianLongDistance_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.LaneTests/testAllLanes30x30_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.LaneTests/testAllLanes90x90_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testArriveNone_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testArrive_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testLeftUTurn_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testMergeRight_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testRightUTurn_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testRoundaboutTurnLeft_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testRoundabout_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testStraightRoundabout_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testTurnRight_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.ManeuverViewTests/testTurnSlightRight_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.RouteControllerSnapshotTests/testRouteSnappingOvershooting_iPhone_14_1@3x.png
  Tests/MapboxNavigationTests/ReferenceImages_64/MapboxNavigationTests.SimulatedLocationManagerTests/testSimulateRouteDoublesBack_iPhone_14_1@3x.png
Labels: - chore, - tests, CarPlay

#2798 Add lane guidance to CarPlay. Fix incorrect coloring of dual-use lane icons
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/LaneView.swift
  Sources/MapboxNavigation/LanesStyleKit.swift
  Sources/MapboxNavigation/LanesView.swift
  Sources/MapboxNavigation/UIImage.swift
  Sources/MapboxNavigation/UIView.swift
  Sources/MapboxNavigation/VisualInstruction.swift
  Tests/MapboxNavigationTests/LaneTests.swift
Labels: - feature, CarPlay, UI, topic: instructions

#2805 Show junction view on main queue
  CHANGELOG.md
  Sources/MapboxNavigation/JunctionView.swift
Labels: - crash, UI, topic: instructions

#2803 Flip U-Turn Maneuver view when driving side is right
  CHANGELOG.md
  Sources/MapboxNavigation/UIView.swift
  Sources/MapboxNavigation/VisualInstruction.swift
Labels: - bug, CarPlay, UI, topic: instructions

#2835 Fix crash in NavigationMapView if it's created via storyboard.
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: - bug, - crash

#2836 Add default implementations for waypoint customization delegates.
  Sources/MapboxNavigation/NavigationMapViewDelegate.swift
  Sources/MapboxNavigation/NavigationViewControllerDelegate.swift
Labels: - bug, UI

#2838 Fix route layer shown over map labels
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: - bug, UI, iOS

#2840 v2.0.0-alpha.2
  Bench/Info.plist
  BenchTests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxNavigation/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  Tests/TestHelper/Info.plist
  custom-navigation.md
  scripts/update-version.sh
Labels: - build
