Repository mapbox/mapbox-navigation-ios, pull requests merged in 2021-05, with the labels that each got.

#2970 Fix feedback UI.
  Sources/MapboxNavigation/FeedbackSubtypeCollectionViewCell.swift
Labels: - bug

#2956 TileStore config for Navigator and MapView
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/LegacyRouteController.swift
  Sources/MapboxCoreNavigation/NavigationService.swift
  Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
  Sources/MapboxCoreNavigation/PredictiveCacheManager.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/Router.swift
  Sources/MapboxCoreNavigation/TileStoreConfiguration.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationOptions.swift
  Sources/MapboxNavigation/NavigationView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
Labels: iOS

#2975 Fix the Maneuver selection in preview
  Sources/MapboxNavigation/CameraController.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationViewportDataSource.swift
  Sources/MapboxNavigation/UIEdgeInsets.swift
Labels: - bug, UI, topic: camera

#2976 bring the arrival frame back to same as 1.x
  Sources/MapboxNavigation/ArrivalController.swift
Labels: UI

#2985 Fix crash in ornaments controller.
  Sources/MapboxNavigation/OrnamentsController.swift
Labels: - bug, - crash

#2988 Fix history directory path configuration
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Labels: - bug

#2990 Fix crash when accessing `compassView`.
  Sources/MapboxNavigation/CarPlayManager.swift
Labels: - bug, - crash, CarPlay

#2978 Update private Carthage dependencies
  Cartfile.private
  Cartfile.resolved
Labels: - build

#2984 Allow the maneuver arrow disappear on customized low zoom level
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: - bug, UI

#2993 Remove deprecated and obsoleted APIs.
  CHANGELOG.md
  Sources/MapboxCoreNavigation/NavigationEventsManager.swift
  Sources/MapboxCoreNavigation/RouteLegProgress.swift
  Sources/MapboxNavigation/BottomBannerViewController.swift
  Sources/MapboxNavigation/StatusView.swift
Labels: - chore, - refactor

#2983 Update Mapbox Maps SDK dependency to `v10.0.0-beta.19.1`.
  CHANGELOG.md
  Example/CustomViewController.swift
  Example/ViewController+FreeDrive.swift
  Example/ViewController+GuidanceCards.swift
  Example/ViewController.swift
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
  Sources/MapboxNavigation/ArrivalController.swift
  Sources/MapboxNavigation/CameraController.swift
  Sources/MapboxNavigation/CarPayCompassView.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/MapboxMapsStyle.swift
  Sources/MapboxNavigation/NavigationCameraDebugView.swift
  Sources/MapboxNavigation/NavigationCameraStateTransition.swift
  Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationMapViewIdentifiers.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewportDataSource.swift
  Sources/MapboxNavigation/OrnamentsController.swift
  Sources/MapboxNavigation/WayNameView.swift
  Sources/TestHelper/NavigationPlotter.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: - build

#2995 Catch-up with `main`.
  .gitattributes
  .tx/config
  Bench/Assets.xcassets/Contents.json
  CHANGELOG.md
  Cartfile.private
  Cartfile.resolved
  Example/AppDelegate+CarPlay.swift
  Example/AppDelegate.swift
  Example/Assets.xcassets/Contents.json
  Example/FavoritesList.swift
  Example/Info.plist
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation.xcodeproj/xcshareddata/xcschemes/Example-CarPlay.xcscheme
  README.md
  Sources/MapboxCoreNavigation/Resources/ca.lproj/Localizable.strings
  Sources/MapboxNavigation/CPMapTemplate.swift
  Sources/MapboxNavigation/CPTrip.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayManagerDelegate.swift
  Sources/MapboxNavigation/CarPlaySearchController+CPSearchTemplateDelegate.swift
  Sources/MapboxNavigation/CarPlaySearchController.swift
  Sources/MapboxNavigation/CongestionLevel.swift
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/NavigationComponent.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NightStyle.swift
  Sources/MapboxNavigation/RecentItem.swift
  Sources/MapboxNavigation/Resources/Base.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/ca.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/ca.lproj/Localizable.stringsdict
  Sources/MapboxNavigation/Resources/ca.lproj/Navigation.strings
  Sources/MapboxNavigation/Resources/de.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/es.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/uk.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/vi.lproj/Localizable.strings
  Sources/MapboxNavigation/StatusView.swift
  Sources/MapboxNavigation/StyleManager.swift
  Sources/MapboxNavigation/TopBannerViewController.swift
  Sources/MapboxNavigation/UIScreen.swift
  Sources/MapboxNavigation/VisualInstruction.swift
  Tests/MapboxNavigationTests/CPMapTemplateTests.swift
  Tests/MapboxNavigationTests/CarPlayManagerTests.swift
  Tests/MapboxNavigationTests/StatusViewTests.swift
  custom-navigation.md
  scripts/convert_string_files.sh
  scripts/update-version.sh
Labels: - build, - chore, Core, UI

#3000 v2.0.0 beta.9
  Bench/Info.plist
  BenchTests/Info.plist
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: - build

#3009 SPM: Update mapbox-events-ios to v0.10.8
  Package.resolved
Labels: - build, dependency management

#3008 Fix "class" as protocol deprecation warnings
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectsStoreDelegate.swift
  Sources/MapboxCoreNavigation/LegacyRouteController.swift
  Sources/MapboxCoreNavigation/NavigationEventsManager.swift
  Sources/MapboxCoreNavigation/NavigationRouteOptions.swift
  Sources/MapboxCoreNavigation/NavigationServiceDelegate.swift
  Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
  Sources/MapboxCoreNavigation/Router.swift
  Sources/MapboxCoreNavigation/RouterDelegate.swift
  Sources/MapboxNavigation/BottomBannerViewController.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayManagerDelegate.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/CarPlaySearchController.swift
  Sources/MapboxNavigation/FeedbackViewController.swift
  Sources/MapboxNavigation/InstructionLabel.swift
  Sources/MapboxNavigation/InstructionPresenter.swift
  Sources/MapboxNavigation/InstructionsBannerView.swift
  Sources/MapboxNavigation/NavigationComponent.swift
  Sources/MapboxNavigation/NavigationMapViewDelegate.swift
  Sources/MapboxNavigation/NavigationViewData.swift
  Sources/MapboxNavigation/RouteVoiceController.swift
  Sources/MapboxNavigation/SpeechSynthesizing.swift
  Sources/MapboxNavigation/StepsViewController.swift
  Sources/MapboxNavigation/StyleManager.swift
  Sources/MapboxNavigation/TopBannerViewController.swift
Labels: - build

#2991 Update NN to 49.0.1, RoadObject overhaul
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  MapboxNavigation.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/CoreConstants.swift
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/EHorizon/DistancedRoadObject.swift
  Sources/MapboxCoreNavigation/EHorizon/OpenLROrientation.swift
  Sources/MapboxCoreNavigation/EHorizon/OpenLRSideOfRoad.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadGraphEdge.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadGraphEdgeMetadata.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadGraphPath.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadGraphPosition.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObject.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectDistanceInfo.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectEdgeLocation.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectLocation.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectMetadata.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectPosition.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectType.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectsStore.swift
  Sources/MapboxCoreNavigation/Geometry.swift
  Sources/MapboxCoreNavigation/Incident.swift
  Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
  Sources/MapboxCoreNavigation/RouteAlert.swift
  Sources/MapboxCoreNavigation/SkuTokenProvider.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/SkuTokenProviderTests.swift
Labels: - refactor

#3005 Fix circular reference issue in MultiplexedSpeechSynthesizer
  CHANGELOG.md
  Sources/MapboxNavigation/MultiplexedSpeechSynthesizer.swift
Labels: - bug

#2977 Clear ImageRepository cache when style change
  CHANGELOG.md
  Sources/MapboxNavigation/InstructionLabel.swift
Labels: - bug, UI

#3004 Custom road objects for EH
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/CoreConstants.swift
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/EHorizon/DistancedRoadObject.swift
  Sources/MapboxCoreNavigation/EHorizon/OpenLRStandard.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObject.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectMatcher.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectMatcherDelegate.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectMatcherError.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectsStore.swift
  Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
  Sources/MapboxCoreNavigation/Result+Expected.swift
  Sources/MapboxCoreNavigation/RouteController.swift
Labels: - feature

#3021 v2.0.0-beta.10
  Bench/Info.plist
  BenchTests/Info.plist
  CHANGELOG.md
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: - build

#3017 Fix build related warnings when using Xcode 12.5
  .tx/config
  Example/en.lproj/Localizable.strings
  MapboxNavigation.xcodeproj/project.pbxproj
  Package.swift
  Sources/MapboxCoreNavigation/Resources/Base.lproj/Localizable.strings
  Sources/MapboxCoreNavigation/Resources/en.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/en.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/en.lproj/Navigation.strings
  Sources/TestHelper/GGPark-to-BernalHeights.route
  Sources/TestHelper/NavigationPlotter.swift
  Sources/TestHelper/UnionSquare-to-GGPark.route
  Sources/TestHelper/li.tar
  Sources/TestHelper/turn_left.data
  Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
  Tests/MapboxCoreNavigationTests/PassiveLocationDataSourceTests.swift
  Tests/MapboxNavigationTests/Fixtures/GGPark-to-BernalHeights.route
  Tests/MapboxNavigationTests/Fixtures/UnionSquare-to-GGPark.route
  Tests/MapboxNavigationTests/Fixtures/turn_left.data
  scripts/extract_localizable.sh
Labels: - build, - tests

#3026 Fix versions in a jazzy docs
  docs/cover.md
Labels: documentation, topic: documentation

#3010 Update to Mapbox Maps `10.0.0-beta.20`, Navigation Native `50.0.0` and Common `12.0.0`.
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/CustomStyles.swift
  Example/CustomViewController.swift
  Example/ViewController+FreeDrive.swift
  Example/ViewController.swift
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/Accounts.swift
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/Directions.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectMatcher.swift
  Sources/MapboxCoreNavigation/PassiveLocationDataSource.swift
  Sources/MapboxCoreNavigation/Result+Expected.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/TileStoreConfiguration.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/MapView.swift
  Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/OrnamentsController.swift
  Sources/MapboxNavigation/RouteLineController.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: - build, UI

#3028 Fix text missing in Guidance Card navigation
  Sources/MapboxNavigation/InstructionLabel.swift
Labels: - bug, UI

#2974 Fix NavigationViewController crash in storyboard.
  CHANGELOG.md
  Example/CustomViewController.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/Resources/Base.lproj/Navigation.storyboard
Labels: - bug, UI

#3034 Fix Cedar.framework path
  MapboxNavigation.xcodeproj/project.pbxproj
Labels: - build

#3024 Fix UnimplementedLogging.logUnimplemented method
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/UnimplementedLogging.swift
  Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
  Tests/MapboxCoreNavigationTests/UnimplementedLoggingTests.swift
Labels: - bug, Core

#3015 TileStore navigation tiles API
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
  Sources/MapboxCoreNavigation/TileStore.swift
  Sources/MapboxCoreNavigation/TilesetDescriptorFactory.swift
Labels: - feature, Core

#3019 Use EHorizon to improve road label during turn-by-turn navigation
  CHANGELOG.md
  Sources/MapboxCoreNavigation/MinimumEditDistance.swift
  Sources/MapboxNavigation/OrnamentsController.swift
Labels: - bug, UI

#3040 Offline routing
  CHANGELOG.md
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/Directions.swift
Labels: - bug, Core, quick fix
