Repository mapbox/mapbox-navigation-ios, pull requests merged in 2021-09, with the labels that each got.

#3315 Fix `.netrc` permission issue.
  .circleci/config.yml
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: - build

#3309 Add `UserHaloCourseViewSnapshotTests`.
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/UserHaloCourseView.swift
  Sources/TestHelper/Fixtures/Images.xcassets/user_halo_color_set.colorset/Contents.json
  Sources/TestHelper/Fixtures/Images.xcassets/user_halo_ring_color_set.colorset/Contents.json
  Tests/MapboxNavigationTests/UserHaloCourseViewSnapshotTests.swift
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/UserHaloCourseViewSnapshotTests/testUserHaloCourseView.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/UserHaloCourseViewSnapshotTests/testUserHaloCourseViewColorWhenChangingAppearance.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/UserHaloCourseViewSnapshotTests/testUserHaloCourseViewColorWhenChangingAppearance.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/UserHaloCourseViewSnapshotTests/testUserUserHaloCourseView.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/UserHaloCourseViewSnapshotTests/testUserHaloCourseView.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/UserHaloCourseViewSnapshotTests/testUserHaloCourseViewColorWhenChangingAppearance.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/UserHaloCourseViewSnapshotTests/testUserHaloCourseViewColorWhenChangingAppearance.2.png
Labels: - tests, UI

#3293 Make navigation camera options more restrictive.
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Sources/MapboxNavigation/FollowingCameraOptions.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationViewportDataSource.swift
  Sources/MapboxNavigation/NavigationViewportDataSourceOptions.swift
  Sources/MapboxNavigation/OverviewCameraOptions.swift
  Tests/MapboxNavigationTests/NavigationCameraTests.swift
Labels: topic: camera, UI

#3337 Copyedit feedback categories
  Sources/MapboxCoreNavigation/PassiveNavigationFeedbackType.swift
  Sources/MapboxNavigation/Feedback/PassiveNavigationFeedbackType+FeedbackItem.swift
  Sources/MapboxNavigation/Resources/en.lproj/Localizable.strings
Labels: - bug, topic: telemetry

#3339 Update active navigation feedback categories
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/ActiveNavigationFeedbackType.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/Feedback/ActiveNavigationFeedbackType+FeedbackItem.swift
  Sources/MapboxNavigation/Feedback/FeedbackItem.swift
  Sources/MapboxNavigation/Feedback/FeedbackViewControllerType.swift
  Sources/MapboxNavigation/Feedback/PassiveNavigationFeedbackType+FeedbackItem.swift
  Sources/MapboxNavigation/Resources/ca.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/de.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/en.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/es-ES.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/es.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/ru.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/uk.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/vi.lproj/Localizable.strings
Labels: release blocker

#3334 Partially update the layer property instead of updating the whole layer.
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Labels: - performance

#3346 Update translations from Transifex
  Sources/MapboxNavigation/Resources/ca.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/de.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/es-ES.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/es.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/ru.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/uk.lproj/Localizable.strings
  Sources/MapboxNavigation/Resources/vi.lproj/Localizable.strings
Labels: topic: localization

#3344 Fix IndexedRouteResponse handling after rerouting
  Sources/MapboxCoreNavigation/RouteController.swift
Labels: - bug

#3350 Docs generation fix
  Sources/MapboxNavigation/CongestionLevel+CarPlay.swift
Labels: quick fix, documentation

#3310 Cover `MapboxNavigation` extensions with automated tests.
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/NSAttributedString.swift
  Sources/MapboxNavigation/UIViewController.swift
  Tests/MapboxNavigationTests/CGPointTests.swift
Labels: - tests, UI

#3356 Add missing files to `MapboxNavigation.xcodeproj`.
  Cartfile.resolved
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/Feedback/DialogViewController.swift
Labels: - bug, - build

#3307 Suport gradient for congestion color change.
  CHANGELOG.md
  Sources/MapboxNavigation/Constants.swift
  Sources/MapboxNavigation/Expression.swift
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
  docs/jazzy.yml
Labels: UI

#3370 Temporary disable API Diff workflow as it has a lot of bugs
  .circleci/config.yml
  Tests/MapboxCoreNavigationTests/BillingHandlerTests.swift
Labels: CI

#3330 Reimplement label localization atop Expression (redux)
  Example/ViewController.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/MapView.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/OrnamentsController.swift
  Sources/MapboxNavigation/RouteLineController.swift
  Sources/MapboxNavigation/VectorSource.swift
  Tests/MapboxNavigationTests/MapViewTests.swift
Labels: - feature, release blocker, topic: localization

#3366 Update `RoadObjectType` documentation.
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectType.swift
Labels: documentation

#3345 Fix inconsistent route progress and index after rerouting
  CHANGELOG.md
  Sources/MapboxCoreNavigation/LegacyRouteController.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/Router.swift
  Tests/MapboxCoreNavigationTests/BillingHandlerTests.swift
Labels: - bug, - refactor, backwards-incompatible

#3367 Rename `RoadObjectType` to `RoadObject.Kind` (and other related symbols).
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/CoreConstants.swift
  Sources/MapboxCoreNavigation/EHorizon/DistancedRoadObject.swift
  Sources/MapboxCoreNavigation/EHorizon/OpenLRIdentifier.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObject.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectEdgeLocation.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectKind.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectLocation.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectMatcher.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectMatcherError.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectPosition.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectStore.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectStoreDelegate.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectType.swift
  docs/jazzy.yml
Labels: - refactor

#3364 EH Mark comments
  Sources/MapboxCoreNavigation/EHorizon/RoadGraph.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadGraphEdgeMetadata.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectMatcher.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectStore.swift
Labels: documentation

#3342 Update to Mapbox Maps `v10.0.0-rc.8`, Navigation Native `66.0.0` and Common `18.0.0`.
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/ViewController+FreeDrive.swift
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/EHorizon/DistancedRoadObject.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectLocation.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectStore.swift
  Sources/MapboxCoreNavigation/LegacyRouteController.swift
  Sources/MapboxCoreNavigation/PassiveLocationManager.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/Router.swift
  Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/OrnamentsController.swift
  Sources/MapboxNavigation/WayNameView.swift
  Sources/TestHelper/DirectionsSpy.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
  Tests/MapboxCoreNavigationTests/RouteControllerTests.swift
Labels: - build

#3354 Disable failing on M1 tests
  Sources/MapboxNavigation/FollowingCameraOptions.swift
  Sources/MapboxNavigation/OverviewCameraOptions.swift
  Tests/MapboxNavigationTests/NavigationCameraTests.swift
Labels: - tests

#3371 Add SPM `MapboxCoreNavigation` integration test
  .circleci/config.yml
  Tests/SPMTest/CoreSPMTest/CoreSPMTest.xcodeproj/project.pbxproj
  Tests/SPMTest/CoreSPMTest/CoreSPMTest.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Tests/SPMTest/CoreSPMTest/CoreSPMTest/Assets.xcassets/AccentColor.colorset/Contents.json
  Tests/SPMTest/CoreSPMTest/CoreSPMTest/Assets.xcassets/AppIcon.appiconset/Contents.json
  Tests/SPMTest/CoreSPMTest/CoreSPMTest/Assets.xcassets/Contents.json
  Tests/SPMTest/CoreSPMTest/CoreSPMTest/ContentView.swift
  Tests/SPMTest/CoreSPMTest/CoreSPMTest/CoreSPMTestApp.swift
  Tests/SPMTest/CoreSPMTest/CoreSPMTest/Info.plist
  Tests/SPMTest/CoreSPMTest/CoreSPMTest/Preview Content/Preview Assets.xcassets/Contents.json
Labels: - build, CI

#3382 Generate prerelease podspecs
  .gitignore
  scripts/update-version.sh
Labels: - build, CocoaPods

#3387 handle route with no distance
  CHANGELOG.md
  Sources/MapboxCoreNavigation/RouteLegProgress.swift
  Sources/MapboxCoreNavigation/RouteProgress.swift
  Sources/TestHelper/Fixtures/routeWithNoDistance.json
  Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  Tests/MapboxCoreNavigationTests/RouteProgressTests.swift
Labels: - crash

#3383 Allow guidance cards to receive the instruction update
  CHANGELOG.md
  Sources/MapboxNavigation/InstructionsCardCell.swift
  Sources/MapboxNavigation/InstructionsCardContainerView.swift
  Sources/MapboxNavigation/InstructionsCardView.swift
  Sources/MapboxNavigation/InstructionsCardViewController.swift
Labels: - bug, UI

#3394 Don't log an error if RecentItem file doesn't exist
  Sources/MapboxNavigation/RecentItem.swift
Labels: - refactor

#3401 Restore testNotReroutingForAllSteps test
  Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
Labels: - tests

#3397 Fix `CPMapTemplate.tripEstimateStyle` update issues.
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/Feedback/FeedbackSubtypeCollectionViewCell.swift
Labels: - bug, UI, CarPlay

#3405 Improve viewport parameters on CarPlay.
  Sources/MapboxNavigation/NavigationViewportDataSource.swift
Labels: UI, CarPlay

#3373 CoreNavigation MARK comments
  Sources/MapboxCoreNavigation/BillingHandler.swift
  Sources/MapboxCoreNavigation/BundleAdditions.swift
  Sources/MapboxCoreNavigation/CLLocation.swift
  Sources/MapboxCoreNavigation/CoreConstants.swift
  Sources/MapboxCoreNavigation/DispatchTimer.swift
  Sources/MapboxCoreNavigation/DistanceFormatter.swift
  Sources/MapboxCoreNavigation/Feedback/NavigationEventsManager.swift
  Sources/MapboxCoreNavigation/LegacyRouteController.swift
  Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
  Sources/MapboxCoreNavigation/NavigationService.swift
  Sources/MapboxCoreNavigation/NavigationServiceDelegate.swift
  Sources/MapboxCoreNavigation/PassiveLocationManager.swift
  Sources/MapboxCoreNavigation/ReplayLocationManager.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/RouteLegProgress.swift
  Sources/MapboxCoreNavigation/RouteProgress.swift
  Sources/MapboxCoreNavigation/RouteStepProgress.swift
  Sources/MapboxCoreNavigation/RouterDelegate.swift
  Sources/MapboxCoreNavigation/SimulatedLocationManager.swift
Labels: documentation

#3388 Adds a script to use debug version of MapboxNavigationNative
  scripts/debug_navigation_native.sh
Labels: - build

#3408 Fix issue, when user puck goes offscreen in some cases.
  Sources/MapboxNavigation/NavigationViewportDataSource.swift
Labels: topic: camera, UI, Regression

#3407 Fix the tilt of the `UserHaloCourseView`.
  CHANGELOG.md
  Sources/MapboxNavigation/UserCourseView.swift
Labels: - bug, UI

#3415 Improve `MapboxNavigation` bundle detection.
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/BundleAdditions.swift
  Sources/MapboxNavigation/Bundle.swift
  Tests/MapboxCoreNavigationTests/BundleAdditionsTests.swift
  Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
Labels: bug, Core

#3378 New billing trip starts on each waypoint
  Sources/MapboxCoreNavigation/BillingHandler.swift
  Sources/MapboxCoreNavigation/LegacyRouteController.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/TestHelper/Fixture.swift
  Sources/TestHelper/TestCase.swift
  Tests/MapboxCoreNavigationTests/BillingHandlerTests.swift
  Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  Tests/MapboxNavigationTests/MapViewTests.swift
Labels: feature

#3419 Update MapboxNavigationNative, MapboxDirectionsSwift dependencies
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: build, release blocker, v2.x

#3420 v2.0.0-rc.4
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-Documentation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build, v2.x
