Repository mapbox/mapbox-navigation-ios, pull requests merged in 2021-11, with the labels that each got.

#3538 Add preventive checks to make sure that before running camera animations coordinate is valid.
  Sources/MapboxNavigation/NavigationCameraStateTransition.swift
  Tests/MapboxNavigationTests/NavigationCameraTests.swift
Labels: bug, topic: camera, UI

#3544 Fix the scrolling guidance cards during orientation change crash
  CHANGELOG.md
  Sources/MapboxNavigation/InstructionsCardViewController.swift
Labels: UI

#3543 Fix issue, which was causing panning dismissal button to stop working on CarPlay.
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
Labels: bug, UI, CarPlay

#3545 Add panning functionality for `CarPlayNavigationViewController`.
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  Sources/MapboxNavigation/CarPlayActivity.swift
  Sources/MapboxNavigation/CarPlayManager.swift
Labels: UI, CarPlay

#3554 Remove xcpretty
  .circleci/config.yml
Labels: build

#3552 Fix car play retain cycle
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayMapViewController.swift
Labels: bug, op-ex, CarPlay, needs cherry-picking

#3558 Pause NavNative navigator when there are no running billing sessions
  CHANGELOG.md
  Sources/MapboxCoreNavigation/BillingHandler.swift
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Tests/MapboxCoreNavigationTests/BillingHandlerTests.swift
Labels: op-ex, release blocker, Apps, P1, v2.x

#3566 Fix issue, which was preventing from adding route duration layer to the map view.
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: bug, UI

#3577 Use `trafficUnknownColor` for route line when no congestion level found.
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Labels: bug, UI

#3559 Add ability to disable dark style, while traversing through the tunnel.
  CHANGELOG.md
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example-CarPlay.xcscheme
  MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewController.swift
Labels: UI, CarPlay, improvement

#3503 Fix guidance cards
  CHANGELOG.md
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/InstructionsCardCell.swift
  Sources/MapboxNavigation/InstructionsCardContainerView.swift
  Sources/MapboxNavigation/InstructionsCardView.swift
  Sources/MapboxNavigation/NightStyle.swift
  Tests/MapboxNavigationTests/InstructionsCardCollectionTests.swift
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/GuidanceCardsSnapshotTests/testLanesManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/GuidanceCardsSnapshotTests/testRegularManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/GuidanceCardsSnapshotTests/testTertiaryManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/GuidanceCardsSnapshotTests/testLanesManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/GuidanceCardsSnapshotTests/testRegularManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/GuidanceCardsSnapshotTests/testTertiaryManeuver.1.png
Labels: bug

#3547 Deprecate custom usesMetric in favor of iOS defined usesMetricSystem
  CHANGELOG.md
  Sources/MapboxCoreNavigation/Locale.swift
  Sources/MapboxCoreNavigation/NavigationService.swift
  Sources/MapboxCoreNavigation/NavigationSettings.swift
  Sources/MapboxNavigation/NavigationViewController.swift
Labels: op-ex, topic: localization

#3575 Allow the customization of TopBannerViewController.
  CHANGELOG.md
  Sources/MapboxNavigation/InstructionsBannerView.swift
  Sources/MapboxNavigation/NavigationView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/TopBannerViewController.swift
  Tests/MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift
Labels: UI

#3583 Fix issue, which was causing inability to see `SpeedLimitView` and `CarPlayCompassView` when right-to-left mode is used on CarPlay.
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Labels: UI, CarPlay

#3569 Rewrite lane use diagram drawing and selection logic
  CHANGELOG.md
  Sources/MapboxNavigation/LaneView.swift
  Sources/MapboxNavigation/LanesStyleKit.swift
  Tests/MapboxNavigationTests/LaneViewTests.swift
Labels: platform parity, op-ex, topic: instructions, UI

#3541 Fix distance measurement system
  CHANGELOG.md
  Sources/MapboxCoreNavigation/DistanceFormatter.swift
  Sources/MapboxCoreNavigation/NavigationRouteOptions.swift
  Sources/MapboxCoreNavigation/NavigationService.swift
  Sources/MapboxCoreNavigation/NavigationSettings.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Tests/MapboxCoreNavigationTests/MeasurementSystemTests.swift
Labels: bug, topic: localization

#3556 Implement the ability to show routes based on style provided in `RoutesPresentationStyle`.
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/RouteDurationAnnotationTailPosition.swift
  Sources/MapboxNavigation/RoutesPresentationStyle.swift
Labels: UI, CarPlay

#3592 Update Mapbox Navigation to `v2.1.0-rc.1`.
  .base_api
  CHANGELOG.md
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build

#3527 Road name labeling functionality for CarPlay.
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/CameraController.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/NavigationMapView+RoadNameLabeling.swift
  Sources/MapboxNavigation/NavigationView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewportDataSource.swift
  Sources/MapboxNavigation/OrnamentsController.swift
  Sources/MapboxNavigation/UIImage.swift
  Sources/MapboxNavigation/UIView.swift
  Sources/MapboxNavigation/WayNameView.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: UI, CarPlay

#3606 Upgrade from Xcode `12.4` to `12.5.1`.
  .circleci/config.yml
Labels: bug, build

#3533 Stop the location update in the background during active navigation using default course view.
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
Labels: bug, UI

#3601 Allow the UserPuckCourseView drawn by the given bounds scale.
  CHANGELOG.md
  Sources/MapboxNavigation/UserCourseView.swift
  Tests/MapboxNavigationTests/UserPuckCourseViewSnapshotTests.swift
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewFillAndShadowColorWhenChangingAppearance.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewFillAndShadowColorWhenChangingAppearance.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewPuckColorWhenChangingAppearance.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewPuckColorWhenChangingAppearance.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewScale.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewStalePuckColor.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewStalePuckColor.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewFillAndShadowColorWhenChangingAppearance.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewFillAndShadowColorWhenChangingAppearance.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewPuckColorWhenChangingAppearance.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewPuckColorWhenChangingAppearance.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewScale.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewStalePuckColor.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewStalePuckColor.2.png
Labels: bug, UI

#3602 Fix misspelled word
  Sources/MapboxNavigation/StyleManager.swift
Labels: documentation

#3466 Improve vanishing route line test.
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/TestHelper/Fixtures/multileg_route.json
  Sources/TestHelper/Fixtures/route-for-vanishing-route-line.json
  Sources/TestHelper/Fixtures/short_route.json
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
  Tests/MapboxNavigationTests/VanishingRouteLineTests.swift
Labels: blocked, improvement

#3599 Fix rendering issue with route preview stretchable route duration callouts
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: UI

#3605 Fix excessive padding on CarPlay during active navigation.
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Labels: bug, UI, CarPlay

#3610 Remove the usage of lineString.trimmed(from:to:) due to high calculation
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  Package.swift
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
Labels: improvement

#3611 Update Mapbox Navigation to `v2.1.0-rc.2`
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build

#3564 Implement the ability to highlight buildings during active-guidance on CarPlay.
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/BuildingHighlighting.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/Constants.swift
  Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift
  Sources/MapboxNavigation/NavigationViewController.swift
Labels: UI, CarPlay, improvement

#3613 Fix style change caused route line update delay.
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/MapboxNavigation/RouteLineController.swift
Labels: UI, CarPlay

#3616 Fix issues in zoom calculations for cases when maneuver is further away from the current location.
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationViewportDataSource.swift
Labels: topic: camera, UI

#3619 Cocoapods CI Job
  .circleci/config.yml
Labels: build, op-ex

#3261 Hybrid Router
  CHANGELOG.md
  Example/AppDelegate.swift
  Example/CustomViewController.swift
  Example/ViewController.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/Directions+RoutingProvider.swift
  Sources/MapboxCoreNavigation/Directions.swift
  Sources/MapboxCoreNavigation/HandlerFactory.swift
  Sources/MapboxCoreNavigation/LegacyRouteController.swift
  Sources/MapboxCoreNavigation/MapboxRoutingProvider.swift
  Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
  Sources/MapboxCoreNavigation/NavigationService.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/RouteProgress.swift
  Sources/MapboxCoreNavigation/Router.swift
  Sources/MapboxCoreNavigation/RoutingProvider.swift
  Sources/MapboxCoreNavigation/TilesetDescriptorFactory.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/JunctionView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/BillingHandlerTests.swift
  Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  Tests/MapboxCoreNavigationTests/NavigationEventsManagerTests.swift
  Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
  Tests/MapboxCoreNavigationTests/RouteControllerTests.swift
  Tests/MapboxCoreNavigationTests/TilesetDescriptorFactoryTests.swift
  Tests/MapboxNavigationTests/CarPlayManagerTests.swift
  Tests/MapboxNavigationTests/CarPlayNavigationViewControllerTests.swift
  Tests/MapboxNavigationTests/CarPlayUtils.swift
  Tests/MapboxNavigationTests/EndOfRouteFeedbackTests.swift
  Tests/MapboxNavigationTests/InstructionsCardCollectionTests.swift
  Tests/MapboxNavigationTests/LeaksSpec.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
  Tests/MapboxNavigationTests/SpeechSynthesizersControllerTests.swift
  Tests/MapboxNavigationTests/StepsViewControllerTests.swift
Labels: feature, backwards incompatible, Core

#3617 Update example to use course parameter for user location
  Example/ViewController.swift
Labels: improvement

#3622 Fix the congestion color missing issue of route line when refresh.
  CHANGELOG.md
  Sources/MapboxNavigation/Array.swift
  Sources/MapboxNavigation/Route.swift
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
Labels: bug, UI

#3623 Fix compilation warnings in example application after Hybrid Router introduction.
  Example/AppDelegate+CarPlay.swift
Labels: build

#3385 Add distance check to prevent vanishing route line update when users go off the route.
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Tests/MapboxNavigationTests/VanishingRouteLineTests.swift
Labels: bug, UI
