Repository mapbox/mapbox-navigation-ios, pull requests merged in 2022-02, with the labels that each got.

#3718 Fix `NavigationViewController` properties change.
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationViewController.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: bug, UI

#3721 Replace deprecated `Navigator.resetRideSession()` with `Navigator.reset()` methods.
  Tests/MapboxCoreNavigationTests/PassiveLocationManagerTests.swift
  Tests/MapboxNavigationTests/CarPlayManagerTests.swift
  Tests/MapboxNavigationTests/SpeechSynthesizersControllerTests.swift
Labels: op-ex

#3720 Fix floating buttons overlapping with iOS device notch when using right-to-left layout interfaces.
  Sources/MapboxNavigation/NavigationViewLayout.swift
Labels: bug, UI

#3700 Support to show and hide traffic data from V2 beta version tile set.
  CHANGELOG.md
  Sources/MapboxNavigation/MapView.swift
  Tests/MapboxNavigationTests/MapViewTests.swift
Labels: UI

#3724 Navigator deinitialization
  CHANGELOG.md
  Sources/MapboxCoreNavigation/BillingHandler.swift
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/HistoryRecording.swift
  Sources/MapboxCoreNavigation/PassiveLocationManager.swift
  Sources/MapboxCoreNavigation/PredictiveCacheManager.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/TestHelper/TestCase.swift
  Tests/MapboxCoreNavigationTests/BillingHandlerTests.swift
  Tests/MapboxCoreNavigationTests/PassiveLocationManagerTests.swift
  Tests/MapboxCoreNavigationTests/TilesetDescriptorFactoryTests.swift
  Tests/MapboxNavigationTests/CarPlayManagerTests.swift
  Tests/MapboxNavigationTests/SKUTests.swift
  Tests/MapboxNavigationTests/SpeechSynthesizersControllerTests.swift
Labels: Core

#3709 Give users the ability to modify `userInfo` dictionary in `CPRouteChoice` and `CPListItem`.
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/CPRouteChoice.swift
  Sources/MapboxNavigation/CPTrip.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlaySearchController+CPSearchTemplateDelegate.swift
  Sources/MapboxNavigation/Constants.swift
  Tests/MapboxNavigationTests/CarPlayManagerSpec.swift
  Tests/MapboxNavigationTests/CarPlayManagerTests.swift
  Tests/MapboxNavigationTests/CarPlayNavigationViewControllerTests.swift
  Tests/MapboxNavigationTests/CarPlayUtils.swift
Labels: bug, CarPlay

#3704 Instructions card improvements.
  CHANGELOG.md
  Example/ViewController+GuidanceCards.swift
  Example/ViewController+InstructionsCard.swift
  Example/ViewController.swift
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/BottomBannerViewLayout.swift
  Sources/MapboxNavigation/Constants+InstructionsCard.swift
  Sources/MapboxNavigation/Constants.swift
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/InstructionsBannerView.swift
  Sources/MapboxNavigation/InstructionsCardCell.swift
  Sources/MapboxNavigation/InstructionsCardCollectionDelegate.swift
  Sources/MapboxNavigation/InstructionsCardContainerView.swift
  Sources/MapboxNavigation/InstructionsCardContainerViewDelegate.swift
  Sources/MapboxNavigation/InstructionsCardView.swift
  Sources/MapboxNavigation/InstructionsCardViewController.swift
  Sources/MapboxNavigation/LanesView.swift
  Sources/MapboxNavigation/NextBannerView.swift
  Sources/MapboxNavigation/NightStyle.swift
  Sources/MapboxNavigation/UIStackView.swift
  Sources/MapboxNavigation/UIView.swift
  Sources/MapboxNavigation/VisualInstruction.swift
  Tests/MapboxNavigationTests/BottomBannerSnapshotTests.swift
  Tests/MapboxNavigationTests/InstructionsCardCollectionTests.swift
  Tests/MapboxNavigationTests/InstructionsCardSnapshotTests.swift
  Tests/MapboxNavigationTests/InstructionsCardViewControllerTests.swift
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/GuidanceCardsSnapshotTests/testLanesManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/GuidanceCardsSnapshotTests/testRegularManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/GuidanceCardsSnapshotTests/testTertiaryManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/InstructionsCardSnapshotTests/testLanesManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/InstructionsCardSnapshotTests/testRegularManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/InstructionsCardSnapshotTests/testTertiaryManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/GuidanceCardsSnapshotTests/testLanesManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/GuidanceCardsSnapshotTests/testRegularManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/GuidanceCardsSnapshotTests/testTertiaryManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/InstructionsCardSnapshotTests/testLanesManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/InstructionsCardSnapshotTests/testRegularManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/InstructionsCardSnapshotTests/testTertiaryManeuver.1.png
Labels: UI, improvement

#3734 Fix the route layers disappearing in preview mode when map style changes.
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: UI

#3729 Hide the remaining steps when user is on final step
  CHANGELOG.md
  Sources/MapboxNavigation/InstructionsBannerView.swift
  Sources/MapboxNavigation/TopBannerViewController.swift
Labels: UI

#3738 Navigator lifecycle bugfix
  CHANGELOG.md
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
Labels: bug, release blocker

#3713 Add the Sprite and Mapbox designed shield caching and retrieval mechanism.
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/SpriteInfoCache.swift
  Sources/MapboxNavigation/SpriteRepository.swift
  Sources/TestHelper/Fixtures/sprite-info.json
  Tests/MapboxNavigationTests/ImageLoadingURLProtocolSpy.swift
  Tests/MapboxNavigationTests/SpriteInfoCacheTests.swift
  Tests/MapboxNavigationTests/SpriteRepositoryTests.swift
Labels: feature

#3736 Fix building highlighting when changing style.
  CHANGELOG.md
  Example/ViewController+FreeDrive.swift
  Example/ViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/RouteLineController.swift
Labels: bug, UI

#3746 Expose waypoint and route detection methods publicly.
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: UI, improvement

#3748 Update NN to 88.0.0 and MapboxMaps to 10.3.0
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/MapboxRoutingProvider.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: build

#3717 Tileset profile configuration
  CHANGELOG.md
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/HandlerFactory.swift
  Sources/MapboxCoreNavigation/MapboxRoutingProvider.swift
  Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
  Sources/MapboxCoreNavigation/PassiveLocationManager.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/TilesetDescriptorFactory.swift
  Tests/MapboxCoreNavigationTests/TilesetDescriptorFactoryTests.swift
Labels: Core

#3731 Add `CarPlayManagerDelegate.carPlayManagerDidEndNavigation(_:byCanceling:)`.
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayManagerDelegate.swift
  Sources/MapboxNavigation/CarPlayNavigationViewControllerDelegate.swift
  Tests/MapboxNavigationTests/CarPlayManagerTests.swift
  Tests/MapboxNavigationTests/CarPlayUtils.swift
Labels: UI, CarPlay

#3750 Bump the API commit.
  .base_api
Labels: build

#3752 Update the CHANGELOG.
  CHANGELOG.md
Labels: documentation

#3723 Use Mapbox designed shield from status for road name labeling
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/CoreConstants.swift
  Sources/MapboxCoreNavigation/NavigationStatus.swift
  Sources/MapboxCoreNavigation/PassiveLocationManager.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/NavigationMapView+RoadNameLabeling.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/OrnamentsController.swift
  Sources/MapboxNavigation/SpriteInfoCache.swift
  Sources/MapboxNavigation/SpriteRepository.swift
  Sources/MapboxNavigation/UIImage.swift
  Sources/MapboxNavigation/WayNameView.swift
  Sources/TestHelper/Fixtures/Images.xcassets/shield-280.imageset/Contents.json
  Sources/TestHelper/Fixtures/Images.xcassets/shield-280.imageset/shield-280.png
  Tests/MapboxNavigationTests/Constants.swift
  Tests/MapboxNavigationTests/SpriteRepositoryTests.swift
  Tests/MapboxNavigationTests/WayNameViewTests.swift
Labels: feature

#3763 Remove FIXME statements that are no longer needed.
  Tests/MapboxCoreNavigationTests/BillingHandlerTests.swift
  Tests/MapboxCoreNavigationTests/RouteControllerTests.swift
Labels: op-ex

#3762 Update Mapbox Navigation to `v2.3.0-rc.2`.
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Package.resolved
  Package.swift
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build
