Repository mapbox/mapbox-navigation-ios, pull requests merged in 2022-09, with the labels that each got.

#4110 New Alternative Routes mechanism
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/AlternativeRoutesCenter.swift
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/RerouteControllerDelegate.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/RoutesCoordinator.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/RoutesCoordinatorTests.swift
Labels: release blocker

#4120 v2.7.2
  .circleci/config.yml
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/CLLocationCoordinate2D.swift
  Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift
  Sources/MapboxNavigation/NavigationMapView+CLLocationManagerDelegate.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/Route.swift
  Sources/MapboxNavigation/RouteLineType.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: build

#4119 v2.6.1
  .circleci/config.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/MapboxNavigation/NavigationMapView+CLLocationManagerDelegate.swift
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testDayDetailedFeedbackViewController.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testDayDetailedFeedbackViewController.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testDayFeedbackViewController.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testNightDetailedFeedbackViewController.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testNightDetailedFeedbackViewController.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testNightDetailedFeedbackViewController.3.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testNightDetailedFeedbackViewController.4.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testNightFeedbackViewController.1.png
Labels: build

#4123 Update changelog.
  CHANGELOG.md
Labels: build

#4112 Update the check for `circleLayer` for default route line position
  Sources/MapboxNavigation/NavigationMapView.swift
  Tests/MapboxNavigationTests/RouteLineLayerPositionTests.swift
Labels: UI

#4144 Update to NavNative v115, Maps v10.8.1, Common v23.0.0
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  Package.resolved
  Package.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: Core, dependencies

#4060 Improve `FloatingButton` styling.
  CHANGELOG.md
  Example/ViewController.swift
  Sources/MapboxNavigation/CameraController.swift
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/FloatingButton.swift
  Sources/MapboxNavigation/InstructionsCardViewController.swift
  Sources/MapboxNavigation/NavigationView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NightStyle.swift
  Sources/MapboxNavigation/OrnamentsController.swift
  Sources/MapboxNavigation/ReportButton.swift
  Sources/MapboxNavigation/Style.swift
  Sources/MapboxNavigation/UIImage.swift
  Sources/MapboxNavigation/UIView.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: UI

#4151 Remove MapboxEvents 1.0.9 from dependency
  Cartfile.resolved
Labels: build

#4147 Support the offline mode for shields in navigation
  CHANGELOG.md
  Sources/MapboxNavigation/ImageDownloader.swift
  Sources/MapboxNavigation/InstructionPresenter.swift
  Sources/MapboxNavigation/SpriteRepository.swift
  Sources/MapboxNavigation/TopBannerViewController.swift
  Sources/MapboxNavigation/WayNameLabel.swift
  Tests/MapboxNavigationTests/SpriteRepositoryTests.swift
Labels: UI

#4152 Renaming StatusPollingConfig
  CHANGELOG.md
  Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
  Sources/MapboxCoreNavigation/NavigationSettings.swift
Labels: needs cherry-picking

#4155 Cherry picks commits from 2.8.0
  CHANGELOG.md
  Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
  Sources/MapboxCoreNavigation/NavigationSettings.swift
Labels: build

#4158 Update version 2.9.0-alpha.1
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build

#4161 Replace symbolSet with symbolImage in CarPlay maneuver.
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/VisualInstruction.swift
Labels: UI, CarPlay, improvement

#4163 Add destination preview and routes preview banners.
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/BannerContainerView.swift
  Sources/MapboxNavigation/CameraModeFloatingButton.swift
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/DestinationDataSource.swift
  Sources/MapboxNavigation/DestinationOptions.swift
  Sources/MapboxNavigation/DestinationPreviewViewController.swift
  Sources/MapboxNavigation/DestinationPreviewViewControllerDelegate.swift
  Sources/MapboxNavigation/DestinationPreviewViewControllerLayout.swift
  Sources/MapboxNavigation/NavigationView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewLayout.swift
  Sources/MapboxNavigation/NightStyle.swift
  Sources/MapboxNavigation/RatingControl.swift
  Sources/MapboxNavigation/Resources/Assets.xcassets/back.imageset/Contents.json
  Sources/MapboxNavigation/Resources/Assets.xcassets/back.imageset/back.pdf
  Sources/MapboxNavigation/Resources/Assets.xcassets/pin.imageset/Contents.json
  Sources/MapboxNavigation/Resources/Assets.xcassets/pin.imageset/pin.pdf
  Sources/MapboxNavigation/Resources/Assets.xcassets/preview_overview.imageset/Contents.json
  Sources/MapboxNavigation/Resources/Assets.xcassets/preview_overview.imageset/preview_overview.pdf
  Sources/MapboxNavigation/Resources/Assets.xcassets/start.imageset/Contents.json
  Sources/MapboxNavigation/Resources/Assets.xcassets/start.imageset/start.pdf
  Sources/MapboxNavigation/Resources/Assets.xcassets/time.imageset/Contents.json
  Sources/MapboxNavigation/Resources/Assets.xcassets/time.imageset/time.pdf
  Sources/MapboxNavigation/ResumeButton.swift
  Sources/MapboxNavigation/RoutesPreviewDataSource.swift
  Sources/MapboxNavigation/RoutesPreviewOptions.swift
  Sources/MapboxNavigation/RoutesPreviewViewController.swift
  Sources/MapboxNavigation/RoutesPreviewViewControllerDelegate.swift
  Sources/MapboxNavigation/RoutesPreviewViewControllerLayout.swift
  Sources/MapboxNavigation/StylableButton.swift
  Sources/MapboxNavigation/StylableLabel.swift
  Sources/MapboxNavigation/UIColor.swift
  Sources/MapboxNavigation/UIImage.swift
Labels: UI, drop-in

#4142 Remove iOS 11 support.
  CHANGELOG.md
  Cartfile
  Cartfile.private
  Cartfile.resolved
  Example/ViewController.swift
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Package.resolved
  Package.swift
  README.md
  Sources/MapboxNavigation/AVAudioSession.swift
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/ExitView.swift
  Sources/MapboxNavigation/Feedback/FeedbackSubtypeCollectionViewCell.swift
  Sources/MapboxNavigation/GenericRouteShield.swift
  Sources/MapboxNavigation/InstructionPresenter.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Tests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  Tests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/xcshareddata/xcschemes/PodInstall.xcscheme
  Tests/CocoaPodsTest/PodInstall/Podfile
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: build

#4133 Add delegate methods for tapping route duration.
  CHANGELOG.md
  Example/ViewController.swift
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: UI

#3930 Replace ImageCache, DataCache with URLCache
  CHANGELOG.md
  CONTRIBUTING.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/Cache.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/ExitView.swift
  Sources/MapboxNavigation/GenericRouteShield.swift
  Sources/MapboxNavigation/ImageDownload.swift
  Sources/MapboxNavigation/ImageDownloader.swift
  Sources/MapboxNavigation/ImageRepository.swift
  Sources/MapboxNavigation/InstructionPresenter.swift
  Sources/MapboxNavigation/SpriteInfoCache.swift
  Sources/MapboxNavigation/SpriteRepository.swift
  Sources/MapboxNavigation/UIImage.swift
  Sources/MapboxNavigation/URLRequest.swift
  Sources/MapboxNavigation/WayNameLabel.swift
  Tests/MapboxNavigationTests/ImageDownloadOperationSpy.swift
  Tests/MapboxNavigationTests/ImageDownloaderTests.swift
  Tests/MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift
  Tests/MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift
  Tests/MapboxNavigationTests/SpriteInfoCacheTests.swift
  Tests/MapboxNavigationTests/SpriteRepositoryTests.swift
  Tests/MapboxNavigationTests/URLDataCacheTests.swift
  Tests/MapboxNavigationTests/WayNameViewTests.swift
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testAbbreviateInstructions.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testAbbreviateInstructionsIncludingDelimiter.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testAdjacentShields.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testMultilinePrimary.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testPrimaryShieldAndSecondary.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/15.0/InstructionsBannerViewSnapshotTests/testAbbreviateInstructions.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/15.0/InstructionsBannerViewSnapshotTests/testAbbreviateInstructionsIncludingDelimiter.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/15.0/InstructionsBannerViewSnapshotTests/testAdjacentShields.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/15.0/InstructionsBannerViewSnapshotTests/testMultilinePrimary.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/14.5/InstructionsBannerViewSnapshotTests/testAbbreviateInstructions.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/14.5/InstructionsBannerViewSnapshotTests/testAbbreviateInstructionsIncludingDelimiter.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/14.5/InstructionsBannerViewSnapshotTests/testAdjacentShields.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/14.5/InstructionsBannerViewSnapshotTests/testMultilinePrimary.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/14.5/InstructionsBannerViewSnapshotTests/testPrimaryShieldAndSecondary.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone14_3/15.2/InstructionsBannerViewSnapshotTests/testAbbreviateInstructions.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone14_3/15.2/InstructionsBannerViewSnapshotTests/testAbbreviateInstructionsIncludingDelimiter.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone14_3/15.2/InstructionsBannerViewSnapshotTests/testAdjacentShields.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone14_3/15.2/InstructionsBannerViewSnapshotTests/testMultilinePrimary.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone15_3/16.0/InstructionsBannerViewSnapshotTests/testAbbreviateInstructions.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone15_3/16.0/InstructionsBannerViewSnapshotTests/testAbbreviateInstructionsIncludingDelimiter.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone15_3/16.0/InstructionsBannerViewSnapshotTests/testAdjacentShields.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone15_3/16.0/InstructionsBannerViewSnapshotTests/testMultilinePrimary.1.png
Labels: op-ex, topic: instructions, topic: voice, UI
