Repository mapbox/mapbox-navigation-ios, pull requests merged in 2022-12, with the labels that each got.

#4285 Show `UserHaloCourseView` only when `NavigationMapview.reducedAccuracyActivatedMode` is true under reducedAccuracy mode
  CHANGELOG.md
  MapboxNavigationTests/MapboxNavigationTests.swift
  MapboxNavigationTests/__Snapshots__/iPhone14_5/15.5/MapboxNavigationTests/testUserLocationStyle.4.png
  MapboxNavigationTests/__Snapshots__/iPhone14_5/15.5/MapboxNavigationTests/testUserLocationStyle.6.png
  MapboxNavigationTests/__Snapshots__/iPhone14_5/15.5/MapboxNavigationTests/testUserLocationStyle.7.png
  MapboxNavigationTests/__Snapshots__/iPhone14_5/15.5/MapboxNavigationTests/testUserLocationStyle.8.png
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: UI

#4130 RouteDurations text centered in callout
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView+Annotations.swift
Labels: UI, bug :beetle:

#4277 Add delegate method to modify the layers that will be added to NavigationMapView during navigation
  CHANGELOG.md
  Example/ViewController.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayManagerDelegate.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayMapViewControllerDelegate.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewControllerDelegate.swift
  Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationMapViewDelegate.swift
  Sources/MapboxNavigation/NavigationViewController+NavigationMapViewDelegate.swift
  Sources/MapboxNavigation/NavigationViewControllerDelegate.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: UI

#4291 Bump api
  .base_api
Labels: build

#4280 Fix logic that resolves current version of NavSDK in runtime
  CHANGELOG.md
  MapboxCoreNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Package.swift
  Sources/MapboxCoreNavigation/Bundle+SDKVersion.swift
  Sources/MapboxCoreNavigation/BundleAdditions.swift
  Sources/MapboxCoreNavigation/EventDetails.swift
  Sources/MapboxCoreNavigation/Feedback/NavigationEventsManager.swift
  Sources/MapboxCoreNavigation/LegacyRouteController.swift
  Sources/MapboxCoreNavigation/NavigationService.swift
  Sources/MapboxCoreNavigation/Resources/MBXInfo.plist
  Sources/MapboxCoreNavigation/URLSession.swift
  Sources/MapboxNavigation/Resources/MBXInfo.plist
  scripts/update-version.sh
Labels: bug, release blocker

#4312 Fix the continuous routes remain in routes preview
  Example/ViewController.swift
Labels: UI, Apps

#4315 Update Maps to v10.10.1 to fix CarPlay map view not loading issue in active navigation session
  CHANGELOG.md
  Cartfile
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  Package.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: CarPlay
