Repository mapbox/mapbox-navigation-ios, pull requests merged in 2022-08, with the labels that each got.

#4044 Update dependency to NavNative v111.0, Maps v10.7.0, Common v22.1.0
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  Package.swift
  Sources/MapboxCoreNavigation/MapboxRoutingProvider.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: dependencies

#4039 Fix styling issues on iPads when using `DayStyle` and `NightStyle`.
  CHANGELOG.md
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/NightStyle.swift
  Sources/MapboxNavigation/Style.swift
  Sources/MapboxNavigation/StyleManager.swift
  Sources/MapboxNavigation/UIColor.swift
Labels: UI, CarPlay

#4034 Fix the building highlighting loss after out of map boundary and rerouting
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/CLLocationCoordinate2D.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxNavigation/CGPoint.swift
  Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: UI

#4030 Add method to update the route line position.
  CHANGELOG.md
  Sources/MapboxNavigation/MapView.swift
  Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
Labels: UI

#4049 Fix injected map view layout bug
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationView.swift
Labels: needs cherry-picking

#4048 Update dependencies for `release-v2.4`.
  CHANGELOG.md
  Cartfile.resolved
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxNavigationTests/VanishingRouteLineTests.swift
Labels: bug, build

#4058 Simulation teleport fix
  CHANGELOG.md
  Sources/MapboxCoreNavigation/SimulatedLocationManager.swift
Labels: bug, release blocker

#4059 vk-simulation-teleport-fix cherry-pick
  CHANGELOG.md
  Sources/MapboxCoreNavigation/SimulatedLocationManager.swift
Labels: bug

#4056 Mapbox Navigation `v2.4.2`.
  .circleci/config.yml
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Package.resolved
  Package.swift
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
Labels: build

#4054 Update `release-v2.5` branch to pin to Mapbox Common `v21.3.0`.
  .circleci/config.yml
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example-CarPlay.xcscheme
  MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
  Package.resolved
  Package.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: build, release blocker

#4064 Mapbox Navigation `v2.5.3`.
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
Labels: build

#4061 Add routing profile switcher to example application
  Example/ViewController.swift
Labels: op-ex, feature, documentation

#4070 Constraint the following distance after current maneuver for camera.
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationViewportDataSource.swift
Labels: topic: camera, UI

#4062 Fix the route line layer position issue after rerouting.
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  Example/CustomViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/NavigationMapView+ContinuousAlternatives.swift
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/RouteLineController.swift
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
Labels: UI

#4083 Mapbox Navigation `v2.7.0`.
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build

#4078 Duplicate departure events fix
  Sources/MapboxCoreNavigation/Feedback/NavigationEventsManager.swift
  Sources/MapboxCoreNavigation/NavigationService.swift
Labels: bug

#4076 Remove redundant iOS 11 availability macros
  Sources/MapboxNavigation/Feedback/FeedbackSubtypeViewController.swift
  Sources/MapboxNavigation/NSAttributedString.swift
  Sources/MapboxNavigation/UIView.swift
Labels: op-ex

#4086 Update the custom style example for styling.
  Example/CustomStyles.swift
Labels: UI

#4084 Default route line layer positioning skips circle layers being used as symbol layers.
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/NavigationMapView.swift
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
  Tests/MapboxNavigationTests/RouteLineLayerPositionTests.swift
Labels: UI

#4085 Upgrade dependencies
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadGraphEdgeMetadata.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObject.swift
  Tests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: build

#4087 v2.8.0-alpha.3
  CHANGELOG.md
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build

#4090 Remove the targetCoordinates mapping after reroute with the dependency upgrade
  Sources/MapboxCoreNavigation/RouteController.swift
Labels: Core

#4093 IncidentsOptions init
  Sources/MapboxCoreNavigation/IncidentsOptions.swift
Labels: bug

#4097 Update the example to use Electronic Horizon for free drive.
  Example/ViewController+FreeDrive.swift
Labels: UI

#4098 Use `MapView.safeAreaInsets` as a viewport padding in free-drive navigation.
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationViewportDataSource.swift
Labels: UI, CarPlay

#4106 Add traversed route line layer to customize `traversedRouteColor`
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/Route.swift
  Sources/MapboxNavigation/RouteLineType.swift
  Tests/MapboxNavigationTests/RouteLineLayerPositionTests.swift
Labels: UI

#4091 Add test application for SPM.
  .circleci/config.yml
  Tests/SPMTest/UISPMTest/UISPMTest.xcodeproj/project.pbxproj
  Tests/SPMTest/UISPMTest/UISPMTest.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Tests/SPMTest/UISPMTest/UISPMTest/AppDelegate.swift
  Tests/SPMTest/UISPMTest/UISPMTest/Assets.xcassets/AccentColor.colorset/Contents.json
  Tests/SPMTest/UISPMTest/UISPMTest/Assets.xcassets/AppIcon.appiconset/Contents.json
  Tests/SPMTest/UISPMTest/UISPMTest/Assets.xcassets/Contents.json
  Tests/SPMTest/UISPMTest/UISPMTest/Base.lproj/LaunchScreen.storyboard
  Tests/SPMTest/UISPMTest/UISPMTest/Base.lproj/Main.storyboard
  Tests/SPMTest/UISPMTest/UISPMTest/Info.plist
  Tests/SPMTest/UISPMTest/UISPMTest/SceneDelegate.swift
  Tests/SPMTest/UISPMTest/UISPMTest/ViewController.swift
  Tests/SPMTest/UISPMTest/project.yml
  scripts/validate_releases.sh
Labels: build

#4109 Remove the hashable extension for `CLLocationCoordinate2D`
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/CLLocationCoordinate2D.swift
  Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: Core, needs cherry-picking

#4114 Fix location authorization on iOS 13 and lower
  .circleci/config.yml
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView+CLLocationManagerDelegate.swift
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/BottomBannerSnapshotTests/testBottomBannerViewController.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/BottomBannerSnapshotTests/testBottomBannerViewControllerNoSafeArea.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/CarPlayCompassViewSnapshotTests/testCarPlayCompassView.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/CarPlayCompassViewSnapshotTests/testCarPlayCompassView.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testDayDetailedFeedbackViewController.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testDayDetailedFeedbackViewController.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testDayFeedbackViewController.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testNightDetailedFeedbackViewController.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testNightDetailedFeedbackViewController.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testNightDetailedFeedbackViewController.3.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testNightDetailedFeedbackViewController.4.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testNightFeedbackViewController.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testAbbreviateInstructions.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testAbbreviateInstructionsIncludingDelimiter.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testAbbreviateWestFremontAvenue.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testAdjacentShields.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testExitShields.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testGenericShieldAndExitViewWithCustomDayStyle.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testGenericShields.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testInstructionsAndNextInstructions.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testLongDistance.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testMultilinePrimary.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testPrimaryShieldAndSecondary.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testSinglelinePrimary.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testSinglelinePrimaryAndSecondary.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testSinglelinePrimaryAndSecondaryWithNightShield.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testSinglelinePrimaryAndSecondaryWithShield.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testSweEngLongDistance.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testUkrainianLongDistance.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsCardSnapshotTests/testLanesManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsCardSnapshotTests/testRegularManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsCardSnapshotTests/testTertiaryManeuver.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/LaneSnapshotTests/verifyAllLanes-size.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/LaneSnapshotTests/verifyAllLanes-size.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/ManeuverArrowSnapshotTests/testManeuverArrowHandlesWaypointsCorrectly.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/ManeuverViewSnapshotTests/testArrive.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/ManeuverViewSnapshotTests/testArriveNone.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/ManeuverViewSnapshotTests/testLeftUTurn.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/ManeuverViewSnapshotTests/testMergeRight.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/ManeuverViewSnapshotTests/testRightUTurn.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/ManeuverViewSnapshotTests/testRoundabout.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/ManeuverViewSnapshotTests/testRoundaboutTurnLeft.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/ManeuverViewSnapshotTests/testStraightRoundabout.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/ManeuverViewSnapshotTests/testTurnRight.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/ManeuverViewSnapshotTests/testTurnSlightRight.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/UserHaloCourseViewSnapshotTests/testUserHaloCourseView.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/UserHaloCourseViewSnapshotTests/testUserHaloCourseViewColorWhenChangingAppearance.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/UserHaloCourseViewSnapshotTests/testUserHaloCourseViewColorWhenChangingAppearance.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/UserHaloCourseViewSnapshotTests/testUserHaloCourseViewMultipleDrawCycles.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/UserHaloCourseViewSnapshotTests/testUserHaloCourseViewMultipleDrawCycles.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewFillAndShadowColorWhenChangingAppearance.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewFillAndShadowColorWhenChangingAppearance.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewPuckColorWhenChangingAppearance.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewPuckColorWhenChangingAppearance.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewScale.1.png
Labels: needs cherry-picking
