Repository mapbox/mapbox-navigation-ios, pull requests merged in 2022-07, with the labels that each got.

#3980 Mapbox Navigation `v2.6.0-rc.2`.
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build

#3985 Catch-up with `release-v2.6` branch.
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build

#3971 Add snapshot test for FeedbackViewController.
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/Feedback/FeedbackSubtypeCollectionViewCell.swift
  Sources/TestHelper/NavigationEventsManagerTestDoubles.swift
  Tests/MapboxNavigationTests/FeedbackViewControllerSnapshotTests.swift
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testDayDetailedFeedbackViewController.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testDayDetailedFeedbackViewController.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testDayFeedbackViewController.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testNightDetailedFeedbackViewController.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testNightDetailedFeedbackViewController.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testNightDetailedFeedbackViewController.3.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testNightDetailedFeedbackViewController.4.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/FeedbackViewControllerSnapshotTests/testNightFeedbackViewController.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/14.5/FeedbackViewControllerSnapshotTests/testDayDetailedFeedbackViewController.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/14.5/FeedbackViewControllerSnapshotTests/testDayDetailedFeedbackViewController.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/14.5/FeedbackViewControllerSnapshotTests/testDayFeedbackViewController.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/14.5/FeedbackViewControllerSnapshotTests/testNightDetailedFeedbackViewController.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/14.5/FeedbackViewControllerSnapshotTests/testNightDetailedFeedbackViewController.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/14.5/FeedbackViewControllerSnapshotTests/testNightDetailedFeedbackViewController.3.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/14.5/FeedbackViewControllerSnapshotTests/testNightDetailedFeedbackViewController.4.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/14.5/FeedbackViewControllerSnapshotTests/testNightFeedbackViewController.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone14_3/15.2/FeedbackViewControllerSnapshotTests/testDayDetailedFeedbackViewController.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone14_3/15.2/FeedbackViewControllerSnapshotTests/testDayDetailedFeedbackViewController.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone14_3/15.2/FeedbackViewControllerSnapshotTests/testDayFeedbackViewController.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone14_3/15.2/FeedbackViewControllerSnapshotTests/testNightDetailedFeedbackViewController.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone14_3/15.2/FeedbackViewControllerSnapshotTests/testNightDetailedFeedbackViewController.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone14_3/15.2/FeedbackViewControllerSnapshotTests/testNightDetailedFeedbackViewController.3.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone14_3/15.2/FeedbackViewControllerSnapshotTests/testNightDetailedFeedbackViewController.4.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone14_3/15.2/FeedbackViewControllerSnapshotTests/testNightFeedbackViewController.1.png
Labels: UI

#3987 Fix an issue where maneuver arrow wasn't removed after passing visual instruction on CarPlay.
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Labels: bug, UI

#3988 Hide user course view in case if current user location coordinate point is invalid.
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: bug, UI

#3990 Mapbox Navigation `v2.6.0`.
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Package.resolved
  Package.swift
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build

#3995 Mapbox Navigation `v2.5.2`.
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
Labels: build

#3978 Update dependencies.
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/CustomViewController.swift
  Example/ViewController+FreeDrive.swift
  Example/ViewController.swift
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  Package.resolved
  Package.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/RouteLineController.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxNavigationTests/MapViewTests.swift
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
Labels: build

#3997 Catch-up with `release-v2.6` branch.
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Package.resolved
  Package.swift
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build

#3981 Mapbox Navigation `v2.7.0-alpha.1`.
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation.podspec
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build

#3973 Exposing sensor data usage toggle
  CHANGELOG.md
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
  Sources/MapboxCoreNavigation/NavigationSettings.swift
  Sources/MapboxCoreNavigation/RerouteController.swift
Labels: platform parity, Core, improvement

#3999 Stop using deprecated methods from Maps SDK in snapshot tests.
  MapboxNavigationTests/MapboxNavigationTests.swift
Labels: build

#3993 Simulation improvement
  Sources/MapboxCoreNavigation/SimulatedLocationManager.swift
  Sources/TestHelper/Fixture.swift
  Tests/MapboxCoreNavigationTests/SimulatedLocationManagerTests.swift
Labels: bug, Core

#3992 Fix the route line updated ahead of user location in short straight-line route step.
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/TestHelper/Fixtures/route-with-straight-line.json
  Tests/MapboxNavigationTests/VanishingRouteLineTests.swift
Labels: UI

#4004 Improve public API of `WayNameView`.
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/InstructionPresenter.swift
  Sources/MapboxNavigation/NavigationView.swift
  Sources/MapboxNavigation/NavigationViewLayout.swift
  Sources/MapboxNavigation/NightStyle.swift
  Sources/MapboxNavigation/SpriteRepository.swift
  Sources/MapboxNavigation/UILayoutGuide.swift
  Sources/MapboxNavigation/WayNameLabel.swift
  Sources/MapboxNavigation/WayNameView.swift
  Tests/MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift
  Tests/MapboxNavigationTests/SpriteRepositoryTests.swift
Labels: op-ex, UI, drop-in

#3998 Pause the update of free drive in CarPlay after active navigation session starts
  Sources/MapboxNavigation/CarPlayManager.swift
Labels: UI, CarPlay

#4009 Use `line-trim-offset` to replace the line gradient stops for route line update.
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
  Tests/MapboxNavigationTests/VanishingRouteLineTests.swift
Labels: UI

#4015 Fix the typo of #4009
  Sources/MapboxNavigation/NavigationMapView.swift
  Tests/MapboxNavigationTests/VanishingRouteLineTests.swift
Labels: improvement

#3996 Provide the ability to modify certain `ResumeButton` properties.
  CHANGELOG.md
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/NightStyle.swift
  Sources/MapboxNavigation/ResumeButton.swift
Labels: UI

#4017 Add expansion/collapsing and animated presentation APIs for banner containers.
  Example/ViewController.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/NavigationServiceDelegate.swift
  Sources/MapboxNavigation/BannerContainerView.swift
  Sources/MapboxNavigation/BannerContainerViewDelegate.swift
  Sources/MapboxNavigation/BannerView.swift
  Sources/MapboxNavigation/BottomBannerViewController.swift
  Sources/MapboxNavigation/BottomBannerViewControllerDelegate.swift
  Sources/MapboxNavigation/BottomBannerViewControllerLayout.swift
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/NavigationView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewLayout.swift
  Sources/MapboxNavigation/NightStyle.swift
  Sources/MapboxNavigation/OrnamentsController.swift
  Sources/MapboxNavigation/TopBannerViewController.swift
  Sources/MapboxNavigation/UIViewController.swift
  Tests/MapboxNavigationTests/BottomBannerSnapshotTests.swift
  Tests/MapboxNavigationTests/InstructionsCardSnapshotTests.swift
  Tests/MapboxNavigationTests/InstructionsCardViewControllerTests.swift
  Tests/MapboxNavigationTests/XCTestCase.swift
Labels: UI

#4013 Fix status bar appearance.
  Sources/MapboxNavigation/DayStyle.swift
Labels: bug, UI

#4020 Only clear Sprite cache when style changes.
  CHANGELOG.md
  Sources/MapboxNavigation/SpriteRepository.swift
Labels: UI, improvement

#4012 Update dependencies.
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/EHorizon/OpenLRIdentifier.swift
  Sources/MapboxCoreNavigation/EHorizon/OpenLROrientation.swift
  Sources/MapboxCoreNavigation/EHorizon/OpenLRSideOfRoad.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectMatcher.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: build

#4021 v2.7.0-beta.2 release
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build

#4024 Only set initial maneuver avoidance radius when driving
  CHANGELOG.md
  Sources/MapboxCoreNavigation/Router.swift
Labels: bug, Core

#4029 Fix crash that sometimes occurs during `NavigationViewController` dismissal.
  CHANGELOG.md
  Sources/MapboxNavigation/RouteLineController.swift
Labels: bug

#4022 Add custom `NavigationViewController` transitions.
  CHANGELOG.md
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  NavigationViewExample/AppDelegate.swift
  NavigationViewExample/Base.lproj/LaunchScreen.storyboard
  NavigationViewExample/Base.lproj/Main.storyboard
  NavigationViewExample/Info.plist
  NavigationViewExample/SceneDelegate.swift
  NavigationViewExample/Transitions/DismissalAnimator.swift
  NavigationViewExample/Transitions/PresentationAnimator.swift
  NavigationViewExample/ViewController.swift
  Sources/MapboxNavigation/CameraController.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewDelegate.swift
Labels: UI

#4040 Remove arrow if the route line is removed after arrival
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/MapboxNavigation/RouteLineController.swift
Labels: UI
