Repository mapbox/mapbox-navigation-ios, pull requests merged in 2022-10, with the labels that each got.

#4186 Convert MatchOptions to RouteOptions on the fly
  CHANGELOG.md
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/Router.swift
  Sources/MapboxNavigation/CarPlayManager.swift
Labels: bug, Core

#4187 Update version to 2.8.1
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
Labels: build

#4143 Switch to night style when Dark Mode is enabled
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationViewController.swift
Labels: topic: design, feature, UI

#4197 Fix the issue of invisible exit views from night mode to day mode.
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: UI

#4193 Fix the intersections property loss after route refresh.
  CHANGELOG.md
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/RouteLegProgress.swift
  Sources/MapboxCoreNavigation/RouteProgress.swift
  Sources/MapboxCoreNavigation/RouteStepProgress.swift
Labels: Core

#4199 Bump base api
  .base_api
Labels: Core

#4205 Localize map labels into user-preferred languages
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: bug, topic: localization

#3642 Fix playback issues, while playing music, re-routing sound and voice instruction at the same time.
  CHANGELOG.md
  Sources/MapboxNavigation/MapboxSpeechSynthesizer.swift
  Sources/MapboxNavigation/RouteVoiceController.swift
Labels: bug, UI

#4185 Add intersection signals along current route.
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/NavigationMapView+Annotations.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationMapViewIdentifiers.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/Resources/Assets.xcassets/RoadIntersections/Contents.json
  Sources/MapboxNavigation/Resources/Assets.xcassets/RoadIntersections/RailroadCrossingDay.imageset/Contents.json
  Sources/MapboxNavigation/Resources/Assets.xcassets/RoadIntersections/RailroadCrossingDay.imageset/RailroadCrossingDay.pdf
  Sources/MapboxNavigation/Resources/Assets.xcassets/RoadIntersections/RailroadCrossingNight.imageset/Contents.json
  Sources/MapboxNavigation/Resources/Assets.xcassets/RoadIntersections/RailroadCrossingNight.imageset/RailroadCrossingNight.pdf
  Sources/MapboxNavigation/Resources/Assets.xcassets/RoadIntersections/StopSignDay.imageset/Contents.json
  Sources/MapboxNavigation/Resources/Assets.xcassets/RoadIntersections/StopSignDay.imageset/StopSignDay.pdf
  Sources/MapboxNavigation/Resources/Assets.xcassets/RoadIntersections/StopSignNight.imageset/Contents.json
  Sources/MapboxNavigation/Resources/Assets.xcassets/RoadIntersections/StopSignNight.imageset/StopSignNight.pdf
  Sources/MapboxNavigation/Resources/Assets.xcassets/RoadIntersections/TrafficSignalDay.imageset/Contents.json
  Sources/MapboxNavigation/Resources/Assets.xcassets/RoadIntersections/TrafficSignalDay.imageset/TrafficSignalDay.pdf
  Sources/MapboxNavigation/Resources/Assets.xcassets/RoadIntersections/TrafficSignalNight.imageset/Contents.json
  Sources/MapboxNavigation/Resources/Assets.xcassets/RoadIntersections/TrafficSignalNight.imageset/TrafficSignalNight.pdf
  Sources/MapboxNavigation/Resources/Assets.xcassets/RoadIntersections/YieldSignDay.imageset/Contents.json
  Sources/MapboxNavigation/Resources/Assets.xcassets/RoadIntersections/YieldSignDay.imageset/YieldSignDay.pdf
  Sources/MapboxNavigation/Resources/Assets.xcassets/RoadIntersections/YieldSignNight.imageset/Contents.json
  Sources/MapboxNavigation/Resources/Assets.xcassets/RoadIntersections/YieldSignNight.imageset/YieldSignNight.pdf
  Sources/MapboxNavigation/RouteLineController.swift
  Sources/MapboxNavigation/String.swift
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
  Tests/MapboxNavigationTests/RouteLineLayerPositionTests.swift
  taginfo.json
Labels: UI

#4210 Add "created" field to passive navigation feedback events
  Sources/MapboxCoreNavigation/PassiveNavigationEventDetails.swift
Labels: release blocker

#4212 Add `backTitle` property to `BannerDismissalViewController`
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/BannerDismissalViewController.swift
  Sources/MapboxNavigation/BannerDismissalViewControllerLayout.swift
  Tests/MapboxNavigationTests/BannerDismissalViewControllerSnapshotTests.swift
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/BannerDismissalViewControllerSnapshotTests/testBannerDismissalViewControllerDayStyle.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/BannerDismissalViewControllerSnapshotTests/testBannerDismissalViewControllerNightStyle.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/15.0/BannerDismissalViewControllerSnapshotTests/testBannerDismissalViewControllerDayStyle.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/15.0/BannerDismissalViewControllerSnapshotTests/testBannerDismissalViewControllerNightStyle.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/14.5/BannerDismissalViewControllerSnapshotTests/testBannerDismissalViewControllerDayStyle.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/14.5/BannerDismissalViewControllerSnapshotTests/testBannerDismissalViewControllerNightStyle.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone14_3/15.2/BannerDismissalViewControllerSnapshotTests/testBannerDismissalViewControllerDayStyle.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone14_3/15.2/BannerDismissalViewControllerSnapshotTests/testBannerDismissalViewControllerNightStyle.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone15_3/16.0/BannerDismissalViewControllerSnapshotTests/testBannerDismissalViewControllerDayStyle.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone15_3/16.0/BannerDismissalViewControllerSnapshotTests/testBannerDismissalViewControllerNightStyle.1.png
Labels: UI

#4217 Fix the gradient feature for route line without congestion.
  CHANGELOG.md
  MapboxNavigationTests/MapboxNavigationTests.swift
  MapboxNavigationTests/__Snapshots__/iPhone14_5/15.5/MapboxNavigationTests/testMultiLegRouteWithoutCongestion.1.png
  Sources/MapboxNavigation/Route.swift
Labels: UI

#4219 Migrate to Transifex API v3
  .tx/config
  Sources/MapboxNavigation/Resources/es-ES.lproj/Localizable.stringsdict
  Sources/MapboxNavigation/Resources/es.lproj/Localizable.stringsdict
  Sources/MapboxNavigation/Resources/fr.lproj/Localizable.stringsdict
  Sources/MapboxNavigation/Resources/vi.lproj/Localizable.strings
Labels: topic: localization
