Repository mapbox/mapbox-navigation-ios, pull requests merged in 2022-03, with the labels that each got.

#3769 Remove the gap between `EndOfRouteViewController` view and screen bottom.
  CHANGELOG.md
  Sources/MapboxNavigation/EndOfRouteViewController.swift
  Sources/MapboxNavigation/NavigationView.swift
Labels: UI

#3760 Allow the leg separator view in StepsViewController updated with style.
  CHANGELOG.md
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/NightStyle.swift
  Sources/MapboxNavigation/StepsViewController.swift
Labels: UI

#3770 Add swipeable bottom banner container view.
  Sources/MapboxNavigation/BottomBannerViewControllerLayout.swift
  Sources/MapboxNavigation/NavigationView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewLayout.swift
  Sources/MapboxNavigation/OrnamentsController.swift
Labels: UI, drop-in

#3782 Fix ImageDownloader memory leak
  CHANGELOG.md
  Sources/MapboxNavigation/ImageDownloader.swift
  Sources/MapboxNavigation/URLSessionDelegateProxy.swift
Labels: bug, op-ex

#3781 Use current location for route refresh
  CHANGELOG.md
  Sources/MapboxCoreNavigation/Router.swift
Labels: bug, topic: location

#3777 Support the style change of the road shield color.
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/NightStyle.swift
Labels: UI

#3776 Align the margin of floating buttons with map attribution button during active navigation.
  CHANGELOG.md
  Sources/MapboxNavigation/OrnamentsController.swift
Labels: UI

#3764 Support the style change of `FeedbackViewController` during active navigation
  CHANGELOG.md
  Example/ViewController+StyleManager.swift
  Example/ViewController.swift
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/Feedback/FeedbackViewController.swift
  Sources/MapboxNavigation/NightStyle.swift
  Sources/MapboxNavigation/StyleManager.swift
Labels: UI

#3747 Customizing SpeechSynthesizer
  CHANGELOG.md
  Sources/MapboxNavigation/MapboxSpeechSynthesizer.swift
  Tests/MapboxNavigationTests/SpeechSynthesizersControllerTests.swift
Labels: Core, improvement

#3785 Stop previewing when swipe to current banner.
  CHANGELOG.md
  Example/CustomViewController.swift
  Sources/MapboxNavigation/InstructionsCardViewController.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/TopBannerViewController.swift
Labels: UI

#3765 Upgrade to MapboxMaps `v10.4.0-rc.1`, MapboxNavigationNative `v92.0.0`.
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/EHorizon/RoadObjectKind.swift
  Sources/MapboxCoreNavigation/MapboxRoutingProvider.swift
  Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
  Sources/MapboxCoreNavigation/NavigationRouteOptions.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/RoutesCoordinator.swift
  Tests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/RoutesCoordinatorTests.swift
  Tests/MapboxCoreNavigationTests/TilesetDescriptorFactoryTests.swift
  Tests/MapboxNavigationTests/MapViewTests.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
Labels: build

#3757 Drop-in UI rework.
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/BannerView.swift
  Sources/MapboxNavigation/Date.swift
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/DistanceLabel.swift
  Sources/MapboxNavigation/FloatingButton.swift
  Sources/MapboxNavigation/HighlightedButton.swift
  Sources/MapboxNavigation/InstructionLabel.swift
  Sources/MapboxNavigation/LineView.swift
  Sources/MapboxNavigation/ManeuverContainerView.swift
  Sources/MapboxNavigation/MarkerView.swift
  Sources/MapboxNavigation/NightStyle.swift
  Sources/MapboxNavigation/ProgressBar.swift
  Sources/MapboxNavigation/ReportButton.swift
  Sources/MapboxNavigation/ResumeButton.swift
  Sources/MapboxNavigation/SeparatorView.swift
  Sources/MapboxNavigation/Solar.swift
  Sources/MapboxNavigation/StepListIndicatorView.swift
  Sources/MapboxNavigation/StylableButton.swift
  Sources/MapboxNavigation/StylableLabel.swift
  Sources/MapboxNavigation/StylableTextView.swift
  Sources/MapboxNavigation/StylableView.swift
  Sources/MapboxNavigation/Style.swift
  Sources/MapboxNavigation/StyleManager.swift
  Sources/MapboxNavigation/StyleManagerDelegate.swift
  Sources/MapboxNavigation/SubtitleLabel.swift
  Sources/MapboxNavigation/TitleLabel.swift
  Sources/MapboxNavigation/UIColor.swift
  Sources/MapboxNavigation/UIFont.swift
  Sources/MapboxNavigation/VisualInstructionDelegate.swift
Labels: UI, drop-in

#3792 Improve `SpriteRepository` update under poor network connection.
  CHANGELOG.md
  Sources/MapboxNavigation/SpriteInfoCache.swift
  Sources/MapboxNavigation/SpriteRepository.swift
  Sources/MapboxNavigation/VisualInstructionComponent.swift
  Sources/MapboxNavigation/WayNameView.swift
  Tests/MapboxNavigationTests/SpriteInfoCacheTests.swift
  Tests/MapboxNavigationTests/SpriteRepositoryTests.swift
  Tests/MapboxNavigationTests/WayNameViewTests.swift
Labels: UI, improvement

#3796 Add lazy initialization of Navigator.shared in RouteController
  CHANGELOG.md
  Sources/MapboxCoreNavigation/RouteController.swift
Labels: bug

#3797 Migrate the pull request template.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#3794 Fix crash related to templates dismissal on CarPlay.
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayManager.swift
Labels: UI, CarPlay

#3798 Allow SpeedLimitView to display unknown speed limit values
  CHANGELOG.md
  Sources/MapboxNavigation/SpeedLimitView.swift
Labels: feature, UI

#3801 Upgrade to MapboxNavigationNative `v93.0.0`
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: build

#3803 Update Mapbox Navigation to `v2.4.0-beta.3`
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build

#3802 Mapbox Navigation SDK `v2.3.1`.
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
Labels: build

#3744 Fix issues related to `routeLineTracksTraversal` usage and custom delegate methods for route line modification.
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  Sources/MapboxCoreNavigation/RouteProgress.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayManagerDelegate.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayMapViewControllerDelegate.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewControllerDelegate.swift
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationMapViewDelegate.swift
  Sources/MapboxNavigation/NavigationViewControllerDelegate.swift
  Sources/MapboxNavigation/UIColor.swift
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
  Tests/MapboxNavigationTests/VanishingRouteLineTests.swift
Labels: bug, UI, CarPlay

#3791 HistoryRecording instance-based methods
  CHANGELOG.md
  Sources/MapboxCoreNavigation/HistoryRecording.swift
Labels: Core
