Repository mapbox/mapbox-navigation-ios, pull requests merged in 2022-05, with the labels that each got.

#3862 MapboxNavigationNative v98.0.0
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: build

#3754 Reroute Controller integration
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  Example/AppDelegate.swift
  Example/CustomViewController.swift
  Example/ViewController.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/LegacyRouteController.swift
  Sources/MapboxCoreNavigation/MapboxRoutingProvider.swift
  Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
  Sources/MapboxCoreNavigation/NavigationService.swift
  Sources/MapboxCoreNavigation/NavigationSettings.swift
  Sources/MapboxCoreNavigation/RerouteController.swift
  Sources/MapboxCoreNavigation/RerouteControllerDelegate.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/Router.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewControllerDelegate.swift
  Tests/MapboxCoreNavigationTests/BillingHandlerTests.swift
  Tests/MapboxCoreNavigationTests/LeakTests.swift
  Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
  Tests/MapboxCoreNavigationTests/NavigationEventsManagerTests.swift
  Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
  Tests/MapboxCoreNavigationTests/RouteControllerTests.swift
  Tests/MapboxNavigationTests/CarPlayManagerSpec.swift
  Tests/MapboxNavigationTests/CarPlayManagerTests.swift
  Tests/MapboxNavigationTests/CarPlayNavigationViewControllerTests.swift
  Tests/MapboxNavigationTests/CarPlayUtils.swift
  Tests/MapboxNavigationTests/EndOfRouteFeedbackTests.swift
  Tests/MapboxNavigationTests/InstructionsCardViewControllerTests.swift
  Tests/MapboxNavigationTests/LeaksTests.swift
  Tests/MapboxNavigationTests/NavigationViewControllerTests.swift
  Tests/MapboxNavigationTests/SpeechSynthesizersControllerTests.swift
  Tests/MapboxNavigationTests/StepsViewControllerTests.swift
Labels: Core, improvement

#3866 v2.4.1
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
Labels: build

#3864 Use the singleton of `SpriteRepository` for instructions and road name label.
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/ExitView.swift
  Sources/MapboxNavigation/GenericRouteShield.swift
  Sources/MapboxNavigation/InstructionLabel.swift
  Sources/MapboxNavigation/InstructionPresenter.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NightStyle.swift
  Sources/MapboxNavigation/SpriteRepository.swift
  Sources/MapboxNavigation/WayNameView.swift
  Sources/TestHelper/Fixtures/Images.xcassets/shieldDay.imageset/Contents.json
  Sources/TestHelper/Fixtures/Images.xcassets/shieldDay.imageset/shieldDay.png
  Sources/TestHelper/Fixtures/Images.xcassets/shieldNight.imageset/Contents.json
  Sources/TestHelper/Fixtures/Images.xcassets/shieldNight.imageset/shieldNight.png
  Sources/TestHelper/Fixtures/sprite-info.json
  Tests/MapboxNavigationTests/Constants.swift
  Tests/MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift
  Tests/MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift
  Tests/MapboxNavigationTests/SpriteInfoCacheTests.swift
  Tests/MapboxNavigationTests/SpriteRepositoryTests.swift
  Tests/MapboxNavigationTests/WayNameViewTests.swift
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testSinglelinePrimaryAndSecondaryWithNightShield.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/InstructionsBannerViewSnapshotTests/testSinglelinePrimaryAndSecondaryWithShield.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/14.5/InstructionsBannerViewSnapshotTests/testSinglelinePrimaryAndSecondaryWithNightShield.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/14.5/InstructionsBannerViewSnapshotTests/testSinglelinePrimaryAndSecondaryWithShield.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone14_3/15.2/InstructionsBannerViewSnapshotTests/testSinglelinePrimaryAndSecondaryWithNightShield.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone14_3/15.2/InstructionsBannerViewSnapshotTests/testSinglelinePrimaryAndSecondaryWithShield.1.png
Labels: UI

#3870 Use legacy fallback icon for U.S. state road shields first.
  CHANGELOG.md
  Sources/MapboxNavigation/InstructionPresenter.swift
  Sources/MapboxNavigation/WayNameView.swift
Labels: UI

#3805 Fix bug where transparent `LanesView` displays on update when `StepsTable` is displayed
  CHANGELOG.md
  Sources/MapboxNavigation/TopBannerViewController.swift
Labels: bug

#3877 Fix memory leak which occurred after presenting intermediate waypoint arrival dialog on CarPlay.
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
Labels: bug, UI, CarPlay

#3869 Upgrade to MapboxMaps `v10.5.0`, MapboxNavigationNative `v99.0.0`
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/RerouteControllerDelegate.swift
  Sources/MapboxCoreNavigation/TollCollection.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/RoutesCoordinatorTests.swift
Labels: build

#3880 Stop navigation without dismissing UI
  CHANGELOG.md
  Sources/MapboxCoreNavigation/LegacyRouteController.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/Router.swift
  Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift
Labels: feature, Core, v2.x

#3896 Fix the crash of `routeRemainingDistancesIndex` after reroute.
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Tests/MapboxNavigationTests/VanishingRouteLineTests.swift
Labels: UI

#3901 Update Directions SDK 2.5.0-rc.1
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: op-ex

#3902 Cherry-pick - Update Directions SDK 2.5.0-rc.1 (#3901)
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: op-ex

#3904 Updates for v2.5.0-rc.2
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: op-ex

#3906 Update for v2.6.0-alpha.1
  CHANGELOG.md
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: op-ex

#3897 Add the ability to show route line layers based on the custom layer position.
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView.swift
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
Labels: UI, improvement

#3911 Fix the crash of non-stop shield update in instruction guidance.
  CHANGELOG.md
  Sources/MapboxNavigation/ExitView.swift
  Sources/MapboxNavigation/GenericRouteShield.swift
  Sources/MapboxNavigation/InstructionPresenter.swift
Labels: UI

#3915 Fix Maps SDK dependency in podspec
  MapboxNavigation.podspec
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: op-ex

#3882 Allow `Always show dark maps` option on CarPlay.
  CHANGELOG.md
  Example/ViewController+StyleManager.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/InstructionLabel.swift
  Sources/MapboxNavigation/VisualInstruction.swift
Labels: bug, UI, CarPlay

#3914 Fixed an issue related to `StyleManager` usage on iOS and CarPlay.
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/StyleManager.swift
Labels: bug, UI, CarPlay

#3761 Add new design for floating buttons.
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/FloatingButton.swift
  Sources/MapboxNavigation/InstructionsCardViewController.swift
  Sources/MapboxNavigation/NavigationView.swift
  Sources/MapboxNavigation/ReportButton.swift
  Sources/MapboxNavigation/Resources/Assets.xcassets/feedback/feedback.imageset/feedback.pdf
  Sources/MapboxNavigation/Resources/Assets.xcassets/volume_off.imageset/volume_off.pdf
  Sources/MapboxNavigation/Resources/Assets.xcassets/volume_up.imageset/volume_up.pdf
  Sources/MapboxNavigation/Style.swift
  Sources/MapboxNavigation/UIColor.swift
  Sources/MapboxNavigation/UIView.swift
Labels: UI, drop-in

#3920 Update `MapboxNavigation` to `v2.5.0`
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Package.resolved
  Package.swift
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build

#3921 Merge v2.5.0 release branch to main
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Package.resolved
  Package.swift
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build

#3923 Update to v2.6.0-alpha.2
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build

#3891 Expose geoJSON tolerance to MapView
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: UI, Core
