Repository mapbox/mapbox-navigation-ios, pull requests merged in 2022-04, with the labels that each got.

#3808 Remove the `PassiveLocationManager ` before active navigation.
  Example/ViewController.swift
Labels: UI

#3804 Fix various edge-cases while changing `CLAccuracyAuthorization` and `CLAuthorizationStatus`.
  CHANGELOG.md
  Example/CustomViewController.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/CLLocationManager.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/NavigationMapView+CLLocationManagerDelegate.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationViewController.swift
Labels: UI, CarPlay

#3807 Provide the ability to preview routes that are based on a `RouteResponse` on CarPlay.
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayManager.swift
Labels: UI, CarPlay

#3814 Add grace-period changelog
  CHANGELOG.md
Labels: Core

#3815 Improve tests
  Tests/MapboxCoreNavigationTests/BillingHandlerTests.swift
  Tests/MapboxNavigationTests/CarPlayManagerSpec.swift
Labels: op-ex

#3826 Use current location from `CLLocationManager` to center camera to it.
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: UI

#3811 Fixes bug where non-restricted restricted area line become restricted in an edge case.
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Tests/MapboxNavigationTests/NavigationMapViewTests.swift
Labels: bug

#3828 Add notifications management delegate methods to `CarPlayManagerDelegate`.
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayManagerDelegate.swift
Labels: UI, CarPlay

#3838 Fix the tests and correct the iOS version in documentation.
  CONTRIBUTING.md
  Sources/MapboxCoreNavigation/TileStore.swift
Labels: build, documentation

#3836 Remove the stale style of `UserPuckCourseView`.
  CHANGELOG.md
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/UserCourseView.swift
  Tests/MapboxNavigationTests/UserPuckCourseViewSnapshotTests.swift
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewStalePuckColor.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone12_5/13.7/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewStalePuckColor.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/14.5/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewStalePuckColor.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone13_4/14.5/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewStalePuckColor.2.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone14_3/15.2/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewStalePuckColor.1.png
  Tests/MapboxNavigationTests/__Snapshots__/iPhone14_3/15.2/UserPuckCourseViewSnapshotTests/testUserPuckCourseViewStalePuckColor.2.png
Labels: UI

#3840 Fix the memory cache loss when App in the background.
  CHANGELOG.md
  Sources/MapboxNavigation/ImageCache.swift
  Sources/MapboxNavigation/SpriteInfoCache.swift
Labels: UI

#3842 Pass `EndOfRouteFeedback` to the app
  CHANGELOG.md
  Example/ViewController.swift
  Sources/MapboxCoreNavigation/Feedback/EndOfRouteFeedback.swift
  Sources/MapboxNavigation/ArrivalController.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewControllerDelegate.swift
Labels: feature

#3844 Update Mapbox Navigation to `v2.5.0-beta.1`
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build

#3845 Fix incorrect end of route comment view style.
  CHANGELOG.md
  Sources/MapboxNavigation/DayStyle.swift
Labels: UI

#3837 Add presentation transitions to `NavigationView` top and bottom banners.
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/BannerContainerView.swift
  Sources/MapboxNavigation/BannerView.swift
  Sources/MapboxNavigation/NavigationView.swift
Labels: UI, drop-in

#3851 Base API commit bump
  .base_api
Labels: build

#3848 Mapbox Navigation SDK `v2.2.1`
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Package.resolved
  Package.swift
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxCoreNavigation/NavigationRouteOptions.swift
  Sources/MapboxCoreNavigation/TileStore.swift
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
Labels: build

#3849 Mapbox Navigation SDK `v2.1.2`
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/Info.plist
  LICENSE.md
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Package.resolved
  Package.swift
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxCoreNavigation/NavigationRouteOptions.swift
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  docs/jazzy.yml
Labels: build

#3795 Expose current speed in `SpeedLimitView`.
  CHANGELOG.md
  Example/ViewController+FreeDrive.swift
  Sources/MapboxNavigation/CarPlayMapViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/OrnamentsController.swift
  Sources/MapboxNavigation/SpeedLimitView.swift
Labels: UI

#3854 Mapbox Navigation SDK `v2.5.0-beta.2`.
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build
