Repository mapbox/mapbox-navigation-ios, pull requests merged in 2022-01, with the labels that each got.

#3674 Allow the mapView receives simulated location update.
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/NavigationLocationProvider.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Tests/MapboxNavigationTests/NavigationLocationProviderTests.swift
Labels: UI

#3676 Force update map buttons on CarPlay during active navigation.
  CHANGELOG.md
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayManagerDelegate.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewControllerDelegate.swift
Labels: bug, UI, CarPlay

#3668 Rerouting customiztion rollback
  CHANGELOG.md
  Example/ViewController.swift
  Sources/MapboxCoreNavigation/NavigationService.swift
  Sources/MapboxCoreNavigation/NavigationServiceDelegate.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/Router.swift
  Sources/MapboxCoreNavigation/RouterDelegate.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/NavigationViewControllerDelegate.swift
  Sources/TestHelper/DirectionsSpy.swift
  Sources/TestHelper/NavigationServiceTestDoubles.swift
  Sources/TestHelper/RouterDelegateSpy.swift
  Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
  Tests/MapboxCoreNavigationTests/RouteControllerTests.swift
Labels: release blocker, Core, v2.x

#3664 Improve rerouting logic if all candidates are very different from the initial route
  CHANGELOG.md
  Sources/MapboxCoreNavigation/Router.swift
  Sources/TestHelper/DummyRoute.swift
  Tests/MapboxCoreNavigationTests/RerouteTests.swift
Labels: bug, topic: directions

#3654 Support instant Restricted Areas Route Line update
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView.swift
  Tests/MapboxNavigationTests/VanishingRouteLineTests.swift
Labels: UI

#3687 Fixed the tests check in VanishingRouteLineTests
  Tests/MapboxNavigationTests/VanishingRouteLineTests.swift
Labels: improvement

#3669 Exposing MapMatching status
  CHANGELOG.md
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/CoreConstants.swift
  Sources/MapboxCoreNavigation/MapMatchingResult.swift
  Sources/MapboxCoreNavigation/PassiveLocationManager.swift
  Sources/MapboxCoreNavigation/RouteController.swift
Labels: Core, improvement

#3685 Fix tap gesture to stop camera transitions
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationCamera.swift
Labels: bug

#3692 Building highlighting overlaps POI icons
  CHANGELOG.md
  Sources/MapboxNavigation/NavigationMapView+BuildingHighlighting.swift
Labels: bug, UI

#3693 Update the base api commit.
  .base_api
Labels: build

#3643 Improve landscape layout during active navigation.
  CHANGELOG.md
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example-CarPlay.xcscheme
  MapboxNavigation-SPM.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/BottomBannerViewController.swift
  Sources/MapboxNavigation/BottomBannerViewLayout.swift
  Sources/MapboxNavigation/CameraController.swift
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/Feedback/FeedbackSubtypeCollectionViewCell.swift
  Sources/MapboxNavigation/InstructionsBannerView.swift
  Sources/MapboxNavigation/InstructionsCardViewController.swift
  Sources/MapboxNavigation/LanesView.swift
  Sources/MapboxNavigation/NavigationView.swift
  Sources/MapboxNavigation/NavigationViewDelegate.swift
  Sources/MapboxNavigation/NavigationViewLayout.swift
  Sources/MapboxNavigation/NextBannerView.swift
  Sources/MapboxNavigation/OrnamentsController.swift
  Sources/MapboxNavigation/StepTableViewCell.swift
  Sources/MapboxNavigation/StepsViewController.swift
  Sources/MapboxNavigation/StepsViewControllerDelegate.swift
  Tests/MapboxNavigationTests/GuidanceCardsSnapshotTests.swift
Labels: UI, drop-in

#3694 Update directions dependency to v2.2.0.
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
  Tests/CocoaPodsTest/PodInstall/PodInstall.xcodeproj/project.pbxproj
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: build

#3695 Update MapboxNavigation to v2.2.0
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build

#3699 Fix crash displaying unrecognized lane
  CHANGELOG.md
  Sources/MapboxNavigation/LaneView.swift
  Tests/MapboxNavigationTests/LaneViewTests.swift
Labels: bug, topic: instructions, UI

#3698 Fix test build errors in Swift 5.3
  Tests/MapboxNavigationTests/VanishingRouteLineTests.swift
Labels: build

#3701 Add initializers to RoundingTable and Threshold
  Sources/MapboxCoreNavigation/DistanceFormatter.swift
Labels: bug

#3702 [bugfix] Fix Direction.calculateOffline using hybrid router
  CHANGELOG.md
  Sources/MapboxCoreNavigation/Directions.swift
Labels: bug, Core

#3703 Update dependency to NavigationNative 83.0.1 and Turf 2.2.0
  Cartfile.resolved
  Package.resolved
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: build

#3647 Route linke blinking on refresh
  CHANGELOG.md
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Sources/MapboxCoreNavigation/RouteProgress.swift
Labels: bug, Core

#3711 MapboxMaps v10.2 or above
  MapboxNavigation.podspec
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: build

#3705 Update NN to 87.0.0 and Maps to 10.3.0-beta.1
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift
  Sources/MapboxCoreNavigation/MapboxRoutingProvider.swift
  Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: build
