Repository mapbox/mapbox-navigation-ios, pull requests merged in 2022-06, with the labels that each got.

#3929 Simulation Rerouting fix
  CHANGELOG.md
  Sources/MapboxCoreNavigation/SimulatedLocationManager.swift
Labels: topic: location, bug :beetle:

#3913 Update NavigationNative and MapboxMaps.
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/CLLocation.swift
  Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/CLLocationTests.swift
Labels: build

#3885 Add `BannerContainerViewDelegate`.
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxNavigation/BannerContainerView.swift
  Sources/MapboxNavigation/BannerContainerViewDelegate.swift
Labels: UI, drop-in

#3823 Make `NavigationView` publicly usable.
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  NavigationViewExample/AppDelegate.swift
  NavigationViewExample/Assets.xcassets/AccentColor.colorset/Contents.json
  NavigationViewExample/Assets.xcassets/AppIcon.appiconset/Contents.json
  NavigationViewExample/Assets.xcassets/Contents.json
  NavigationViewExample/Base.lproj/LaunchScreen.storyboard
  NavigationViewExample/Base.lproj/Main.storyboard
  NavigationViewExample/Info.plist
  NavigationViewExample/SceneDelegate.swift
  NavigationViewExample/ViewController.swift
  Sources/MapboxNavigation/NavigationView.swift
Labels: UI, drop-in

#3919 Fix issue with user course view rendering.
  Sources/MapboxNavigation/NavigationMapView.swift
Labels: bug, UI

#3928 Pause and resume navigator when using `RouteController`.
  CHANGELOG.md
  Sources/MapboxCoreNavigation/LegacyRouteController.swift
  Sources/MapboxCoreNavigation/NavigationService.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Tests/MapboxCoreNavigationTests/NavigationServiceTests.swift
Labels: improvement

#3850 Alternative routes display
  CHANGELOG.md
  Example/AppDelegate+CarPlay.swift
  MapboxNavigation.xcodeproj/project.pbxproj
  Sources/MapboxCoreNavigation/LegacyRouteController.swift
  Sources/MapboxCoreNavigation/RouteController.swift
  Sources/MapboxCoreNavigation/Router.swift
  Sources/MapboxNavigation/CarPlayManager.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/NavigationMapView+ContinuousAlternatives.swift
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/NavigationMapViewDelegate.swift
  Sources/MapboxNavigation/NavigationViewController.swift
  Sources/MapboxNavigation/RouteLineController.swift
Labels: feature, UI

#3942 Enable disabled vanishing route line tests.
  Tests/MapboxNavigationTests/VanishingRouteLineTests.swift
Labels: op-ex

#3950 Pin Mapbox Common to 22.0.0-rc.2 in CocoaPods spec
  CHANGELOG.md
  Gemfile.lock
  MapboxCoreNavigation.podspec
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: op-ex

#3855 Make `NavigationMapView` route line traversal feature public for active navigation.
  CHANGELOG.md
  Example/CustomViewController.swift
  Sources/MapboxNavigation/CarPlayNavigationViewController.swift
  Sources/MapboxNavigation/NavigationMapView+VanishingRouteLine.swift
  Sources/MapboxNavigation/NavigationMapView.swift
  Sources/MapboxNavigation/RouteLineController.swift
Labels: feature, UI

#3954 Allow the detailed feedback style change.
  CHANGELOG.md
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/Feedback/FeedbackSubtypeCollectionViewCell.swift
  Sources/MapboxNavigation/Feedback/FeedbackSubtypeViewController.swift
  Sources/MapboxNavigation/NightStyle.swift
  Sources/MapboxNavigation/StyleManager.swift
Labels: UI

#3955 Update dependencies.
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  Package.resolved
  Package.swift
  Sources/MapboxCoreNavigation/NativeHandlersFactory.swift
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
Labels: build

#3969 Update to `v2.6.0-rc.1`
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Example/Info.plist
  MapboxCoreNavigation.podspec
  MapboxNavigation-SPM.xcodeproj/project.pbxproj
  MapboxNavigation-SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxNavigation.podspec
  MapboxNavigation.xcodeproj/project.pbxproj
  Package.resolved
  Package.swift
  README.md
  Sources/CarPlayTestHelper/Info.plist
  Sources/MapboxCoreNavigation/Info.plist
  Sources/MapboxCoreNavigation/MBXInfo.plist
  Sources/MapboxNavigation/Info.plist
  Sources/MapboxNavigation/MBXInfo.plist
  Sources/TestHelper/Info.plist
  Tests/CocoaPodsTest/PodInstall/Podfile.lock
  Tests/MapboxCoreNavigationTests/Info.plist
  Tests/MapboxNavigationTests/Info.plist
  custom-navigation.md
Labels: build

#3922 Fix `StyleManager` default style updates.
  CHANGELOG.md
  Sources/MapboxNavigation/DayStyle.swift
  Sources/MapboxNavigation/NightStyle.swift
  Sources/MapboxNavigation/Style.swift
  Sources/MapboxNavigation/StyleManager.swift
  Tests/MapboxNavigationTests/CarPlayCompassViewSnapshotTests.swift
Labels: bug, release blocker, UI, CarPlay
